import Link from 'next/link';
import { WorkflowSteps } from '@/components/workflow-steps';
import { ProspectReport } from '@/components/prospect-report';
import { buildProspectReport, listCandidateContacts } from '@/lib/research-report';
import { linkCandidateCompanyAction } from '@/app/v2-actions';
import { requireAuthenticated } from '@/lib/auth';
import { getCampaignRepository } from '@/lib/campaign-runtime';
import { CampaignMutation, RunRefresh } from '@/components/campaign-forms';
import { confirmWebsiteAction, controlRunAction, reviewCandidateAction } from '@/app/campaign-actions';
const labels:Record<string,string>={queued:'En file',processing:'Analyse en cours',needs_site:'Site à confirmer',review:'À examiner',accepted:'Retenue',rejected:'Écartée',verify:'À vérifier'};
const runLabels:Record<string,string>={queued:'En file',running:'En cours',paused:'En pause',completed:'Analyse terminée',failed:'Interrompu',cancelled:'Annulé'};
export default async function RunPage({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{filtre?:string;candidat?:string}>}){
  await requireAuthenticated();const {id}=await params,{filtre='review',candidat}=await searchParams,repo=await getCampaignRepository(),run=await repo.getRun(id),all=await repo.listCandidates(id);
  const rows=all.filter(c=>filtre==='all'||filtre==='review'?filtre==='all'||['review','needs_site','queued','processing'].includes(c.status):filtre==='complete'?['needs_site','verify'].includes(c.status):c.status===filtre).sort((a,b)=>Number(Boolean(b.html?.contacts.length&&(b.html?.findings.length||b.mobile?.findings.length)))-Number(Boolean(a.html?.contacts.length&&(a.html?.findings.length||a.mobile?.findings.length))));
  const selected=rows.find(c=>c.id===candidat)||rows[0],active=['queued','running'].includes(run.status);
  const findings=[...(selected?.html?.findings||[]),...(selected?.mobile?.findings||[])],contacts=selected?listCandidateContacts(selected):[],report=selected?buildProspectReport(selected,run.target):null;
  const knownCompanies=await repo.listCompanies(run.campaignId);
  const approach=findings.find(f=>f.approach)?.approach||'';
  return <><WorkflowSteps campaignId={run.campaignId} active="examiner" runId={id}/><Link href={`/campagnes/${run.campaignId}?onglet=research`} className="back-link">← {run.target.name}</Link><div className="page-heading"><div><p className="eyebrow">{run.target.targetBusiness} · {run.target.targetCity}</p><h1>Votre lot de recherche</h1><p className="page-subtitle">{runLabels[run.status]} · {all.filter(c=>!['queued','processing'].includes(c.status)).length}/{active&&!all.length?run.limit:all.length} entreprises traitées</p></div><RunRefresh active={active}/></div>
    <section className="panel section-panel"><p role="status" aria-live="polite">{active?'Le traitement continue même si vous fermez cette page.':'Les résultats sont enregistrés. Vous pouvez les examiner à votre rythme.'} {all.filter(c=>c.status==='needs_site').length} site(s) à compléter.</p>{run.error&&<p className={run.status==='completed'?'field-help':'form-error'}>{run.error}</p>}<div className="campaign-controls">{active&&<CampaignMutation action={controlRunAction} submit="Suspendre le lot" secondary><input type="hidden" name="runId" value={id}/><input type="hidden" name="operation" value="pause"/></CampaignMutation>}{['paused','failed','queued'].includes(run.status)&&<CampaignMutation action={controlRunAction} submit={run.status==='queued'?'Relancer la prise en charge':'Reprendre le lot'} secondary><input type="hidden" name="runId" value={id}/><input type="hidden" name="operation" value="resume"/></CampaignMutation>}{!['completed','cancelled'].includes(run.status)&&<CampaignMutation action={controlRunAction} submit="Annuler le lot" secondary><input type="hidden" name="runId" value={id}/><input type="hidden" name="operation" value="cancel"/></CampaignMutation>}</div></section>
    {!active&&!all.length&&<p className="inline-empty">Aucune nouvelle entreprise trouvée dans les limites de cette recherche. Les entreprises déjà présentes dans la campagne ou ayant une opposition sont exclues.</p>}
    <nav className="filter-tabs" aria-label="Filtrer les résultats">{[['review','À examiner'],['complete','À compléter'],['accepted','Retenues'],['rejected','Écartées'],['all','Toutes']].map(([key,label])=><Link key={key} href={`/campagnes/lots/${id}?filtre=${key}`} className={filtre===key?'selected':''}>{label}</Link>)}</nav>
    <div className={`review-layout ${candidat?'review-has-selection':''}`}><aside className="review-list" aria-label="Entreprises du lot">{rows.length?rows.map(c=><Link scroll={false} key={c.id} href={`/campagnes/lots/${id}?filtre=${filtre}&candidat=${c.id}`} className={`panel review-list-item ${c.id===selected?.id?'selected':''}`}><strong>{c.company.name}</strong><span className="small muted">{c.company.city} · {c.company.business}</span><span className="badge">{labels[c.status]}</span></Link>):<p className="inline-empty">{active?'Les premiers résultats apparaîtront ici.':'Aucun résultat dans ce filtre.'}</p>}</aside>
    {selected&&<section className="panel section-panel review-detail" key={`${selected.id}:${selected.revision}`}><Link href={`/campagnes/lots/${id}?filtre=${filtre}`} className="back-link review-mobile-back">← Revenir à la liste</Link><div className="section-title"><h2>{selected.company.name}</h2><span className="badge">{labels[selected.status]}</span></div><p>{selected.company.city} · {selected.company.business}</p><a href={selected.company.sourceUrl} className="open-link" target="_blank" rel="noopener noreferrer">Source de l’entreprise ↗</a>
      {selected.website&&<p><a href={selected.website} target="_blank" rel="noopener noreferrer">{selected.website}</a></p>}{selected.websites.map(p=><p key={p.url} className="small"><a href={p.url} target="_blank" rel="noopener noreferrer">{p.url}</a> · <a href={p.sourceUrl} target="_blank" rel="noopener noreferrer">Source du site</a> · {p.confidence==='exact'?'SIRET correspondant':'À confirmer'}</p>)}
      {!['accepted','rejected','processing'].includes(selected.status)&&<details open={selected.status==='needs_site'}><summary>{selected.website?'Corriger le site':'Confirmer ou renseigner le site'}</summary><div className="details-body"><CampaignMutation action={confirmWebsiteAction} submit="Confirmer le site et analyser" secondary><input type="hidden" name="candidateId" value={selected.id}/><input type="hidden" name="revision" value={selected.revision}/><div className="field"><label htmlFor="candidate-website">Site officiel</label><input name="website" id="candidate-website" type="url" required defaultValue={selected.website||selected.websites[0]?.url||''} placeholder="https://…"/></div><p className="field-help">Un site non trouvé dans ces sources ne signifie pas que l’entreprise n’a pas de site.</p></CampaignMutation></div></details>}
      {selected.htmlError&&<p className="field-help">HTML / recherche du site : {selected.htmlError}</p>}{selected.mobileError&&<p className="field-help">Test mobile indisponible : {selected.mobileError}. Les autres résultats sont conservés.</p>}{[...(selected.html?.warnings||[]),...(selected.mobile?.warnings||[])].map((w,i)=><p className="field-help" key={i}>{w}</p>)}
      {!['processing','queued'].includes(selected.status)&&<CampaignMutation action={reviewCandidateAction}>
        <input type="hidden" name="candidateId" value={selected.id}/><input type="hidden" name="revision" value={selected.revision}/>
        {report&&<ProspectReport report={report} selectionName="findingId" printHref={'/campagnes/rapports/candidat/'+selected.id}/>}
        <h3>Contacts professionnels</h3>{contacts.length?contacts.map((c,i)=><label className="check-label" key={`${c.kind}:${i}`}><input type="checkbox" name="contactIndex" value={i}/><span>{c.value} · <a href={c.sourceUrl} target="_blank" rel="noopener noreferrer">Source</a></span></label>):<p className="field-help">Aucun contact extrait. À compléter sur la fiche.</p>}
        <details><summary>Note d’approche facultative</summary><div className="field"><label htmlFor="candidate-approach">Angle pour cette campagne</label><textarea id="candidate-approach" name="approach" maxLength={4000} defaultValue={approach?`${approach}${run.target.targetOffer?`\nOffre proposée : ${run.target.targetOffer}`:''}`:''} placeholder="Choisissez un fait et adaptez votre approche à l’offre de cette campagne."/></div><p className="field-help">Le dossier complet est conservé. Les preuves sélectionnées préparent votre motif ; les contacts choisis complètent la fiche.</p></details><div className="button-row review-decisions"><button name="decision" value="accept" className="button primary">Garder dans la campagne</button><button name="decision" value="verify" className="button secondary">Plus tard</button><button name="decision" value="reject" className="button text-button">Écarter</button></div>
      </CampaignMutation>}
      {!selected.companyId&&knownCompanies.length>0&&<details><summary>Confirmer un rapprochement avec une fiche connue</summary><div className="details-body"><CampaignMutation action={linkCandidateCompanyAction} submit="Confirmer l’identité commune" secondary><input type="hidden" name="candidateId" value={selected.id}/><input type="hidden" name="revision" value={selected.revision}/><label htmlFor="identity-company">Entreprise correspondante</label><select name="companyId" id="identity-company" required defaultValue=""><option value="" disabled>Choisir la fiche vérifiée</option>{knownCompanies.map(c=><option key={c.id} value={c.id}>{c.name} · {c.city}</option>)}</select><p className="field-help">Confirmez uniquement après vérification. Un nom, une ville ou un domaine semblable ne suffisent pas.</p></CampaignMutation></div></details>}
      {selected.status==='accepted'&&selected.companyId&&<Link href={'/campagnes/'+run.campaignId+'?etape=preparer&prospect='+selected.companyId} className="button primary">Préparer ce contact →</Link>}
    </section>}
    </div>
    {!active&&all.length>0&&rows.length===0&&<Link className="button primary" href={'/campagnes/'+run.campaignId+'?etape=preparer'}>Passer à la préparation des contacts →</Link>}
  </>;
}
