import Link from 'next/link';
import { redirect } from 'next/navigation';
import { QualificationSummary } from '@/components/qualification-summary';
import { notFound } from 'next/navigation';
import { requireAuthenticated } from '@/lib/auth';
import { getCampaignRepository } from '@/lib/campaign-runtime';
import { getStore } from '@/lib/db';
import { CampaignForm, CampaignMutation, LaunchForm, ExistingAnalysisForm } from '@/components/campaign-forms';
import { CampaignProvider } from '@/components/campaign-context';
import { AddCompany } from '@/components/forms';
import { WorkflowSteps } from '@/components/workflow-steps';
import { ProspectWork } from '@/components/prospect-work';
import { ResearchStatus } from '@/components/research-status';
import { ContactOutcomeForm } from '@/components/contact-workspace';
import { parisToday } from '@/lib/domain';
import { campaignStatusAction, duplicateCampaignAction, attachCompanyAction } from '@/app/campaign-actions';
const labels:Record<string,string>={queued:'En file',running:'En cours',paused:'En pause',completed:'À examiner',failed:'Interrompu',cancelled:'Annulé'};
export default async function CampaignDetail({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{onglet?:string;etape?:string;prospect?:string}>}){
  await requireAuthenticated();const {id}=await params,query=await searchParams,repo=await getCampaignRepository();const campaign=(await repo.listCampaigns()).find(c=>c.id===id);if(!campaign)notFound();
  const step=query.etape||(query.onglet==='prospects'?'preparer':'rechercher');
  if(query.etape==='examiner')redirect(`/campagnes/${id}/qualification`);
  const [companies,runs,shared]=await Promise.all([repo.listCompanies(id),repo.listRuns(id),getStore().listCompanies()]),known=new Set(companies.map(c=>c.id));
  const selected=companies.find(c=>!c.archived&&c.id===query.prospect)||companies.find(c=>!c.archived&&!c.oppositionActive);
  return <CampaignProvider id={id}>
    <Link href="/campagnes" className="back-link">← Campagnes</Link><div className="page-heading"><div><p className="eyebrow">{campaign.targetBusiness} · {campaign.targetCity}</p><h1>{campaign.name}</h1><p className="page-subtitle">{campaign.targetOffer||'Pickles Studio · Sites, UX/UI et applications'} · {campaign.status==='active'?'Active':campaign.status==='paused'?'En pause':'Archivée'}</p></div><AddCompany settings={campaign}/></div>
    <WorkflowSteps campaignId={id} active={step} runId={runs[0]?.id}/>
    {step==='cibler'&&<section className="panel section-panel"><h2>Votre cible et la raison de cette campagne</h2><p>Définissez les professionnels recherchés et l’aide que vous pouvez leur proposer. Les codes NAF restent facultatifs.</p><CampaignForm campaign={campaign} defaults={campaign}/></section>}
    {step==='rechercher'&&<><details className="panel section-panel"><summary>Ma cible et spécialisation de campagne</summary><CampaignForm campaign={campaign} defaults={campaign}/></details><p><Link className="button primary" href={`/campagnes/${id}/qualification`}>Qualifier les entreprises trouvées →</Link></p><ResearchStatus/><div className="campaign-detail-grid"><section className="panel section-panel"><h2>Trouver des entreprises</h2><LaunchForm campaignId={id} disabled={campaign.status!=='active'}/></section><section className="panel section-panel"><h2>Vos lots</h2>{runs.length?runs.map(r=><Link key={r.id} href={`/campagnes/${id}/qualification`} className="campaign-run-link"><span>{new Intl.DateTimeFormat('fr-FR',{dateStyle:'short',timeStyle:'short',timeZone:'Europe/Paris'}).format(new Date(r.createdAt))} · {r.limit} entreprises</span><span className="badge">{labels[r.status]}</span></Link>):<p className="inline-empty">Lancez votre premier lot pour préparer des pistes à examiner.</p>}</section></div><details className="panel section-panel"><summary>Actualiser les dossiers de mes prospects existants</summary><div className="details-body"><ExistingAnalysisForm campaignId={id} companies={companies.filter(c=>!c.archived&&!c.oppositionActive)}/></div></details></>}
    {step==='examiner'&&<section className="panel section-panel"><h2>Examiner les résultats</h2>{runs.map(r=><Link key={r.id} href={`/campagnes/${id}/qualification`} className="campaign-run-link"><span>Lot du {r.createdAt.slice(0,10)}</span><span>{labels[r.status]}</span></Link>)}{!runs.length&&<Link href={'/campagnes/'+id+'?etape=rechercher'} className="button primary">Lancer mon premier lot</Link>}</section>}
    {['preparer','suivre'].includes(step)&&<div className={'review-layout '+(query.prospect?'review-has-selection':'')}><aside className="review-list" aria-label="Prospects de cette campagne">{companies.filter(c=>!c.archived).map(c=><Link scroll={false} key={c.id} href={'/campagnes/'+id+'?etape='+step+'&prospect='+c.id} className={'panel review-list-item '+(c.id===selected?.id?'selected':'')}><strong>{c.name}</strong><span className="small muted">{step==='suivre'?c.nextAction?.text||'Aucun suivi prévu':c.plan?'Plan enregistré':'Motif à choisir'}</span><span className="badge">{c.oppositionActive?'Ne plus contacter':c.stage}</span></Link>)}{!companies.some(c=>!c.archived)&&<p className="inline-empty">Gardez d’abord une entreprise à l’étape Examiner.</p>}</aside>{selected&&<section className="panel section-panel review-detail"><Link href={'/campagnes/'+id+'?etape='+step} className="back-link review-mobile-back">← Liste des prospects</Link><div className="section-title"><h2>{selected.name}</h2><Link className="open-link small" href={'/prospects/'+selected.id+'?campagne='+id}>Compléter la fiche ↗</Link></div><QualificationSummary company={selected} settings={campaign} today={parisToday()} criteriaHref={'/prospects/'+selected.id+'?campagne='+id}/>{step==='preparer'?<ProspectWork company={selected} campaign={campaign}/>:<><h3>Enregistrer l’action et décider de la suite</h3><ContactOutcomeForm key={campaign.id+':'+selected.id} company={selected} campaign={campaign} today={parisToday()}/>{selected.contactEvents?.length? <details className="workspace-detail"><summary>Contacts enregistrés</summary>{selected.contactEvents.map(e=><p key={e.id}>{e.date} · {e.channel} · {e.outcome}<br/>{e.note}<br/>{e.nextAction?'Suite : '+e.nextAction.text+' le '+e.nextAction.date:'Aucun suivi prévu'}</p>)}</details>:null}</>}</section>}</div>}
    <details className="panel section-panel"><summary>Gestion et entreprises déjà connues</summary><div className="details-body stack"><CampaignMutation action={attachCompanyAction} submit="Rattacher à cette campagne" secondary><input type="hidden" name="campaignId" value={id}/><div className="field"><label htmlFor="attach-company">Entreprise déjà connue</label><select name="companyId" id="attach-company" required defaultValue=""><option value="" disabled>Choisir une entreprise</option>{shared.filter(c=>!known.has(c.id)).map(c=><option key={c.id} value={c.id}>{c.name} · {c.city}</option>)}</select></div></CampaignMutation><div className="campaign-controls"><CampaignMutation action={duplicateCampaignAction} submit="Dupliquer la configuration" secondary><input type="hidden" name="id" value={id}/></CampaignMutation><CampaignMutation action={campaignStatusAction} submit={campaign.status==='active'?'Mettre en pause':'Réactiver'} secondary><input type="hidden" name="id" value={id}/><input type="hidden" name="revision" value={campaign.revision}/><input type="hidden" name="status" value={campaign.status==='active'?'paused':'active'}/></CampaignMutation>{campaign.status!=='archived'&&<CampaignMutation action={campaignStatusAction} submit="Archiver la campagne" secondary><input type="hidden" name="id" value={id}/><input type="hidden" name="revision" value={campaign.revision}/><input type="hidden" name="status" value="archived"/><p className="field-help">L’historique est conservé. Les lots et actions actifs sont suspendus.</p></CampaignMutation>}</div></div></details>
  </CampaignProvider>;
}
