import Link from 'next/link';
import { notFound } from 'next/navigation';
import { requireAuthenticated } from '@/lib/auth';
import { getCampaignRepository } from '@/lib/campaign-runtime';
import { getStore } from '@/lib/db';
import { CampaignForm, CampaignMutation, LaunchForm, ExistingAnalysisForm } from '@/components/campaign-forms';
import { CampaignProvider } from '@/components/campaign-context';
import { AddCompany } from '@/components/forms';
import { ScoreCell } from '@/components/qualification-summary';
import { parisToday } from '@/lib/domain';
import { campaignStatusAction, duplicateCampaignAction, attachCompanyAction } from '@/app/campaign-actions';
const labels:Record<string,string>={queued:'En file',running:'En cours',paused:'En pause',completed:'À examiner',failed:'Interrompu',cancelled:'Annulé'};
export default async function CampaignDetail({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{onglet?:string}>}){
  await requireAuthenticated();const {id}=await params,{onglet='overview'}=await searchParams,repo=await getCampaignRepository();const campaign=(await repo.listCampaigns()).find(c=>c.id===id);if(!campaign)notFound();
  const [companies,runs,shared]=await Promise.all([repo.listCompanies(id),repo.listRuns(id),getStore().listCompanies()]);const known=new Set(companies.map(c=>c.id));return <CampaignProvider id={id}>
    <Link href="/campagnes" className="back-link">← Campagnes</Link><div className="page-heading"><div><p className="eyebrow">{campaign.targetBusiness} · {campaign.targetCity}</p><h1>{campaign.name}</h1><p className="page-subtitle">{campaign.targetOffer||'Offre à préciser'} · {campaign.status==='active'?'Active':campaign.status==='paused'?'En pause':'Archivée'}</p></div><AddCompany settings={campaign}/></div>
    <nav className="filter-tabs" aria-label="Sections de la campagne">{[['overview','Vue d’ensemble'],['research','Recherches'],['prospects','Prospects']].map(([key,label])=><Link key={key} href={`/campagnes/${id}?onglet=${key}`} className={onglet===key?'selected':''}>{label}</Link>)}</nav>
    {onglet!=='prospects'&&<div className="campaign-detail-grid"><section className="panel section-panel"><h2>Trouver des entreprises</h2><LaunchForm campaignId={id} disabled={campaign.status!=='active'}/></section><section className="panel section-panel"><h2>Vos lots</h2>{runs.length?runs.map(r=><Link key={r.id} href={`/campagnes/lots/${r.id}`} className="campaign-run-link"><span>{new Intl.DateTimeFormat('fr-FR',{dateStyle:'short',timeStyle:'short',timeZone:'Europe/Paris'}).format(new Date(r.createdAt))} · {r.limit} entreprises</span><span className="badge">{labels[r.status]}</span></Link>):<p className="inline-empty">Lancez votre premier lot pour préparer des pistes à examiner.</p>}</section></div>}
    {onglet==='prospects'&&<><section className="panel section-panel"><h2>Prospects de cette campagne</h2>{companies.length?<div className="prospects-table-wrap"><table className="prospects-table"><thead><tr><th>Entreprise</th><th>Qualification</th><th>Étape</th><th>Prochaine action</th></tr></thead><tbody>{companies.map(c=><tr key={c.id}><td data-label="Entreprise"><Link href={`/prospects/${c.id}?campagne=${id}`} className="company-name">{c.name}</Link></td><td data-label="Qualification"><ScoreCell company={c} settings={campaign} today={parisToday()}/></td><td data-label="Étape">{c.archived?'Archivée':c.stage}</td><td data-label="Prochaine action">{c.nextAction?.text||'À planifier'}</td></tr>)}</tbody></table></div>:<p className="inline-empty">Les entreprises retenues apparaîtront ici.</p>}</section><section className="panel section-panel"><h2>Analyser les sites des prospects</h2>{campaign.status==='active'?<ExistingAnalysisForm campaignId={id} companies={companies.filter(c=>!c.archived&&!c.oppositionActive)}/>:<p>Réactivez la campagne pour lancer une analyse.</p>}</section></>}
    <details className="panel section-panel"><summary>Rattacher une entreprise déjà connue</summary><div className="details-body"><CampaignMutation action={attachCompanyAction} submit="Rattacher à cette campagne" secondary><input type="hidden" name="campaignId" value={id}/><div className="field"><label htmlFor="attach-company">Entreprise</label><select name="companyId" id="attach-company" required defaultValue=""><option value="" disabled>Choisir une entreprise</option>{shared.filter(c=>!known.has(c.id)).map(c=><option key={c.id} value={c.id}>{c.name} · {c.city}</option>)}</select></div><p className="field-help">Les contacts restent communs. La qualification de cette campagne commence à zéro.</p></CampaignMutation></div></details>
    <details className="panel section-panel"><summary>Modifier la cible et l’offre</summary><div className="details-body"><CampaignForm campaign={campaign} defaults={campaign}/></div></details>
    <section className="panel section-panel"><h2>Gérer la campagne</h2><div className="campaign-controls"><CampaignMutation action={duplicateCampaignAction} submit="Dupliquer la configuration" secondary><input type="hidden" name="id" value={id}/></CampaignMutation><CampaignMutation action={campaignStatusAction} submit={campaign.status==='active'?'Mettre en pause':'Réactiver'} secondary><input type="hidden" name="id" value={id}/><input type="hidden" name="revision" value={campaign.revision}/><input type="hidden" name="status" value={campaign.status==='active'?'paused':'active'}/></CampaignMutation>{campaign.status!=='archived'&&<CampaignMutation action={campaignStatusAction} submit="Archiver la campagne" secondary><input type="hidden" name="id" value={id}/><input type="hidden" name="revision" value={campaign.revision}/><input type="hidden" name="status" value="archived"/><p className="field-help">Les lots seront suspendus et {companies.filter(c=>c.nextAction).length} action(s) quitteront le programme actif. L’historique est conservé.</p></CampaignMutation>}</div></section>
  </CampaignProvider>;
}
