import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync,rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { randomUUID } from 'node:crypto';
import { createClient } from '@libsql/client';
import { PDFDocument } from 'pdf-lib';
import { Store } from '../lib/db';
import { AsyncCloudStore } from '../lib/cloud-db';
import { CampaignRepository } from '../lib/campaign-repository';
import { buildClientBrief } from '../lib/client-brief-build';
import { saveClientBrief,getClientBrief,briefNeedsUpdate,clientBriefWordCount } from '../lib/client-brief';
import { renderClientBriefPdf,BriefLayoutError } from '../lib/client-brief-pdf';
import { storeResearchAsset,getResearchAsset } from '../lib/research-assets';
import { isClientBriefFact } from '../lib/client-brief-rules';
import { comparisonSchema } from '../lib/comparison';
import { parisToday,backupSchema } from '../lib/domain';
import { visualCaptureFixture } from './fixtures/visual-capture';
import type { DiscoveryCandidate } from '../lib/campaign-types';
async function fixture(kind:'local'|'cloud'){
 const dir=mkdtempSync(join(tmpdir(),'brine-client-brief-')),path=join(dir,'data.sqlite'),base=kind==='local'?new Store(path):new AsyncCloudStore(createClient({url:`file:${path}`}));await base.listCompanies();const repo=new CampaignRepository(createClient({url:`file:${path}`}));await repo.bootstrap();const campaign=await repo.saveCampaign({name:'Rénovation',targetCity:'Montpellier',targetBusiness:'Rénovation',targetOffer:'',targetCompanyType:'Artisans',targetExclusions:'',activityCodes:'',keywords:'rénovation'}),run=await repo.createRun(campaign.id,10,randomUUID()),asset=await storeResearchAsset(repo,Buffer.from(visualCaptureFixture.split(',')[1],'base64'));
 const c:DiscoveryCandidate={id:randomUUID(),runId:run.id,companyId:null,company:{name:'Entreprise de recette',siren:'',siret:'',city:'Montpellier',business:'Rénovation',activityCode:'',address:'',sourceUrl:'https://artisan.example/'},website:'https://artisan.example/',websites:[],status:'review',html:null,mobile:null,htmlError:'',mobileError:'',attempts:{},revision:1,research:{sources:[{id:'source',provider:'website',url:'https://artisan.example/',title:'Page consultée',excerpt:'Preuve de recette',collectedAt:parisToday()}],facts:Array.from({length:12},(_,index)=>({id:'fact-'+index,kind:'observed',section:'site',sentiment:index<3?'issue':'positive',text:index===0?'Le bouton Comparer masque une partie des photographies.':`Observation ${index+1} conservée dans le dossier.`,sourceIds:['source'],observedOn:parisToday(),scope:'Scénario de test.',review:{state:'confirmed',nature:'observation',provenance:'manual'},...(index===0?{visual:{category:'overlap',device:'desktop',element:'Comparer',pageUrl:'https://artisan.example/',assetId:asset.id,viewport:{width:1280,height:900}}}:{})})),contacts:[{kind:'email',value:'contact@artisan.example',sourceId:'source',sourceUrl:'https://artisan.example/'}],profiles:[],warnings:[]}};
 await repo.transaction(tx=>repo.putCandidate(tx,c));const id=(await repo.reviewCandidate(c.id,1,'accept',['fact-0'],[0],''))!;
 return {repo,base,campaign,c,id,asset,close(){repo.close();base.close();rmSync(dir,{recursive:true,force:true});}};
}
async function form(f:Awaited<ReturnType<typeof fixture>>){const report=(await f.repo.getCompanyReport(f.campaign.id,f.id))!,profile=await f.repo.getProviderProfile(),data=new FormData();data.set('campaignId',f.campaign.id);data.set('companyId',f.id);data.set('reportId',report.id);data.set('profileRevision',String(profile.revision));data.set('payload',JSON.stringify({situation:'Votre site présente vos prestations de rénovation et des réalisations à Montpellier.',positives:'Les coordonnées de contact sont accessibles.',points:[{factId:'fact-0',text:'Le bouton Comparer masque une partie des photos.',effect:'La comparaison des réalisations peut être moins facile.',help:'Vérifier cet affichage et corriger la taille du bouton.'}],actions:['Reproduire le défaut sur la page et sur téléphone.','Corriger cet élément puis vérifier la présentation des photos.'],invitation:'Quel parcours souhaitez-vous privilégier pour présenter vos réalisations ?'}));return data;}
for(const kind of ['local','cloud'] as const){
 test(`${kind}: a real immutable two-page PDF uses only confirmed selected facts while all twelve observations remain in the report`,async()=>{const f=await fixture(kind);try{
  const brief=await buildClientBrief(f.repo,await form(f),randomUUID());const bytes=await renderClientBriefPdf(brief,id=>getResearchAsset(f.repo,id)),pdf=await PDFDocument.load(bytes);assert.equal(pdf.getPageCount(),2);for(const page of pdf.getPages()){assert.ok(Math.abs(page.getWidth()-595.28)<.01);assert.ok(Math.abs(page.getHeight()-841.89)<.01);}assert.ok(bytes.length<4*1024*1024);assert.ok(clientBriefWordCount(brief)<=450);const before=(await f.repo.client.execute('SELECT COUNT(*) n FROM research_operations')).rows[0].n;
  await Promise.all([saveClientBrief(f.repo,brief),saveClientBrief(f.repo,brief)]);assert.equal((await f.repo.client.execute('SELECT COUNT(*) n FROM research_client_briefs')).rows[0].n,1);assert.deepEqual(await getClientBrief(f.repo,brief.id),brief);assert.equal((await f.repo.getCompanyReport(f.campaign.id,f.id))!.facts.filter(fact=>/^fact-/.test(fact.id)).length,12);
  const repeat=await renderClientBriefPdf(brief,id=>getResearchAsset(f.repo,id));assert.deepEqual(repeat,bytes);assert.equal((await f.repo.client.execute('SELECT COUNT(*) n FROM research_operations')).rows[0].n,before);assert.equal(await briefNeedsUpdate(f.repo,brief),false);
  const context=await f.repo.getQualificationContext(f.c.id);await f.repo.reviewFinding(f.c.id,context.candidate.revision,'fact-0','rejected');assert.equal(await briefNeedsUpdate(f.repo,brief),true);assert.deepEqual(await renderClientBriefPdf((await getClientBrief(f.repo,brief.id))!,id=>getResearchAsset(f.repo,id)),bytes);await assert.rejects(saveClientBrief(f.repo,{...brief,id:randomUUID()}),/confirmés/);
 }finally{f.close();}});
 test(`${kind}: private assets, drafts and client brief versions round-trip to a new database with bounded files staged once`,async()=>{const f=await fixture(kind),fresh=await fixture(kind);try{
  const brief=await buildClientBrief(f.repo,await form(f),randomUUID());await saveClientBrief(f.repo,brief);const backup=await f.base.exportBackup();assert.equal(backup.schemaVersion,6);assert.ok(backupSchema.safeParse(backup).success);assert.equal(backup.campaignData?.assets?.length,1);assert.ok(!JSON.stringify(backup).includes('base64'));
  await fresh.repo.client.execute('DELETE FROM research_assets');const before=await fresh.base.exportBackup();await assert.rejects(Promise.resolve().then(()=>fresh.base.restoreBackup(backup,true)),/captures.*manquent/);assert.deepEqual((await fresh.base.exportBackup()).companies,before.companies);
  const bytes=(await getResearchAsset(f.repo,f.asset.id))!;await storeResearchAsset(fresh.repo,bytes);await storeResearchAsset(fresh.repo,bytes);assert.equal((await fresh.repo.client.execute('SELECT COUNT(*) n FROM research_assets')).rows[0].n,1);await fresh.base.restoreBackup(backup,true);await fresh.repo.bootstrap();assert.deepEqual(await getClientBrief(fresh.repo,brief.id),brief);assert.deepEqual((await fresh.repo.getCandidate(f.c.id)).research?.facts,f.c.research?.facts);assert.ok(await getResearchAsset(fresh.repo,f.asset.id));
 }finally{fresh.close();f.close();}});
 test(`${kind}: excessive text, missing captures and internal notes are rejected explicitly rather than silently cut`,async()=>{const f=await fixture(kind);try{
  const data=await form(f),brief=await buildClientBrief(f.repo,data,randomUUID());const long={...brief,situation:Array.from({length:460},()=> 'mot').join(' ')};await assert.rejects(renderClientBriefPdf(long,id=>getResearchAsset(f.repo,id)),BriefLayoutError);assert.equal(long.situation.split(' ').length,460);await assert.rejects(renderClientBriefPdf(brief,async()=>null),/capture confirmée manque/);
  const report=(await f.repo.getCompanyReport(f.campaign.id,f.id))!,internal={...report.facts[0],origin:'qualification' as const};assert.equal(isClientBriefFact(internal,report),false);assert.equal(isClientBriefFact({...report.facts[0],review:{state:'proposed',nature:'observation',provenance:'render'}},report),false);
 }finally{f.close();}});
 test(`${kind}: updating comparability or the provider profile marks a saved PDF stale without rewriting it`,async()=>{const f=await fixture(kind);try{
  const comparison=comparisonSchema.parse({id:randomUUID(),campaignId:f.campaign.id,companyId:f.id,createdAt:new Date().toISOString(),targetRevision:f.campaign.revision,queries:[],competitors:[{name:'Autre entreprise',url:'https://other.example/',sourceUrl:'https://other.example/',notes:['Prestations publiées.'],checkedAt:new Date().toISOString(),confirmed:true}],warnings:[]});await f.repo.client.execute({sql:'INSERT INTO research_comparisons(id,campaignId,companyId,payload) VALUES(?,?,?,?)',args:[comparison.id,comparison.campaignId,comparison.companyId,JSON.stringify(comparison)]});const brief=await buildClientBrief(f.repo,await form(f),randomUUID());await saveClientBrief(f.repo,brief);assert.equal(await briefNeedsUpdate(f.repo,brief),false);
  const next={...comparison,id:randomUUID(),competitors:[{...comparison.competitors[0],confirmed:false}]};await f.repo.client.execute({sql:'INSERT INTO research_comparisons(id,campaignId,companyId,payload) VALUES(?,?,?,?)',args:[next.id,next.campaignId,next.companyId,JSON.stringify(next)]});assert.equal(await briefNeedsUpdate(f.repo,brief),true);assert.deepEqual((await getClientBrief(f.repo,brief.id))?.comparison,comparison);
 }finally{f.close();}});
 test(`${kind}: a simple recorded contact preserves public report identity and the reviewed PDF; one useful action is accepted`,async()=>{const f=await fixture(kind);try{
  const data=await form(f),input=JSON.parse(String(data.get('payload')));input.actions=input.actions.slice(0,1);data.set('payload',JSON.stringify(input));const brief=await buildClientBrief(f.repo,data,randomUUID());await saveClientBrief(f.repo,brief);const before=(await f.repo.getCompanyReport(f.campaign.id,f.id))!,company=await f.repo.getCompany(f.campaign.id,f.id);
  await f.repo.recordContact(f.campaign.id,f.id,{id:randomUUID(),submittedKey:randomUUID(),channel:'email',outcome:'no_response',date:parisToday(),note:'Note privée sur le suivi, sans correction d’une preuve.',nextAction:null},company.participationRevision);
  const after=(await f.repo.getCompanyReport(f.campaign.id,f.id))!;assert.equal(after.id,before.id);assert.ok(after.facts.some(f=>f.origin==='exchange'&&f.text.includes('Note privée')));assert.equal(await briefNeedsUpdate(f.repo,brief),false);assert.equal(brief.actions.length,1);
 }finally{f.close();}});
}
