import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createClient } from '@libsql/client';
import { Store } from '../lib/db';
import { CampaignRepository } from '../lib/campaign-repository';
import { budgetMonth, saveProviderState, reserveResearchOperation, runBudgetedResearch, getBudgetOverview, recordCreditPurchase, readCompletedOperation, serpApiDailyLimit } from '../lib/research-budget';

function fixture(){const dir=mkdtempSync(join(tmpdir(),'brine-research-budget-')),path=join(dir,'test.sqlite'),store=new Store(path),repo=new CampaignRepository(createClient({url:`file:${path}`}));return {dir,path,store,repo,close(){store.close();repo.close();rmSync(dir,{recursive:true,force:true});}};}
async function configure(repo:CampaignRepository,now=new Date()){await saveProviderState(repo,'openrouter',{checkedAt:now.toISOString(),valid:true,remaining:5,keyLimit:5,keyReset:'monthly'});await saveProviderState(repo,'serpapi',{checkedAt:now.toISOString(),valid:true,remaining:250,hourlyLimit:50});}

test('monthly accounting follows Europe/Paris at the UTC boundary',()=>{assert.equal(budgetMonth(new Date('2026-09-30T22:30:00Z')),'2026-10');});
test('separate workers reserve atomically without exceeding the global provider limit',async()=>{const f=fixture(),other=new CampaignRepository(createClient({url:`file:${f.path}`}));try{await configure(f.repo);const values=await Promise.allSettled([reserveResearchOperation(f.repo,{key:'first',provider:'openrouter',maxUsd:3}),reserveResearchOperation(other,{key:'second',provider:'openrouter',maxUsd:3})]);assert.equal(values.filter(v=>v.status==='fulfilled').length,1);assert.equal((await getBudgetOverview(f.repo)).reservedUsd,3);}finally{other.close();f.close();}});
test('completed operations replay their result without another bill and settle real cost',async()=>{const f=fixture();try{await configure(f.repo);let calls=0;const input={key:'idempotent',provider:'openrouter' as const,maxUsd:.6};const execute=()=>runBudgetedResearch(f.repo,input,async()=>{calls++;return {value:{report:'retained'},actualUsd:.01};});assert.deepEqual(await execute(),{report:'retained'});assert.deepEqual(await execute(),{report:'retained'});assert.equal(calls,1);const overview=await getBudgetOverview(f.repo);assert.equal(overview.spentUsd,.01);assert.equal(overview.reservedUsd,0);}finally{f.close();}});
test('ambiguous timeouts keep the worst-case reservation and never automatically retry',async()=>{const f=fixture();try{await configure(f.repo);let calls=0;const execute=()=>runBudgetedResearch(f.repo,{key:'timeout',provider:'openrouter',maxUsd:.6},async()=>{calls++;throw new Error('network timeout');});await assert.rejects(execute(),/timeout/);await assert.rejects(execute(),/incertain/);assert.equal(calls,1);assert.equal((await getBudgetOverview(f.repo)).reservedUsd,.6);}finally{f.close();}});
test('results without billing metadata remain reusable while their maximum cost stays reserved',async()=>{const f=fixture();try{await configure(f.repo);await runBudgetedResearch(f.repo,{key:'unknown-cost',provider:'openrouter',maxUsd:.3},async()=>({value:{safe:true},actualUsd:null}));assert.deepEqual(await readCompletedOperation(f.repo,'unknown-cost'),{safe:true});assert.equal((await getBudgetOverview(f.repo)).reservedUsd,.3);}finally{f.close();}});
test('provider quota, hourly quota and eight-per-run search limit are enforced before requests',async()=>{const f=fixture();try{await configure(f.repo);for(let i=0;i<8;i++)await runBudgetedResearch(f.repo,{key:`run:lot:search:${i}`,provider:'serpapi',maxUsd:0},async()=>({value:{},actualUsd:0}));await assert.rejects(reserveResearchOperation(f.repo,{key:'run:lot:search:8',provider:'serpapi',maxUsd:0}),/huit/);const rows=await f.repo.client.execute('SELECT COUNT(*) AS n FROM research_operations');assert.equal(rows.rows[0].n,8);await saveProviderState(f.repo,'serpapi',{checkedAt:new Date().toISOString(),valid:true,remaining:0,hourlyLimit:50});await assert.rejects(reserveResearchOperation(f.repo,{key:'empty-provider',provider:'serpapi',maxUsd:0}),/Quota gratuit/);}finally{f.close();}});
test('the daily Google allowance is global across campaigns and uses the actual renewal date',async()=>{const f=fixture();try{const now=new Date('2026-10-04T12:00:00Z'),state={checkedAt:now.toISOString(),valid:true,remaining:30,hourlyLimit:50,renewalDate:'2026-10-14'};assert.equal(serpApiDailyLimit(state,now),3);await saveProviderState(f.repo,'serpapi',state);for(let i=0;i<3;i++)await runBudgetedResearch(f.repo,{key:`run:first:google:${i}`,provider:'serpapi',maxUsd:0},async()=>({value:{},actualUsd:0}),now);await assert.rejects(reserveResearchOperation(f.repo,{key:'run:other:google',provider:'serpapi',maxUsd:0},now),/partagé du jour/);assert.equal((await getBudgetOverview(f.repo,now)).serpApiDailyUsed,3);}finally{f.close();}});
test('external Google account usage is included in the hourly gate and remaining quota display',async()=>{const f=fixture();try{const now=new Date();await saveProviderState(f.repo,'serpapi',{checkedAt:now.toISOString(),valid:true,remaining:200,hourlyLimit:50,observedHourUsed:49});await runBudgetedResearch(f.repo,{key:'last-hourly-search',provider:'serpapi',maxUsd:0},async()=>({value:{},actualUsd:0}),now);await assert.rejects(reserveResearchOperation(f.repo,{key:'too-many-hourly',provider:'serpapi',maxUsd:0},now),/horaire/);const overview=await getBudgetOverview(f.repo,now);assert.equal(overview.serpApiHourUsed,50);assert.equal(overview.serpApiRemaining,199);}finally{f.close();}});
test('a restore preserves pending expenses and completed cached results independently of business records',async()=>{const f=fixture();try{await f.repo.bootstrap();await configure(f.repo);const backup=f.store.exportBackup();await reserveResearchOperation(f.repo,{key:'charged-before-restore',provider:'openrouter',maxUsd:.5});await runBudgetedResearch(f.repo,{key:'cached',provider:'serpapi',maxUsd:0},async()=>({value:{result:'persisted'},actualUsd:0}));f.store.restoreBackup(backup,true);assert.equal((await getBudgetOverview(f.repo)).reservedUsd,.5);assert.deepEqual(await readCompletedOperation(f.repo,'cached'),{result:'persisted'});}finally{f.close();}});
test('credit purchases are separate, idempotent, and cannot exceed ten euros paid in one month',async()=>{const f=fixture();try{const date=new Date().toISOString().slice(0,10);await recordCreditPurchase(f.repo,{id:'receipt-1',date,amountEuro:6.12,notes:'Montant final payé'});await recordCreditPurchase(f.repo,{id:'receipt-1',date,amountEuro:6.12});await assert.rejects(recordCreditPurchase(f.repo,{id:'receipt-2',date,amountEuro:4}),/10 €/);await assert.rejects(recordCreditPurchase(f.repo,{id:'receipt-3',date:'2026-02-30',amountEuro:1}),/date réelle/);assert.equal((await getBudgetOverview(f.repo)).paidEuro,6.12);}finally{f.close();}});
