import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { randomUUID } from 'node:crypto';
import { createClient } from '@libsql/client';
import { Store } from '../lib/db';
import { CampaignRepository } from '../lib/campaign-repository';
import type { Campaign, DiscoveryCandidate } from '../lib/campaign-types';
import { buildOpenRouterRequest, maximumOpenRouterCost, normalizeSearchResults, normalizeAiDiscovery, serpSearch, openRouterJson, getNeutralAiPanel, panelQuestions, boundedProviderJson, checkResearchProvider, discoverMixedProspects, generateContactPreparationWithAI, generateReportNarrative, discoveryBacklogKey } from '../lib/research-providers';
import { getBudgetOverview, getProviderState, runBudgetedResearch, saveProviderState } from '../lib/research-budget';
import { populateRun, processCandidate, processMobile, processReport, finishRun, type DiscoveryProviders } from '../lib/discovery-engine';
import { buildProspectReport } from '../lib/research-report';
import { buildContactDrafts, createApproachPlan, emptyProviderProfile } from '../lib/contact-preparation';
import { visualCaptureFixture } from './fixtures/visual-capture';

const target:Campaign={id:'test',name:'Peintres',targetCity:'Montpellier',targetBusiness:'Peinture',targetOffer:'Site de présentation',activityCodes:'43.34Z',keywords:'peintre',status:'active',revision:1,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};
function fixture(){const dir=mkdtempSync(join(tmpdir(),'brine-research-provider-')),path=join(dir,'test.sqlite'),store=new Store(path),repo=new CampaignRepository(createClient({url:`file:${path}`}));return {store,repo,close(){store.close();repo.close();rmSync(dir,{recursive:true,force:true});}};}
async function fakeKeys(work:()=>Promise<void>){const oldSerp=process.env.SERPAPI_API_KEY,oldRouter=process.env.OPENROUTER_API_KEY;process.env.SERPAPI_API_KEY='test-serp-secret';process.env.OPENROUTER_API_KEY='test-router-secret';try{await work();}finally{if(oldSerp===undefined)delete process.env.SERPAPI_API_KEY;else process.env.SERPAPI_API_KEY=oldSerp;if(oldRouter===undefined)delete process.env.OPENROUTER_API_KEY;else process.env.OPENROUTER_API_KEY=oldRouter;}}
const json=(value:unknown)=>Response.json(value);
const account={plan_monthly_price:0,total_searches_left:250,plan_renewal_date:'2099-01-01',account_rate_limit_per_hour:50,this_hour_searches:0};
const key={data:{limit:5,limit_reset:'monthly',limit_remaining:5,usage_monthly:0}};
test('Maps leads retain sourced public phones and social profiles without fake registry identifiers',()=>{const leads=normalizeSearchResults({local_results:[{title:'Atelier Couleur',address:'1 rue Test Montpellier',phone:'04 00 00 01 23',website:'https://www.instagram.com/ateliercouleur/',place_id:'ChIJ-test'}]},'maps',target,'peintre Montpellier');assert.equal(leads.length,1);assert.equal(leads[0].company.siren,'');assert.equal(leads[0].website,'');assert.equal(leads[0].research.contacts.find(c=>c.kind==='phone')?.value,'04 00 00 01 23');assert.equal(leads[0].research.profiles.length,1);assert.ok(leads[0].research.identityKeys?.includes('maps:ChIJ-test'));assert.ok(!leads[0].research.facts.some(f=>/sans site|aucun site n.existe/.test(f.text)));});
test('organic directories and private URLs are excluded; official-site proposals need confirmation',()=>{const leads=normalizeSearchResults({organic_results:[{title:'PagesJaunes',link:'https://www.pagesjaunes.fr/annuaire/montpellier'},{title:'Internal',link:'http://127.0.0.1/private'},{title:'Atelier Couleur | Peintre Montpellier',link:'https://atelier-couleur.fr',snippet:'Peintre Montpellier'}]},'google',target,'peintre Montpellier');assert.equal(leads.length,1);assert.equal(leads[0].website,'');assert.equal(leads[0].websites[0].confidence,'confirm');});
test('AI proposals must match actual citation annotations and the selected commune',()=>{const source={id:'s',provider:'openrouter' as const,url:'https://atelier.fr/',title:'Atelier Montpellier',excerpt:'Peinture Montpellier',collectedAt:new Date().toISOString()};const leads=normalizeAiDiscovery({model:'model',sources:[source],data:{businesses:[{name:'Atelier',city:'Montpellier',business:'Peinture',url:'https://atelier.fr/',sourceUrl:'https://atelier.fr/'},{name:'Inventé',city:'Montpellier',business:'Peinture',url:'https://fake.fr/',sourceUrl:'https://fake.fr/'},{name:'Ailleurs',city:'Paris',business:'Peinture',url:'https://atelier.fr/',sourceUrl:'https://atelier.fr/'}]}},target);assert.equal(leads.length,1);assert.equal(leads[0].company.siren,'');assert.equal(leads[0].research.facts[0].kind,'hypothesis');});
test('a model cannot replace the commune of a cited business with the selected target',()=>{const source={id:'paris-source',provider:'openrouter' as const,url:'https://atelier.fr/',title:'Atelier Paris',excerpt:'Peinture à Paris',collectedAt:new Date().toISOString()};assert.deepEqual(normalizeAiDiscovery({model:'model',sources:[source],data:{businesses:[{name:'Atelier',city:'Montpellier',business:'Peinture',url:source.url,sourceUrl:source.url}]}},target),[]);});
test('OpenRouter uses only one bounded Exa server tool and pinned token prices',()=>{const request=buildOpenRouterRequest('question',true,3000) as {model:string;max_tool_calls:number;tools:Array<{parameters:Record<string,unknown>}>;provider:{max_price:{prompt:number;completion:number}}};assert.equal(request.model,'google/gemini-3.1-flash-lite');assert.equal(request.max_tool_calls,1);assert.deepEqual(request.tools[0].parameters,{engine:'exa',mode:'auto',max_uses:1,max_results:5,max_total_results:5,max_characters:2000});assert.deepEqual(request.provider.max_price,{prompt:.25,completion:1.5});assert.ok(maximumOpenRouterCost(true)>maximumOpenRouterCost(false));assert.throws(()=>buildOpenRouterRequest('x'.repeat(24001),false),/volumineux/);});
test('Google cache avoids repeat quota usage and never stores the API key',async()=>fakeKeys(async()=>{const f=fixture();try{let searches=0;const fetcher=(async(url:unknown)=>String(url).includes('account.json')?json(account):(searches++,json({search_metadata:{status:'Success'},search_parameters:{api_key:'test-serp-secret'},organic_results:[{title:'Atelier',link:'https://atelier.fr/'}],serpapi_pagination:{next:'https://serpapi.com/search?api_key=test-serp-secret'}}))) as typeof fetch;const params={engine:'google',q:'peintre Montpellier'};await serpSearch(f.repo,params,'query-one',fetcher);await serpSearch(f.repo,params,'query-two',fetcher);assert.equal(searches,1);const rows=await f.repo.client.execute('SELECT payload FROM research_operations');assert.ok(!String(rows.rows[0].payload).includes('test-serp-secret'));assert.equal((await getBudgetOverview(f.repo)).serpApiUsed,1);}finally{f.close();}}));
test('a paid SerpApi plan or unlimited OpenRouter key is refused before search requests',async()=>fakeKeys(async()=>{const f=fixture();try{let calls=0;const fetcher=(async()=>{calls++;return json({...account,plan_monthly_price:25});}) as typeof fetch;await assert.rejects(checkResearchProvider(f.repo,'serpapi',fetcher),/plan.*gratuit/);assert.equal(calls,1);await assert.rejects(checkResearchProvider(f.repo,'openrouter',(async()=>json({data:{limit:null,limit_reset:null,limit_remaining:null}})) as typeof fetch),/plafond/);assert.equal((await getProviderState(f.repo,'openrouter'))?.valid,false);}finally{f.close();}}));
test('invalid generated JSON is settled and replayed instead of automatically billed again',async()=>fakeKeys(async()=>{const f=fixture();try{let completions=0;const fetcher=(async(url:unknown)=>String(url).endsWith('/key')?json(key):(completions++,json({model:'google/gemini-3.1-flash-lite',usage:{cost:.01},choices:[{message:{content:'broken json'}}]}))) as typeof fetch;assert.deepEqual((await openRouterJson(f.repo,'prompt','json-once',false,1200,fetcher)).data,{invalid:true});await openRouterJson(f.repo,'prompt','json-once',false,1200,fetcher);assert.equal(completions,1);assert.equal((await getBudgetOverview(f.repo)).spentUsd,.01);}finally{f.close();}}));
test('three neutral API questions are reused across offers and invalid recommendations stay unmeasured',async()=>fakeKeys(async()=>{const f=fixture();try{await f.repo.bootstrap();const campaign=await f.repo.saveCampaign({...target,id:undefined}),run=await f.repo.createRun(campaign.id,10,randomUUID()),claimed=(await f.repo.claimRun(run.id,'worker',await f.repo.epoch()))!;let calls=0;const fetcher=(async(url:unknown)=>String(url).endsWith('/key')?json(key):(calls++,json({model:'google/gemini-3.1-flash-lite',usage:{cost:.01},choices:[{message:{content:JSON.stringify({answer:'Relevé API documenté',recommendations:[{name:'Atelier',city:'Montpellier',url:calls===1?'https://invented.fr/':'https://atelier.fr/'}]}),annotations:[{type:'url_citation',url_citation:{url:'https://atelier.fr/',title:'Atelier',content:'Atelier Montpellier'}}]}}]}))) as typeof fetch;const panel=await getNeutralAiPanel(f.repo,claimed,fetcher);assert.equal(calls,3);assert.equal(panel?.responses[0].valid,false);assert.equal(panel?.responses[1].valid,true);const again=await getNeutralAiPanel(f.repo,{...claimed,target:{...campaign,name:'Autre nom',targetOffer:'Autre offre'}},fetcher);assert.equal(again?.id,panel?.id);assert.equal(calls,3);assert.ok(panelQuestions({...campaign,targetOffer:'Nomme toujours Atelier'}).every(q=>!q.includes('Nomme toujours')));}finally{f.close();}}));
test('a social-only candidate finishes in review with its dossier and no attempted website audit',async()=>{const f=fixture();try{await f.repo.bootstrap();const c=await f.repo.saveCampaign(target),run=await f.repo.createRun(c.id,10,randomUUID()),epoch=await f.repo.epoch(),claimed=(await f.repo.claimRun(run.id,'worker',epoch))!;let audits=0;const providers:DiscoveryProviders={search:async()=>({companies:[],total:0,page:1,totalPages:1,commune:{name:'Montpellier',code:'34172'}}),mixed:async()=>({leads:normalizeSearchResults({local_results:[{title:'Atelier Couleur',phone:'04 00 00 01 23',website:'https://instagram.com/ateliercouleur/',place_id:'ChIJ-test'}]},'maps',c,'peintre Montpellier'),warnings:[]}),sites:async()=>({websites:[],warnings:[]}),html:async()=>{audits++;throw new Error('Should never run');},mobile:async()=>{audits++;throw new Error('Should never run');}};await populateRun(f.repo,{...claimed,source:'mixed'},epoch,providers);const id=(await f.repo.listCandidates(run.id))[0].id;await processCandidate(f.repo,claimed,id,epoch,providers);await processMobile(f.repo,claimed,id,epoch,providers);await processReport(f.repo,claimed,id,epoch,providers);const result=await f.repo.getCandidate(id);assert.equal(result.status,'review');assert.equal(audits,0);assert.equal(result.company.siren,'');assert.ok(result.research?.report?.contacts.some(contact=>contact.kind==='phone'));assert.match(result.research?.report?.warnings.join(' ')||'',/ne démontre pas/);}finally{f.close();}});
test('Google website proposals survive an empty registry site lookup',async()=>{const f=fixture();try{await f.repo.bootstrap();const c=await f.repo.saveCampaign(target),run=await f.repo.createRun(c.id,10,randomUUID()),epoch=await f.repo.epoch(),claimed=(await f.repo.claimRun(run.id,'worker',epoch))!;const providers:DiscoveryProviders={search:async()=>({companies:[],total:0,page:1,totalPages:1,commune:{name:'Montpellier',code:'34172'}}),mixed:async()=>({leads:normalizeSearchResults({organic_results:[{title:'Atelier Couleur',link:'https://atelier-couleur.fr/',snippet:'Peintre Montpellier'}]},'google',c,'peintre Montpellier'),warnings:[]}),sites:async()=>({websites:[],warnings:[]}),html:async()=>{throw new Error('Site is not confirmed');},mobile:async()=>{throw new Error('Site is not confirmed');}};await populateRun(f.repo,{...claimed,source:'mixed'},epoch,providers);const id=(await f.repo.listCandidates(run.id))[0].id;await processCandidate(f.repo,claimed,id,epoch,providers);const result=await f.repo.getCandidate(id);assert.equal(result.website,'');assert.equal(result.websites[0].url,'https://atelier-couleur.fr/');assert.equal(result.websites[0].confidence,'confirm');assert.equal(result.status,'review');}finally{f.close();}});
test('a pause after paid enrichment reuses its committed result on resume',async()=>{const f=fixture();try{await f.repo.bootstrap();await saveProviderState(f.repo,'openrouter',{checkedAt:new Date().toISOString(),valid:true,remaining:5});const campaign=await f.repo.saveCampaign(target),run=await f.repo.createRun(campaign.id,10,randomUUID()),epoch=await f.repo.epoch(),first=(await f.repo.claimRun(run.id,'first',epoch))!;let enrichCalls=0,paidCalls=0;const research=normalizeSearchResults({local_results:[{title:'Atelier Couleur',phone:'04 00 00 01 23',website:'https://instagram.com/ateliercouleur/',place_id:'ChIJ-test'}]},'maps',campaign,'peintre Montpellier')[0].research;const providers:DiscoveryProviders={search:async()=>({companies:[{siren:'490484557',siret:'49048455700023',name:'Atelier Couleur',city:'Montpellier',business:'Peinture',activityCode:'43.34Z',address:'',sourceUrl:'https://annuaire-entreprises.data.gouv.fr/entreprise/490484557'}],total:1,page:1,totalPages:1,commune:{name:'Montpellier',code:'34172'}}),enrich:async(repo,r,c)=>{enrichCalls++;const result=await runBudgetedResearch(repo,{key:`candidate:${c.id}:paid-enrich`,provider:'openrouter',maxUsd:.5},async()=>{paidCalls++;return {value:research,actualUsd:.01};});if(enrichCalls===1)await repo.controlRun(r.id,'pause');return result;},sites:async()=>({websites:[],warnings:[]}),html:async()=>{throw new Error('No website');},mobile:async()=>{throw new Error('No website');}};await populateRun(f.repo,{...first,source:'registry'},epoch,providers);const id=(await f.repo.listCandidates(run.id))[0].id;await processCandidate(f.repo,first,id,epoch,providers);assert.equal((await f.repo.getCandidate(id)).attempts.enrichCompleted,undefined);await f.repo.controlRun(run.id,'resume');const second=(await f.repo.claimRun(run.id,'second',epoch))!;await processCandidate(f.repo,second,id,epoch,providers);assert.equal(enrichCalls,2);assert.equal(paidCalls,1);assert.equal((await f.repo.getCandidate(id)).attempts.enrichCompleted,1);assert.equal((await f.repo.getCandidate(id)).research?.profiles.length,1);}finally{f.close();}});
test('oversized and malformed provider responses fail with a safe error',async()=>{await assert.rejects(boundedProviderJson('https://example.com',{},(async()=>new Response('x'.repeat(1024*1024+1))) as typeof fetch),/volumineuse/);await assert.rejects(boundedProviderJson('https://example.com',{},(async()=>new Response('no json')) as typeof fetch),/invalide/);});

test('a new lot continues both Google and Maps pagination while a resumed lot reuses its fixed pages',async()=>fakeKeys(async()=>{
  delete process.env.OPENROUTER_API_KEY;
  const f=fixture();try{
    await f.repo.bootstrap();const campaign=await f.repo.saveCampaign(target),epoch=await f.repo.epoch();
    const calls:Array<{engine:string;start:string}>=[];
    const fetcher=(async(url:unknown)=>{
      const request=new URL(String(url));if(request.pathname==='/account.json')return json({...account,plan_renewal_date:new Date(Date.now()+30*86400000).toISOString().slice(0,10)});
      const engine=request.searchParams.get('engine')!,start=request.searchParams.get('start')!;calls.push({engine,start});
      return json(engine==='google_maps'?{local_results:[{title:`Atelier Maps ${start}`,place_id:`maps-${start}`,phone:'04 00 00 01 23'}]}:{organic_results:[{title:`Atelier Google ${start}`,link:`https://atelier-${start}.example/`}]});
    }) as typeof fetch;
    const providers:DiscoveryProviders={search:async()=>({companies:[],total:0,page:1,totalPages:1,commune:{name:'Montpellier',code:'34172'}}),mixed:(repo,run)=>discoverMixedProspects(repo,run,fetcher),sites:async()=>({websites:[],warnings:[]}),html:async()=>{throw new Error('No audit needed');},mobile:async()=>{throw new Error('No audit needed');}};
    const first=await f.repo.createRun(campaign.id,10,randomUUID()),claimed=(await f.repo.claimRun(first.id,'first',epoch))!;
    await populateRun(f.repo,claimed,epoch,providers);assert.equal((await f.repo.listCandidates(first.id)).length,4);
    await discoverMixedProspects(f.repo,claimed,fetcher);assert.equal(calls.length,4,'same run reuses the fixed page plan and cached responses');
    await finishRun(f.repo,claimed,epoch);
    const second=await f.repo.createRun(campaign.id,10,randomUUID()),next=(await f.repo.claimRun(second.id,'second',epoch))!;
    await populateRun(f.repo,next,epoch,providers);
    assert.deepEqual(calls,[{engine:'google_maps',start:'0'},{engine:'google_maps',start:'20'},{engine:'google',start:'0'},{engine:'google',start:'10'},{engine:'google_maps',start:'40'},{engine:'google_maps',start:'60'},{engine:'google',start:'20'},{engine:'google',start:'30'}]);
    assert.equal((await f.repo.listCandidates(second.id)).length,4);assert.equal((await getBudgetOverview(f.repo)).serpApiUsed,8);
  }finally{f.close();}
}));

test('surplus sourced prospects are admitted from the shared cache before another provider request',async()=>fakeKeys(async()=>{
  delete process.env.OPENROUTER_API_KEY;
  const f=fixture();try{
    await f.repo.bootstrap();const campaign=await f.repo.saveCampaign(target),epoch=await f.repo.epoch();let searches=0;
    const fetcher=(async(url:unknown)=>String(url).includes('account.json')?json({...account,plan_renewal_date:new Date(Date.now()+30*86400000).toISOString().slice(0,10)}):(searches++,json(String(url).includes('engine=google_maps')?{local_results:Array.from({length:20},(_,index)=>({title:`Atelier ${index}`,place_id:`place-${index}`,phone:'04 00 00 01 23'}))}:{organic_results:[]}))) as typeof fetch;
    const providers:DiscoveryProviders={search:async()=>({companies:[],total:0,page:1,totalPages:1,commune:{name:'Montpellier',code:'34172'}}),mixed:(repo,run)=>discoverMixedProspects(repo,run,fetcher),sites:async()=>({websites:[],warnings:[]}),html:async()=>{throw new Error('No audit needed');},mobile:async()=>{throw new Error('No audit needed');}};
    const first=await f.repo.createRun(campaign.id,10,randomUUID()),claimed=(await f.repo.claimRun(first.id,'first',epoch))!;
    await populateRun(f.repo,claimed,epoch,providers);await finishRun(f.repo,claimed,epoch);assert.equal(searches,4);
    const second=await f.repo.createRun(campaign.id,10,randomUUID()),next=(await f.repo.claimRun(second.id,'second',epoch))!;await populateRun(f.repo,next,epoch,providers);
    assert.equal(searches,4);const firstIds=new Set((await f.repo.listCandidates(first.id)).map(candidate=>candidate.dedupeKey)),secondCandidates=await f.repo.listCandidates(second.id);assert.equal(secondCandidates.length,10);assert.ok(secondCandidates.every(candidate=>!firstIds.has(candidate.dedupeKey)));
    const stored=await f.repo.client.execute({sql:'SELECT payload FROM research_cache WHERE cacheKey = ?',args:[discoveryBacklogKey(next)]});assert.deepEqual(JSON.parse(String(stored.rows[0].payload)),[]);
  }finally{f.close();}
}));

test('pausing an API panel preserves billed answers without poisoning the shared target cache',async()=>fakeKeys(async()=>{
  const f=fixture();try{
    await f.repo.bootstrap();const campaign=await f.repo.saveCampaign(target),run=await f.repo.createRun(campaign.id,10,randomUUID()),epoch=await f.repo.epoch(),claimed=(await f.repo.claimRun(run.id,'first',epoch))!;let calls=0;
    const fetcher=(async(url:unknown)=>{if(String(url).endsWith('/key'))return json(key);calls++;if(calls===1)await f.repo.controlRun(run.id,'pause');return json({usage:{cost:.01},choices:[{message:{content:JSON.stringify({answer:'Atelier est un professionnel local documenté.',recommendations:[{name:'Atelier',city:'Montpellier',url:'https://atelier.fr/'}]}),annotations:[{type:'url_citation',url_citation:{url:'https://atelier.fr/',title:'Atelier',content:'Atelier Montpellier'}}]}}]});}) as typeof fetch;
    await assert.rejects(getNeutralAiPanel(f.repo,claimed,fetcher),/suspendu/);assert.equal(calls,1);assert.equal((await f.repo.client.execute("SELECT COUNT(*) AS n FROM research_cache WHERE cacheKey LIKE 'panel:%'")).rows[0].n,0);
    await f.repo.controlRun(run.id,'resume');const resumed=(await f.repo.claimRun(run.id,'second',epoch))!;const panel=await getNeutralAiPanel(f.repo,resumed,fetcher);assert.equal(calls,3);assert.equal(panel?.responses.filter(response=>response.valid).length,3);assert.equal((await getBudgetOverview(f.repo)).spentUsd,.03);
  }finally{f.close();}
}));

test('a paused lot cannot start a paid report synthesis',async()=>fakeKeys(async()=>{
  const f=fixture(),originalFetch=globalThis.fetch;try{
    await f.repo.bootstrap();const campaign=await f.repo.saveCampaign(target),run=await f.repo.createRun(campaign.id,10,randomUUID()),claimed=(await f.repo.claimRun(run.id,'worker',await f.repo.epoch()))!;
    const lead=normalizeSearchResults({local_results:[{title:'Atelier',place_id:'ChIJ-test',phone:'04 00 00 01 23'}]},'maps',campaign,'peintre Montpellier')[0],candidate:DiscoveryCandidate={id:'paused-candidate',runId:run.id,companyId:null,company:lead.company,status:'review',website:'',websites:[],html:null,mobile:null,htmlError:'',mobileError:'',attempts:{},revision:1,research:lead.research};
    await f.repo.controlRun(run.id,'pause');let calls=0;globalThis.fetch=(async()=>{calls++;throw new Error('No request should be started');}) as typeof fetch;
    assert.equal(await generateReportNarrative(f.repo,claimed,candidate,buildProspectReport(candidate,campaign)),'');assert.equal(calls,0);
  }finally{globalThis.fetch=originalFetch;f.close();}
}));

test('AI prepares a grounded plan and short opening while preserving the complete call guide',async()=>fakeKeys(async()=>{
  const f=fixture(),originalFetch=globalThis.fetch;try{
    const candidate:DiscoveryCandidate={id:'contact-candidate',runId:'contact-run',companyId:null,company:{name:'Atelier',city:'Montpellier',business:'Peinture',siren:'',siret:'',activityCode:'',address:'',sourceUrl:'https://atelier.example/'},status:'review',website:'https://atelier.example/',websites:[],html:{website:'https://atelier.example/',analyzedOn:'2026-10-04',pages:[{url:'https://atelier.example/',title:'Atelier'}],contacts:[],warnings:[],findings:[{id:'broken',key:'technical',note:'Le lien « Demander un devis » répond HTTP 404.',sourceUrl:'https://atelier.example/devis',approach:'Vérifier cet accès.'}]},mobile:null,htmlError:'',mobileError:'',attempts:{},revision:1};
    const report=buildProspectReport(candidate,target),profile={...emptyProviderProfile(),name:'Rayan',activity:'développeur indépendant',services:'Sites web',revision:1};
    report.facts.find(fact=>fact.id==='broken')!.visual={category:'interaction',device:'desktop',element:'Lien Demander un devis',pageUrl:candidate.website,screenshot:visualCaptureFixture};
    const plan=createApproachPlan(report,target,profile,['broken']),drafts=buildContactDrafts(plan,report,profile);let completions=0;
    globalThis.fetch=(async(url:unknown,options?:RequestInit)=>{
      if(String(url).endsWith('/key'))return json(key);completions++;
      const request=JSON.parse(String(options?.body)),context=JSON.parse(request.messages[1].content.split('Données fiables : ')[1]),current=context.plan;
      assert.ok(!String(options?.body).includes('data:image/jpeg;base64,'),'Private captures are never sent as text to the drafting provider.');
      const text=`Bonjour, je suis ${context.profile.name}, ${context.profile.activity}. ${current.motive} ${current.question}`;
      return json({usage:{cost:.001},choices:[{message:{content:JSON.stringify({plan:{evidenceIds:current.evidenceIds,motive:current.motive,rationale:current.rationale,hypothesis:current.hypothesis,help:current.help,question:current.question,nextStep:current.nextStep,offer:current.offer},email:{subject:'Votre parcours de contact',text},call:{text}})}}]});
    }) as typeof fetch;
    const result=await generateContactPreparationWithAI(f.repo,plan,report,profile,drafts,'contact-operation');assert.equal(result.drafts[0].origin,'openrouter');assert.equal(result.plan.motive,report.facts.find(fact=>fact.id==='broken')?.text);const call=result.drafts.find(draft=>draft.channel==='call')!;assert.equal(call.blocks[0].label,'Ouverture courte');assert.ok(call.blocks.some(block=>block.label==='Refus'));assert.ok(call.blocks.some(block=>block.label==='Prochaine étape'));assert.ok(call.blocks.length>10);
    await generateContactPreparationWithAI(f.repo,{...plan,createdAt:new Date(Date.now()+1000).toISOString()},report,profile,drafts,'contact-operation');assert.equal(completions,1,'a submission retry ignores incidental creation timestamps');
    const changedProfile={...profile,name:'Camille',activity:'designer indépendant',revision:2},changedPlan=createApproachPlan(report,target,changedProfile,['broken']),changedDrafts=buildContactDrafts(changedPlan,report,changedProfile);
    const changed=await generateContactPreparationWithAI(f.repo,changedPlan,report,changedProfile,changedDrafts,'contact-operation');assert.equal(completions,2);assert.equal(changed.drafts[0].origin,'openrouter');assert.match(changed.drafts[0].text,/Camille, designer indépendant/);assert.ok(!changed.drafts[0].text.includes('Rayan'));
    const changedReport=buildProspectReport({...candidate,html:{...candidate.html!,findings:[{...candidate.html!.findings[0],note:'Le lien « Obtenir un devis » répond HTTP 404.'}]}},target),reportPlan=createApproachPlan(changedReport,target,changedProfile,['broken']);
    const revised=await generateContactPreparationWithAI(f.repo,reportPlan,changedReport,changedProfile,buildContactDrafts(reportPlan,changedReport,changedProfile),'contact-operation');assert.equal(completions,3);assert.equal(revised.drafts[0].reportId,changedReport.id);assert.match(revised.drafts[0].text,/Obtenir un devis/);assert.ok(!revised.drafts[0].text.includes('Demander un devis'));
    const editedPlan={...reportPlan,question:'Comment préférez-vous recevoir les demandes de devis ?'};
    const edited=await generateContactPreparationWithAI(f.repo,editedPlan,changedReport,changedProfile,buildContactDrafts(editedPlan,changedReport,changedProfile),'contact-operation');assert.equal(completions,4);assert.match(edited.drafts[0].text,/Comment préférez-vous/);
  }finally{globalThis.fetch=originalFetch;f.close();}
}));

test('the mixed discovery deadline includes registry time and keeps acquired results before stopping requests',async()=>fakeKeys(async()=>{
  const f=fixture(),originalNow=Date.now,initial=originalNow();let elapsed=0;
  Date.now=()=>initial+elapsed;
  try{
    await f.repo.bootstrap();const campaign=await f.repo.saveCampaign(target),run=await f.repo.createRun(campaign.id,10,randomUUID()),epoch=await f.repo.epoch(),claimed=(await f.repo.claimRun(run.id,'worker',epoch))!;let registryCalls=0,searches=0,accountChecks=0,routerCalls=0;
    const fetcher=(async(url:unknown)=>{
      if(String(url).includes('account.json')){accountChecks++;elapsed+=40_000;return json({...account,plan_renewal_date:new Date(initial+30*86400000).toISOString().slice(0,10)});}
      if(String(url).includes('serpapi.com/search.json')){searches++;elapsed+=40_000;return json({local_results:[{title:'Atelier acquis',place_id:'place-acquired',phone:'04 00 00 01 23'}]});}
      routerCalls++;throw new Error('There is no time left to start an account check and paid request');
    }) as typeof fetch;
    const providers:DiscoveryProviders={search:async()=>{registryCalls++;elapsed+=18_000;return {companies:[],total:100,page:registryCalls,totalPages:5,commune:{name:'Montpellier',code:'34172'}};},mixed:(repo,current,deadline)=>discoverMixedProspects(repo,current,fetcher,deadline),sites:async()=>({websites:[],warnings:[]}),html:async()=>{throw new Error('No audit needed');},mobile:async()=>{throw new Error('No audit needed');}};
    await populateRun(f.repo,claimed,epoch,providers);const candidates=await f.repo.listCandidates(run.id);
    assert.equal(registryCalls,5);assert.equal(accountChecks,1);assert.equal(searches,1);assert.equal(routerCalls,0);assert.equal(elapsed,170_000);assert.equal(candidates.length,1);assert.equal(candidates[0].company.name,'Atelier acquis');assert.match(candidates[0].research?.warnings.join(' ')||'',/durée de collecte.*résultats acquis.*reportée/);
    await finishRun(f.repo,claimed,epoch);const complete=await f.repo.getRun(run.id);assert.equal(complete.status,'completed');assert.match(complete.error,/Collecte partielle.*durée de collecte/);
  }finally{Date.now=originalNow;f.close();}
}));

test('registry collection itself stops before starting a page without enough remaining time',async()=>{
  const f=fixture(),originalNow=Date.now,initial=originalNow();let elapsed=0;Date.now=()=>initial+elapsed;
  try{
    await f.repo.bootstrap();const campaign=await f.repo.saveCampaign(target),run=await f.repo.createRun(campaign.id,10,randomUUID()),epoch=await f.repo.epoch(),claimed=(await f.repo.claimRun(run.id,'worker',epoch))!;let calls=0;
    const providers:DiscoveryProviders={search:async()=>{calls++;elapsed+=55_000;return {companies:[{siren:`49048455${calls}`,siret:`49048455${calls}00023`,name:`Atelier ${calls}`,city:'Montpellier',business:'Peinture',activityCode:'43.34Z',address:'',sourceUrl:`https://annuaire-entreprises.data.gouv.fr/entreprise/49048455${calls}`}],total:100,page:calls,totalPages:5,commune:{name:'Montpellier',code:'34172'}};},sites:async()=>({websites:[],warnings:[]}),html:async()=>{throw new Error('No audit needed');},mobile:async()=>{throw new Error('No audit needed');}};
    await populateRun(f.repo,{...claimed,source:'registry'},epoch,providers);const candidates=await f.repo.listCandidates(run.id);assert.equal(calls,3);assert.equal(elapsed,165_000);assert.equal(candidates.length,3);assert.ok(candidates.every(candidate=>candidate.research?.warnings.some(warning=>warning.includes('collecte du registre est arrêtée'))));
  }finally{Date.now=originalNow;f.close();}
});
