import test from 'node:test';
import { createHash } from 'node:crypto';
import { getResearchAsset } from '../lib/research-assets';
import { visualCaptureFixture } from './fixtures/visual-capture';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createClient } from '@libsql/client';
import { Store } from '../lib/db';
import { AsyncCloudStore } from '../lib/cloud-db';
import { CampaignRepository } from '../lib/campaign-repository';
import { backupSchema, parisToday } from '../lib/domain';
import { buildContactDrafts, createApproachPlan, emptyProviderProfile } from '../lib/contact-preparation';
import { researchFactSchema } from '../lib/research-schemas';
import { isPublicVisualUrl, isValidVisualScreenshot, MAX_VISUAL_SCREENSHOT_BYTES, parseVisualObservation, type VisualObservationInput } from '../lib/visual-evidence';
import type { CampaignCompany, DiscoveryCandidate } from '../lib/campaign-types';

// A real 1 × 1 JPEG generated by a browser canvas, without any external image source.
const screenshot = visualCaptureFixture;
const assetId=createHash('sha256').update(Buffer.from(screenshot.split(',')[1],'base64')).digest('hex');
const input = (): VisualObservationInput => ({category:'overlap',device:'desktop',pageUrl:'https://atelier.example/realisations',element:'Comparaison avant / après',observation:'Trois formes sombres recouvrent une partie des photos de réalisations.',observedOn:parisToday(),viewport:{width:1440,height:900},screenshot});

test('visual proof accepts a real bounded JPEG and rejects fake MIME, signatures, invalid base64 and oversized bytes',()=>{
  assert.equal(isValidVisualScreenshot(screenshot),true);
  for(const value of ['data:image/svg+xml;base64,PHN2Zz4=',screenshot.replace('image/jpeg','image/png'),'data:image/jpeg;base64,iVBORw0KGgo=','data:image/jpeg;base64,/9j/2Q==',screenshot+'!'])assert.equal(isValidVisualScreenshot(value),false);
  const bytes=Buffer.from(screenshot.split(',')[1],'base64');
  const oversized=Buffer.concat([bytes.subarray(0,-2),Buffer.alloc(MAX_VISUAL_SCREENSHOT_BYTES),bytes.subarray(-2)]);
  assert.equal(isValidVisualScreenshot(`data:image/jpeg;base64,${oversized.toString('base64')}`),false);
});

test('visual observations require a public page, real past date, precise element and complete viewport',()=>{
  for(const url of ['https://login:secret@atelier.example/','file:///tmp/page','https://localhost/','http://127.0.0.1/','http://2130706433/','http://192.168.1.1/','http://[::1]/','https://printer.local/','https://atelier.example\\@localhost/'])assert.equal(isPublicVisualUrl(url),false,url);
  const now=new Date('2026-10-04T12:00:00Z');
  assert.equal(parseVisualObservation({...input(),observedOn:'2026-10-04T11:59:59Z'},now).pageUrl,input().pageUrl);
  for(const value of [{observedOn:'2099-01-01'},{observedOn:'2026-10-04T12:00:01Z'},{observedOn:'2026-02-30'},{observedOn:''},{element:''},{viewport:{width:390}},{pageUrl:'https://user:pass@atelier.example/'},{screenshot:'data:image/jpeg;base64,PHN2Zz4='}])assert.throws(()=>parseVisualObservation({...input(),observedOn:'2026-10-04',...value},now));
});

test('report schema preserves visual evidence only as a sourced dated direct site observation',()=>{
  const {observation:text,observedOn,...visual}=input(),fact={id:'visual',section:'site',kind:'observed',sentiment:'issue',text,sourceIds:['source'],observedOn,scope:'Sur cet écran uniquement.',visual};
  const parsed=researchFactSchema.parse(fact);assert.deepEqual(parsed.visual,visual);
  for(const changed of [{kind:'reported'},{section:'presentation'},{observedOn:''},{visual:{...visual,screenshot:'https://atelier.example/image.jpg'}}])assert.equal(researchFactSchema.safeParse({...fact,...changed}).success,false);
});

const target={name:'Artisans Lyon',targetCity:'Lyon',targetBusiness:'Rénovation',targetCompanyType:'Indépendants',targetOffer:'Développement et amélioration de sites web',targetExclusions:'',activityCodes:'',keywords:'rénovation'};
async function fixture(kind:'local'|'cloud'){
  const dir=mkdtempSync(join(tmpdir(),'brine-visual-')),path=join(dir,'data.sqlite');
  const base=kind==='local'?new Store(path):new AsyncCloudStore(createClient({url:`file:${path}`}));await base.listCompanies();
  const repo=new CampaignRepository(createClient({url:`file:${path}`}));await repo.bootstrap();
  const campaign=await repo.saveCampaign(target),run=await repo.createRun(campaign.id,10,randomUUID());
  const candidate:DiscoveryCandidate={id:randomUUID(),runId:run.id,companyId:null,company:{name:'Atelier Exemple',siren:'',siret:'',city:'Lyon',business:'Rénovation',activityCode:'',address:'',sourceUrl:'https://atelier.example/'},status:'review',websites:[],website:'https://atelier.example/',html:null,mobile:null,htmlError:'',mobileError:'',attempts:{},revision:1,research:{sources:[{id:'source',provider:'website',url:'https://atelier.example/',title:'Atelier Exemple',excerpt:'Les prestations de rénovation et un accès renvoyant HTTP 404.',collectedAt:parisToday()}],facts:Array.from({length:12},(_,n)=>({id:`fact-${n}`,section:'site',kind:'observed',sentiment:'issue',text:`Accès ${n} : la page renvoie HTTP 404.`,sourceIds:['source'],observedOn:parisToday(),scope:'Une réponse ponctuelle.'})),contacts:[{kind:'email',value:'contact@atelier.example',sourceUrl:'https://atelier.example/',sourceId:'source'}],profiles:['https://www.instagram.com/atelierexemple/'],warnings:['Limite déjà documentée.'],narrative:'Atelier Exemple présente des prestations de rénovation.',collectionStatus:'Collecte HTML conservée.',identityKeys:['example-id']}};
  await repo.transaction(tx=>repo.putCandidate(tx,candidate));
  return {base,repo,campaign,run,candidate,close(){repo.close();base.close();rmSync(dir,{recursive:true,force:true});}};
}

for(const kind of ['local','cloud'] as const){
  test(`${kind}: visual save preserves every fact, channel, narrative and profile and repeated submission writes once`,async()=>{
    const f=await fixture(kind);try{
      const before=structuredClone(f.candidate.research!);
      const [saved,repeated]=await Promise.all([f.repo.addVisualObservation(f.candidate.id,1,input()),f.repo.addVisualObservation(f.candidate.id,1,input())]);
      assert.deepEqual(repeated,saved);
      assert.equal(saved.revision,2);assert.equal(saved.research?.facts.length,13);
      assert.deepEqual(saved.research?.facts.slice(0,12),before.facts);
      for(const key of ['contacts','profiles','warnings','narrative','collectionStatus','identityKeys'] as const)assert.deepEqual(saved.research?.[key],before[key]);
      const visualFact=saved.research!.facts[12],source=saved.research!.sources.find(source=>source.id===visualFact.sourceIds[0])!;
      assert.deepEqual(Buffer.from((await getResearchAsset(f.repo,assetId))!),Buffer.from(screenshot.split(',')[1],'base64'));assert.equal(visualFact.visual?.screenshot,undefined);assert.equal(visualFact.kind,'observed');assert.equal(visualFact.visual?.assetId,assetId);assert.equal(source.provider,'manual');assert.equal(source.url,input().pageUrl);assert.equal(source.collectedAt,input().observedOn);
      assert.match(visualFact.scope,/humaine/);assert.match(visualFact.scope,/aucune perte/);assert.equal(saved.research?.report?.facts.filter(fact=>fact.id.startsWith('fact-')).length,12);assert.equal(saved.research?.report?.facts.find(fact=>fact.id===visualFact.id)?.visual?.assetId,assetId);
      assert.equal(saved.research?.report?.narrative,before.narrative);
      assert.deepEqual(await f.repo.addVisualObservation(f.candidate.id,1,input()),saved);
      await assert.rejects(f.repo.addVisualObservation(f.candidate.id,1,{...input(),observation:'Une autre erreur visible.'}),/changé/);
      assert.deepEqual(await f.repo.getCandidate(f.candidate.id),saved);
      const backup=await f.base.exportBackup();assert.equal(backup.schemaVersion,7);assert.equal(backupSchema.safeParse(backup).success,true);
      await f.base.restoreBackup(backup,true);
      assert.deepEqual((await f.repo.getCandidate(f.candidate.id)).research?.facts,saved.research?.facts);
      assert.equal((await f.repo.getCandidate(f.candidate.id)).research?.report?.facts.find(fact=>fact.id===visualFact.id)?.visual?.assetId,assetId);
      assert.equal((await f.repo.client.execute('SELECT * FROM research_operations')).rows.length,0);
    }finally{f.close();}
  });
  test(`${kind}: processing protection, concurrent conflicting revisions and invalid inputs leave no partial proof`,async()=>{
    const f=await fixture(kind);try{
      for(const status of ['queued','processing'] as const){
        await f.repo.transaction(tx=>f.repo.putCandidate(tx,{...f.candidate,status}));
        await assert.rejects(f.repo.addVisualObservation(f.candidate.id,1,input()),/cours/);
        assert.equal((await f.repo.getCandidate(f.candidate.id)).research?.facts.length,12);
      }
      await f.repo.transaction(tx=>f.repo.putCandidate(tx,f.candidate));
      const before=await f.repo.getCandidate(f.candidate.id);
      await assert.rejects(f.repo.addVisualObservation(f.candidate.id,1,{...input(),observedOn:'2099-01-01'}),/passé/);
      await assert.rejects(f.repo.addVisualObservation(f.candidate.id,1,{...input(),screenshot:'data:image/jpeg;base64,PHN2Zz4='}),/JPEG/);
      assert.deepEqual(await f.repo.getCandidate(f.candidate.id),before);
      const results=await Promise.allSettled([f.repo.addVisualObservation(f.candidate.id,1,input()),f.repo.addVisualObservation(f.candidate.id,1,{...input(),observation:'Un texte est coupé.'})]);
      assert.equal(results.filter(result=>result.status==='fulfilled').length,1);assert.equal((await f.repo.getCandidate(f.candidate.id)).research?.facts.length,13);
    }finally{f.close();}
  });
  test(`${kind}: shared visual fact invalidates plans in every campaign while preserving draft versions and selected facts`,async()=>{
    const f=await fixture(kind);try{
      const id=(await f.repo.reviewCandidate(f.candidate.id,1,'accept',['fact-0'],[0],''))!,campaign2=await f.repo.saveCampaign({...target,name:'Autre campagne'});
      await f.repo.attach(campaign2.id,id);
      const profile=await f.repo.saveProviderProfile({...emptyProviderProfile(),name:'Alex',activity:'développeur indépendant',services:'Amélioration de sites web'},0);
      const snapshots:CampaignCompany[]=[];
      for(const campaign of [f.campaign,campaign2]){
        const report=(await f.repo.getCompanyReport(campaign.id,id))!,plan=createApproachPlan(report,campaign,profile,['fact-0']),drafts=buildContactDrafts(plan,report,profile),company=await f.repo.getCompany(campaign.id,id);
        const readiness={target:true,reason:true,channel:true,evidenceIds:plan.evidenceIds,channelKind:'email' as const,confirmedAt:new Date().toISOString(),targetRevision:campaign.revision,reportId:report.id};
        snapshots.push(await f.repo.savePreparation(campaign.id,id,{readiness,plan,drafts},company.participationRevision));
      }
      const before=await f.repo.getCandidate(f.candidate.id),saved=await f.repo.addVisualObservation(before.id,before.revision,input()),activityCount=(await f.repo.listActivities(id)).length;
      for(let n=0;n<2;n++){
        const old=snapshots[n],current=await f.repo.getCompany(old.campaignId,id),report=(await f.repo.getCompanyReport(old.campaignId,id))!;
        assert.equal(current.readiness?.reason,false);assert.match(current.plan?.revalidateReason||'',/visuelle/);assert.deepEqual(current.drafts,old.drafts);assert.deepEqual(current.findingIds,old.findingIds);assert.equal(current.participationRevision,old.participationRevision+1);
        assert.notEqual(report.id,old.readiness?.reportId);assert.ok(report.facts.some(fact=>fact.visual?.assetId===assetId));
      }
      await f.repo.addVisualObservation(before.id,before.revision,input());
      assert.equal((await f.repo.listActivities(id)).length,activityCount);assert.equal((await f.repo.getCandidate(before.id)).revision,saved.revision);
    }finally{f.close();}
  });
}
