import type { DiscoveryProviders } from '../discovery-engine';
import { parisToday } from '../domain';
import type { ResearchData } from '../research-types';
const socialResearch = (city: string): ResearchData => {
  const url='https://www.instagram.com/atelier-demo-social/', id='src-social-fixture';
  const observations=[['identity','Le nom Atelier Social Démo est affiché sur le profil.'],['identity',`La commune ${city} est indiquée dans la présentation.`],['fit','L’activité d’électricité est mentionnée.'],['fit','La présentation annonce des interventions pour les particuliers.'],['presence','Un profil Instagram public est documenté.'],['presence','L’adresse du site officiel reste inconnue.'],['presentation','La description présente le dépannage électrique.'],['presentation','La description mentionne les installations électriques.'],['presentation','Le profil présente des exemples de réalisations.'],['contact','Le téléphone professionnel 04 00 00 01 23 est affiché.'],['contact','Le profil constitue un point de contact professionnel public.'],['opportunities','La présentation publique peut servir de point de départ à une discussion sur une page de présentation dédiée.']] as const;
  return { sources:[{id,provider:'google',url,title:'Atelier Social Démo',excerpt:'Électricité, dépannage et installations pour particuliers. Montpellier. Réalisations et téléphone professionnel 04 00 00 01 23. Profil de test déterministe.',collectedAt:new Date().toISOString(),query:'électricien '+city}],facts:observations.map(([section,text],index)=>({id:`social-fact-${index}`,section,kind:index===11?'hypothesis':'reported',sentiment:'neutral',text,sourceIds:[id],observedOn:parisToday(),scope:'Jeu de données de test déterministe ; aucun relevé réel.'})),contacts:[{kind:'phone',value:'04 00 00 01 23',sourceUrl:url,sourceId:id},{kind:'profileUrl',value:url,sourceUrl:url,sourceId:id}],profiles:[url],warnings:['Données de test déterministes. Le site officiel demeure inconnu.'],identityKeys:['social:'+url] };
};
export const discoveryFixtures:DiscoveryProviders={
  mixed:async(_repo,run)=>({leads:[{company:{siren:'',siret:'',name:'Atelier Social Démo',city:run.target.targetCity,business:'Électricité',activityCode:'',address:'',sourceUrl:'https://www.instagram.com/atelier-demo-social/'},dedupeKey:'social:atelier-demo-social',website:'',websites:[],research:socialResearch(run.target.targetCity)}],warnings:[]}),
  search:async input=>({companies:[{siren:'490484557',siret:'49048455700023',name:'Atelier Démo — lot',city:input.city,business:'Électricité',activityCode:'43.21A',address:'1 rue Démo',sourceUrl:'https://annuaire-entreprises.data.gouv.fr/entreprise/490484557'},{siren:'123456789',siret:'12345678900011',name:'Artisan — site à confirmer',city:input.city,business:'Électricité',activityCode:'43.21A',address:'2 rue Démo',sourceUrl:'https://annuaire-entreprises.data.gouv.fr/entreprise/123456789'}],total:2,page:1,totalPages:1,commune:{name:input.city,code:'69123'}}),
  sites:async c=>({websites:c.siren==='490484557'?[{url:'https://atelier-demo.test/',sourceUrl:'https://data.ademe.fr/datasets/liste-des-entreprises-rge-2-new',confidence:'exact'}]:[],warnings:[]}),
  html:async website=>({website,analyzedOn:parisToday(),pages:[{url:website,title:'Atelier Démo'}],contacts:[{kind:'email',value:'contact@atelier-demo.test',sourceUrl:website}],findings:[{id:'quote404',key:'technical',note:'Le lien Demander un devis renvoie HTTP 404.',sourceUrl:website,approach:'Proposer de rétablir la demande de devis.'}],warnings:['Analyse de test déterministe.']}),
  mobile:async()=>{throw new Error('PageSpeed indisponible : configuration de test.');},
};
