'use server';
import { headers } from 'next/headers';
import { revalidatePath } from 'next/cache';
import { redirect } from 'next/navigation';
import { requireAuthenticated } from '@/lib/auth';
import { isAllowedRequest } from '@/lib/security';
import { getCampaignRepository } from '@/lib/campaign-runtime';
import { dispatchDiscovery } from '@/lib/discovery-dispatch';
import { validatePublicSiteUrl } from '@/lib/site-analysis';
import type { ActionState } from '@/lib/types';
const str=(data:FormData,key:string)=>String(data.get(key)||'').trim();
async function authorize(){const h=await headers();if(!isAllowedRequest(h.get('host'),h.get('origin'),h.get('sec-fetch-site')))throw new Error('Requête non autorisée.');await requireAuthenticated();}
const fail=(error:unknown):ActionState=>({error:error instanceof Error?error.message:'Enregistrement impossible.'});
function refresh(){revalidatePath('/campagnes','layout');revalidatePath('/');revalidatePath('/prospects','layout');}
export async function saveCampaignAction(_:ActionState,data:FormData):Promise<ActionState>{let id:string;try{await authorize();const repo=await getCampaignRepository();const c=await repo.saveCampaign({name:str(data,'name'),targetCity:str(data,'targetCity'),targetBusiness:str(data,'targetBusiness'),targetCompanyType:str(data,'targetCompanyType'),targetOffer:str(data,'targetOffer'),targetExclusions:str(data,'targetExclusions'),activityCodes:str(data,'activityCodes'),keywords:str(data,'keywords')},str(data,'id')||undefined,Number(str(data,'revision'))||undefined);id=c.id;refresh();}catch(error){return fail(error);}redirect(`/campagnes/${id}`);}
export async function campaignStatusAction(_:ActionState,data:FormData):Promise<ActionState>{try{await authorize();const status=str(data,'status');if(!['active','paused','archived'].includes(status))throw new Error('État invalide.');await(await getCampaignRepository()).setCampaignStatus(str(data,'id'),status as 'active'|'paused'|'archived',Number(str(data,'revision')));refresh();return {ok:true,message:status==='active'?'Campagne réactivée. Les lots restent à reprendre explicitement.':'Campagne suspendue. Historique conservé.'};}catch(error){return fail(error);}}
export async function duplicateCampaignAction(_:ActionState,data:FormData):Promise<ActionState>{let id:string;try{await authorize();const repo=await getCampaignRepository(),old=await repo.getCampaign(str(data,'id'));const c=await repo.saveCampaign({name:`${old.name.slice(0,165)} — copie`,targetCity:old.targetCity,targetBusiness:old.targetBusiness,targetCompanyType:old.targetCompanyType||'',targetOffer:old.targetOffer||'',targetExclusions:old.targetExclusions||'',activityCodes:old.activityCodes,keywords:old.keywords||''});id=c.id;refresh();}catch(error){return fail(error);}redirect(`/campagnes/${id}`);}
export async function launchRunAction(_:ActionState,data:FormData):Promise<ActionState>{let id:string;try{await authorize();const repo=await getCampaignRepository(),ids=data.getAll('companyId').map(String);if(ids.length>20)throw new Error('Sélectionnez au maximum 20 entreprises.');const limit=ids.length||Number(str(data,'limit'));if(!ids.length&&![10,20].includes(limit))throw new Error('Choisissez 10 ou 20 entreprises.');const campaign=await repo.getCampaign(str(data,'campaignId'));const run=await repo.createRun(campaign.id,limit,str(data,'launchKey'),ids);id=run.id;try{await dispatchDiscovery();}catch{/* The committed run remains queued; reconciliation or explicit retry repairs dispatch. */}refresh();}catch(error){return fail(error);}redirect(`/campagnes/lots/${id}`);}
export async function controlRunAction(_:ActionState,data:FormData):Promise<ActionState>{try{await authorize();const operation=str(data,'operation');if(!['pause','resume','cancel'].includes(operation))throw new Error('Commande invalide.');await(await getCampaignRepository()).controlRun(str(data,'runId'),operation as 'pause'|'resume'|'cancel');if(operation==='resume')await dispatchDiscovery();refresh();return {ok:true,message:'État du lot enregistré.'};}catch(error){return fail(error);}}
export async function confirmWebsiteAction(_:ActionState,data:FormData):Promise<ActionState>{try{await authorize();const website=(await validatePublicSiteUrl(str(data,'website'))).href;await(await getCampaignRepository()).confirmWebsite(str(data,'candidateId'),website,Number(str(data,'revision')));await dispatchDiscovery();refresh();return {ok:true,message:'Site confirmé. Analyse mise en file.'};}catch(error){return fail(error);}}
export async function reviewCandidateAction(_:ActionState,data:FormData):Promise<ActionState>{
  let destination:string;
  try{await authorize();const decision=str(data,'decision');if(!['accept','reject','verify'].includes(decision))throw new Error('Décision invalide.');
    const repo=await getCampaignRepository(),candidateId=str(data,'candidateId'),candidate=await repo.getCandidate(candidateId);
    await repo.reviewCandidate(candidateId,Number(str(data,'revision')),decision as 'accept'|'reject'|'verify',data.getAll('findingId').map(String),data.getAll('contactIndex').map(x=>Number(x)),str(data,'approach'),str(data,'selectionComplete')==='yes');
    refresh();const next=(await repo.listCandidates(candidate.runId)).find(c=>['review','needs_site'].includes(c.status));destination=`/campagnes/lots/${candidate.runId}?filtre=review${next?'&candidat='+next.id:''}`;
  }catch(error){return fail(error);}
  redirect(destination);
}
export async function attachCompanyAction(_:ActionState,data:FormData):Promise<ActionState>{try{await authorize();await(await getCampaignRepository()).attach(str(data,'campaignId'),str(data,'companyId'));refresh();return {ok:true,message:'Entreprise rattachée à la campagne.'};}catch(error){return fail(error);}}
export async function saveApproachAction(_:ActionState,data:FormData):Promise<ActionState>{try{await authorize();await(await getCampaignRepository()).saveApproach(str(data,'campaignId'),str(data,'companyId'),str(data,'approach'),Number(str(data,'revision')));refresh();return {ok:true,message:'Angle enregistré pour cette campagne.'};}catch(error){return fail(error);}}
export async function removeCandidateParticipationAction(_:ActionState,data:FormData):Promise<ActionState>{try{await authorize();if(str(data,'confirmed')!=='yes')throw new Error('Confirmez le retrait de cette campagne.');await(await getCampaignRepository()).removeCandidateParticipation(str(data,'candidateId'),Number(str(data,'revision')),Number(str(data,'participationRevision')));refresh();return {ok:true,message:'Prospect retiré de cette campagne. La fiche commune et son historique sont conservés.'};}catch(error){return fail(error);}}
export async function restoreCandidateParticipationAction(_:ActionState,data:FormData):Promise<ActionState>{try{await authorize();const repo=await getCampaignRepository(),candidate=await repo.getCandidate(str(data,'candidateId'));if(candidate.status!=='accepted'||!candidate.companyId||candidate.revision!==Number(str(data,'revision')))throw new Error('Ce résultat a changé. Rechargez la page.');const run=await repo.getRun(candidate.runId);await repo.setArchived(run.campaignId,candidate.companyId,false,Number(str(data,'participationRevision')));refresh();return {ok:true,message:'Prospect réintégré dans cette campagne. Vérifiez la préparation avant de contacter.'};}catch(error){return fail(error);}}
