'use server';
import { randomUUID } from 'node:crypto';
import { headers } from 'next/headers';
import { revalidatePath } from 'next/cache';
import { requireAuthenticated } from '@/lib/auth';
import { isAllowedRequest } from '@/lib/security';
import { getCampaignRepository } from '@/lib/campaign-runtime';
import { createApproachPlan, buildContactDrafts, buildReplyDraft, buildFollowupDraft } from '@/lib/contact-preparation';
import { contactDraftSchema, contactEventSchema, providerProfileSchema } from '@/lib/research-schemas';
import { generateContactPreparationWithAI } from '@/lib/research-providers';
import { recordCreditPurchase } from '@/lib/research-budget';
import type { ActionState } from '@/lib/types';
const str=(data:FormData,name:string)=>String(data.get(name)||'').trim();
async function authorize(){const h=await headers();if(!isAllowedRequest(h.get('host'),h.get('origin'),h.get('sec-fetch-site')))throw new Error('Requête non autorisée.');await requireAuthenticated();}
function fail(e:unknown):ActionState{return {error:e instanceof Error?e.message:'Enregistrement impossible.'};}
function refresh(){revalidatePath('/','layout');}
async function context(data:FormData){const repo=await getCampaignRepository(),campaign=await repo.getCampaign(str(data,'campaignId')),company=await repo.getCompany(campaign.id,str(data,'companyId'));if(!company)throw new Error('Prospect introuvable.');const [report,profile]=await Promise.all([repo.getCompanyReport(campaign.id,company.id),repo.getProviderProfile()]);if(!report)throw new Error('Complétez le dossier avant de préparer le contact.');return {repo,campaign,company,report,profile};}
export async function saveProviderProfileAction(_:ActionState,data:FormData):Promise<ActionState>{try{await authorize();const repo=await getCampaignRepository();const input=providerProfileSchema.parse({...Object.fromEntries(['name','activity','skills','services','website','references','terms','prices','signature'].map(k=>[k,str(data,k)])),revision:Number(str(data,'revision'))});await repo.saveProviderProfile(input,Number(str(data,'revision')));refresh();return {ok:true,message:'Votre offre et votre signature sont enregistrées.'};}catch(e){return fail(e);}}
export async function prepareContactAction(_:ActionState,data:FormData):Promise<ActionState>{try{await authorize();const {repo,campaign,company,report,profile}=await context(data),evidenceIds=data.getAll('evidenceId').map(String);let plan=createApproachPlan(report,campaign,profile,evidenceIds);if(!plan)throw new Error('Aucun motif pertinent. Complétez le dossier ou gardez ce prospect pour plus tard.');
  const operation=str(data,'operation');if(!['plan','save_plan','drafts','ai'].includes(operation))throw new Error('Choisissez une action de préparation.');
  if(company.oppositionActive||company.archived||campaign.status!=='active')throw new Error('Réactivez ce suivi avant de préparer un contact.');
  if(Number(str(data,'revision'))!==company.participationRevision)throw new Error('La préparation a changé. Rechargez avant de rédiger.');
  const editable=['motive','hypothesis','help','question','nextStep'] as const;
  for(const key of editable){const value=str(data,key);if(value.length>({motive:12000,hypothesis:5000,help:5000,question:1500,nextStep:3000}[key]))throw new Error('La formulation est trop longue.');if(data.has(key)&&operation!=='plan')plan={...plan,[key]:value};}
  if(!plan.motive.trim()||!plan.question.trim())throw new Error('Précisez le motif et la question principale avant d’enregistrer.');
  const channelKind=str(data,'channelKind')==='phone'?'phone' as const:'email' as const;
  const planOnly=['plan','save_plan'].includes(operation);
  const readiness={target:data.get('target')==='yes',reason:!planOnly&&data.get('reason')==='yes',channel:data.get('channel')==='yes',evidenceIds:plan.evidenceIds,channelKind,confirmedAt:new Date().toISOString(),targetRevision:campaign.revision,reportId:report.id};
  let drafts=planOnly?[]:buildContactDrafts(plan,report,profile);
  if(str(data,'operation')==='ai'){const generated=await generateContactPreparationWithAI(repo,plan,report,profile,drafts,str(data,'operationKey')||randomUUID());plan=generated.plan;drafts=generated.drafts;}
  await repo.savePreparation(campaign.id,company.id,{plan,readiness,drafts},Number(str(data,'revision')));refresh();return {ok:true,message:operation==='save_plan'?'Vos formulations sont enregistrées. Confirmez le motif avant de préparer les textes.':operation==='plan'?'Nouvelle proposition enregistrée. Vérifiez le motif et les trois points avant de préparer les textes.':drafts.some(d=>d.origin==='openrouter')?'Préparation IA enregistrée. Relisez les textes avant tout contact.':operation==='ai'?'L’IA n’a pas fourni de préparation utilisable. Plan et brouillons déterministes enregistrés ; les preuves restent complètes.':'Plan et brouillons enregistrés. Relisez les textes avant tout contact.'};
}catch(e){return fail(e);}}
export async function editContactDraftAction(_:ActionState,data:FormData):Promise<ActionState>{try{await authorize();const {repo,campaign,company,report,profile}=await context(data),drafts=company.drafts||[],old=drafts.find(d=>d.id===str(data,'draftId'));if(!old)throw new Error('Brouillon introuvable.');
  const draft=contactDraftSchema.parse({...old,id:randomUUID(),version:old.version+1,text:str(data,'text'),subject:str(data,'subject'),createdAt:new Date().toISOString(),origin:'manual',usedAt:undefined,reportId:report.id,profileRevision:profile.revision});
  await repo.savePreparation(campaign.id,company.id,{drafts:[...drafts,draft]},Number(str(data,'revision')));refresh();return {ok:true,message:'Nouvelle version enregistrée, sans recherche ni appel IA.'};}catch(e){return fail(e);}}
export async function recordContactAction(_:ActionState,data:FormData):Promise<ActionState>{try{await authorize();const {repo,campaign,company}=await context(data);
  const opposition=str(data,'mode')!=='action'&&str(data,'outcome')==='opposition';
  if(!opposition&&str(data,'followup')!=='none'&&str(data,'followup')!=='yes')throw new Error('Choisissez une prochaine action ou Aucun suivi prévu.');
  const nextAction=!opposition&&str(data,'followup')==='yes'?{text:str(data,'nextText'),date:str(data,'nextDate')}:null;
  if(str(data,'mode')==='action')await repo.completeActionWithOutcome(campaign.id,company.id,str(data,'completeActionId'),{submittedKey:str(data,'submittedKey'),date:str(data,'date'),note:str(data,'note'),nextAction},Number(str(data,'revision')));
  else{const event=contactEventSchema.parse({id:str(data,'submittedKey'),submittedKey:str(data,'submittedKey'),date:str(data,'date'),channel:str(data,'channel'),outcome:str(data,'outcome'),note:str(data,'note'),draftId:str(data,'draftId')||undefined,nextAction});await repo.recordContact(campaign.id,company.id,event,Number(str(data,'revision')),str(data,'completeActionId')||undefined);}
  refresh();return {ok:true,message:'Résultat et prochaine étape enregistrés ensemble.'};}catch(e){return fail(e);}}
export async function prepareContinuationAction(_:ActionState,data:FormData):Promise<ActionState>{try{await authorize();const {repo,campaign,company,report,profile}=await context(data),event=company.contactEvents?.find(e=>e.id===str(data,'eventId'));if(!event||!company.plan||company.plan.revalidateReason)throw new Error('Choisissez un contact enregistré et revalidez le motif s’il a changé.');const verified=createApproachPlan(report,campaign,profile,company.plan.evidenceIds),plan={...verified,motive:company.plan.motive,hypothesis:company.plan.hypothesis,help:company.plan.help,question:company.plan.question,nextStep:company.plan.nextStep},draft=str(data,'kind')==='followup'?buildFollowupDraft(plan,report,profile,event):buildReplyDraft(plan,report,profile,event);await repo.savePreparation(campaign.id,company.id,{plan,drafts:[draft],...(company.readiness?{readiness:{...company.readiness,reason:false,reportId:report.id,targetRevision:campaign.revision}}:{})},Number(str(data,'revision')));refresh();return {ok:true,message:'Brouillon préparé à partir du contact enregistré. Relisez-le et confirmez à nouveau le motif avant de contacter.'};}catch(e){return fail(e);}}
export async function creditPurchaseAction(_:ActionState,data:FormData):Promise<ActionState>{try{await authorize();await recordCreditPurchase(await getCampaignRepository(),{id:str(data,'purchaseId'),date:str(data,'date'),amountEuro:Number(str(data,'amountEuro')),notes:str(data,'notes')});refresh();return {ok:true,message:'Achat payé enregistré. Aucun achat n’a été effectué par Brine.'};}catch(e){return fail(e);}}
export async function correctReportFactAction(_:ActionState,data:FormData):Promise<ActionState>{try{await authorize();const {repo,campaign,company}=await context(data);await repo.correctReportFact(campaign.id,company.id,str(data,'factId'),str(data,'note'),Number(str(data,'revision')),str(data,'mode')==='hypothesis'?'hypothesis':'fact');refresh();return {ok:true,message:'Correction conservée dans le dossier. Les préparations concernées sont à revalider.'};}catch(e){return fail(e);}}
export async function saveProfessionalContactAction(_:ActionState,data:FormData):Promise<ActionState>{try{await authorize();const {repo,campaign,company}=await context(data);await repo.saveProfessionalContact(campaign.id,company.id,{email:str(data,'email'),phone:str(data,'phone'),sourceUrl:str(data,'sourceUrl')},Number(str(data,'revision')),str(data,'sharedUpdatedAt'));refresh();return {ok:true,message:'Contact et provenance enregistrés. Confirmez le canal dans la préparation.'};}catch(e){return fail(e);}}
export async function linkCandidateCompanyAction(_:ActionState,data:FormData):Promise<ActionState>{try{await authorize();await(await getCampaignRepository()).linkCandidateCompany(str(data,'candidateId'),str(data,'companyId'),Number(str(data,'revision')));refresh();return {ok:true,message:'Identité confirmée. Vous pouvez reprendre votre décision.'};}catch(e){return fail(e);}}
