'use client';
import { useActionState, useState, useEffect } from 'react';
import { useRouter } from 'next/navigation';
import type { ReactNode } from 'react';
import type { ActionState, Company, Settings } from '@/lib/types';
import type { Campaign } from '@/lib/campaign-types';
import { saveCampaignAction, launchRunAction } from '@/app/campaign-actions';
export function CampaignMutation({action,children,submit,secondary=false}:{action:(state:ActionState,data:FormData)=>Promise<ActionState>;children:ReactNode;submit?:string;secondary?:boolean}){
  const [state,dispatch,pending]=useActionState(action,{});return <form action={dispatch} className="stack" aria-busy={pending} onReset={e=>e.preventDefault()}>{children}{submit&&<button className={`button ${secondary?'secondary':'primary'}`} disabled={pending} type="submit">{pending?'Enregistrement…':submit}</button>}{state.error&&<p className="form-error" role="alert">{state.error}</p>}{state.message&&<p className="form-success" role="status">{state.message}</p>}</form>;
}
export function CampaignForm({campaign,defaults}:{campaign?:Campaign;defaults:Settings}){const c=campaign||defaults;return <CampaignMutation action={saveCampaignAction} submit={campaign?'Enregistrer la campagne':'Créer la campagne'}>
  {campaign&&<><input type="hidden" name="id" value={campaign.id}/><input type="hidden" name="revision" value={campaign.revision}/></>}
  <div className="field"><label htmlFor="campaign-name">Nom de la campagne</label><input id="campaign-name" name="name" required maxLength={180} defaultValue={campaign?.name} placeholder="Ex. Électriciens Montpellier — demandes de devis"/></div>
  <div className="form-grid"><div className="field"><label htmlFor="campaign-city">Commune</label><input id="campaign-city" name="targetCity" required defaultValue={c.targetCity} maxLength={180}/></div><div className="field"><label htmlFor="campaign-business">Activité recherchée</label><input id="campaign-business" name="targetBusiness" required defaultValue={c.targetBusiness} maxLength={300}/></div></div>
  <div className="field"><label htmlFor="campaign-naf">Codes d’activité NAF</label><input id="campaign-naf" name="activityCodes" defaultValue={campaign?.activityCodes||'43.32A,43.33Z,43.34Z'} maxLength={200} placeholder="Ex. 43.21A"/><span className="field-help">Codes séparés par une virgule. Utilisés pour la recherche officielle. <a href="https://www.insee.fr/fr/information/2120875" target="_blank" rel="noopener noreferrer">Nomenclature INSEE</a></span></div>
  <div className="field"><label htmlFor="campaign-company-type">Type d’entreprise</label><input id="campaign-company-type" name="targetCompanyType" defaultValue={c.targetCompanyType||''} maxLength={300}/></div>
  <div className="field"><label htmlFor="campaign-offer">Offre proposée</label><textarea id="campaign-offer" name="targetOffer" defaultValue={c.targetOffer||''} maxLength={1000} placeholder="Ex. Améliorer le parcours de demande de devis sur mobile"/></div>
  <div className="field"><label htmlFor="campaign-exclusions">Exclusions à vérifier</label><textarea id="campaign-exclusions" name="targetExclusions" defaultValue={c.targetExclusions||''} maxLength={2000}/><span className="field-help">Ces conditions sont vérifiées pendant la revue et la qualification.</span></div>
  {campaign&&<p className="field-help">Les lots précédents gardent leur cible d’origine. Une modification de cible peut demander une revalidation des qualifications.</p>}
</CampaignMutation>;}
export function LaunchForm({campaignId,disabled=false}:{campaignId:string;disabled?:boolean}){const [key]=useState(()=>crypto.randomUUID());return <CampaignMutation action={launchRunAction} submit={disabled?undefined:'Lancer la recherche et l’analyse'}><input type="hidden" name="campaignId" value={campaignId}/><input type="hidden" name="launchKey" value={key}/><div className="field"><label htmlFor="batch-size">Taille du lot</label><select name="limit" id="batch-size" defaultValue="10" disabled={disabled}><option value="10">10 entreprises</option><option value="20">20 entreprises</option></select></div><p className="field-help">Recherche du site, contacts, audit HTML et test mobile. Les entreprises attendent votre revue avant d’être retenues.</p>{disabled&&<p className="inline-empty">Réactivez la campagne pour lancer une recherche.</p>}</CampaignMutation>;}
export function ExistingAnalysisForm({companies,campaignId}:{companies:Company[];campaignId:string}){const [selected,setSelected]=useState<string[]>([]),[key]=useState(()=>crypto.randomUUID());return <CampaignMutation action={launchRunAction} submit={selected.length?`Analyser les sites (${selected.length})`:undefined}><input type="hidden" name="campaignId" value={campaignId}/><input type="hidden" name="launchKey" value={key}/>{companies.map(c=><label className="check-label" key={c.id}><input type="checkbox" name="companyId" value={c.id} checked={selected.includes(c.id)} disabled={!selected.includes(c.id)&&selected.length>=20} onChange={e=>setSelected(e.target.checked?[...selected,c.id]:selected.filter(id=>id!==c.id))}/>{c.name}<span className="small muted">{c.website||'Site à trouver'}</span></label>)}<p className="field-help">Sélectionnez jusqu’à 20 entreprises. Les informations manuelles seront conservées.</p></CampaignMutation>;}
export function RunRefresh({active}:{active:boolean}){const router=useRouter();const [error,setError]=useState('');useEffect(()=>{if(!active)return;const timer=setInterval(()=>{if(document.visibilityState==='visible')router.refresh();},5000);return ()=>clearInterval(timer);},[active,router]);return <button className="button text-button small-button" type="button" onClick={()=>{setError('');try{router.refresh();}catch{setError('Actualisation indisponible.');}}}>{active?'Actualiser la progression':'Actualiser les résultats'}{error}</button>;}

export function CopyText({value}:{value:string}){const [message,setMessage]=useState('');return <div><button type="button" className="button secondary" onClick={async()=>{try{await navigator.clipboard.writeText(value);setMessage('Copié.');}catch{setMessage('Copie indisponible. Sélectionnez le texte dans le champ.');}}}>Copier l’angle</button><span role="status" className="small">{message}</span></div>;}
