'use client';
import { useActionState, useEffect, useState } from 'react';
import { ArrowLeft, ArrowRight, Check, Download, FileText, Pencil, Plus, X } from 'lucide-react';
import { FactVisualEvidence, reportDate } from './prospect-report';
import { FindingBadge } from './qualification-enrichment';
import { createClientBriefAction, compareProspectAction, confirmComparisonAction } from '@/app/client-brief-actions';
import { isClientBriefFact } from '@/lib/client-brief-rules';
import { clientBriefBodyWordCount } from '@/lib/client-brief-text';
import type { ProspectReport, ProviderProfile } from '@/lib/research-types';
import type { ComparisonSnapshot } from '@/lib/comparison';
import type { ActionState } from '@/lib/types';
function Feedback({state}:{state:ActionState}){return <>{state.error&&<p className="form-error" role="alert">{state.error}</p>}{state.message&&<p className="form-success" role="status">{state.message}</p>}</>;}
export function ComparisonWorkspace({campaignId,companyId,comparison,searchPlan = [],remainingQueries}:{campaignId:string;companyId:string;comparison:ComparisonSnapshot|null;searchPlan?:string[];remainingQueries?:number}){
  const [state,dispatch,pending]=useActionState(compareProspectAction,{}),[confirmation,confirm,confirming]=useActionState(confirmComparisonAction,{}),[key,setKey]=useState(()=>crypto.randomUUID());
  return <details className="panel section-panel comparison-workspace"><summary>Comparer avec deux entreprises locales · facultatif</summary><div className="details-body stack"><p>Qualité de présence et positions Google observées. Jusqu’à deux recherches partagées dans le quota gratuit ; les relevés compatibles sont réutilisés.</p><div className="comparison-search-plan"><strong>Recherches prévues avant lancement</strong>{searchPlan.length > 0 ? <ol>{searchPlan.slice(0,2).map(query=><li key={query}>« {query} »</li>)}</ol> : <p>Deux requêtes maximum, liées à l’activité et à la ville de la campagne.</p>}<p>{remainingQueries === undefined ? 'Le quota disponible sera vérifié avant chaque recherche.' : `${remainingQueries} recherche${remainingQueries > 1 ? 's' : ''} disponible${remainingQueries > 1 ? 's' : ''} dans le quota gratuit.`}</p>{remainingQueries === 0 && <p>Les relevés déjà en cache peuvent être réutilisés. Aucune recherche au-delà du quota ne sera lancée.</p>}</div><form action={dispatch} className="stack"><input type="hidden" name="campaignId" value={campaignId}/><input type="hidden" name="companyId" value={companyId}/><input type="hidden" name="operationKey" value={key}/><details><summary>Choisir ou remplacer les sites comparés</summary><div className="form-grid"><label className="field">Premier site<input type="url" name="replacement1" onChange={()=>setKey(crypto.randomUUID())} placeholder="https://…"/></label><label className="field">Deuxième site<input type="url" name="replacement2" onChange={()=>setKey(crypto.randomUUID())} placeholder="https://…"/></label></div></details><label className="check-label"><input type="checkbox" name="confirmed" value="yes" required/>Lancer cette comparaison, avec au maximum deux nouvelles recherches Google.</label><button className="button secondary" disabled={pending}>{pending?'Comparaison en cours…':'Comparer à la demande'}</button><Feedback state={state}/></form>
  {comparison&&<>{comparison.queries.length < 2 && <p className="data-notice">Comparaison partielle · {comparison.queries.length}/2 recherches exploitables. Consultez les limites ci-dessous avant d’en tirer une conclusion.</p>}<div className="stack">{comparison.queries.map(query=><article className="qualification-finding" key={query.query}><strong>{query.query}</strong><p className="field-help">{query.location} · {query.recordedAt.slice(0,10)} · ordinateur · dix premiers résultats organiques</p><ol className="comparison-results">{query.results.map(row=><li key={row.position}><a href={row.url} target="_blank" rel="noopener noreferrer">{row.position}. {row.title}</a></li>)}</ol></article>)}</div><form action={confirm} className="stack"><input type="hidden" name="campaignId" value={campaignId}/><input type="hidden" name="companyId" value={companyId}/><input type="hidden" name="comparisonId" value={comparison.id}/>{comparison.competitors.map((c,index)=><article className="qualification-finding" key={c.url}><a href={c.url} target="_blank" rel="noopener noreferrer">{c.name}</a>{c.notes.map(note=><p key={note}>{note}</p>)}<label className="check-label"><input type="checkbox" name="competitorIndex" value={index} defaultChecked={c.confirmed}/>Cette entreprise est comparable sur ce marché.</label></article>)}<button className="button secondary" disabled={confirming}>Enregistrer la comparabilité</button><Feedback state={confirmation}/></form><details><summary>Couverture et limites</summary>{comparison.warnings.map(w=><p key={w} className="field-help">{w}</p>)}</details></>}
  </div></details>;
}
const briefSteps = ['Préparer', 'Choisir les points', 'Relire', 'Générer le PDF'];


export function ClientBriefWorkspace({ campaignId, companyId, report, profile, briefs, comparison = null, website = '' }: {
  campaignId: string; companyId: string; report: ProspectReport; profile: ProviderProfile;
  briefs: Array<{ id: string; createdAt: string; stale: boolean }>; website?:string; comparison?: ComparisonSnapshot | null;
}) {
  const [open, setOpen] = useState(false), [step, setStep] = useState(0), [reviewed, setReviewed] = useState(false);
  const [versionKey, setVersionKey] = useState(() => crypto.randomUUID());
  const [state, dispatch, pending] = useActionState(createClientBriefAction, {});
  const [pdfPreview, setPdfPreview] = useState<{ url: string; signature: string } | null>(null);
  const [previewing, setPreviewing] = useState(false), [previewError, setPreviewError] = useState('');
  const available = report.facts.filter(fact => isClientBriefFact(fact, report));
  const [situation, setSituation] = useState(`Quelques points relevés sur la présence numérique de ${report.companyName}, à vérifier selon vos priorités.`);
  const [positives, setPositives] = useState('');
  const [points, setPoints] = useState<Array<{ factId: string; text: string; effect: string; help: string }>>([]);
  const [actions, setActions] = useState(['Vérifier ensemble les constats retenus et leur utilité pour vos visiteurs.', 'Définir une amélioration proportionnée à votre priorité.']);
  const [invitation, setInvitation] = useState('Quel aspect aimeriez-vous simplifier en priorité ? Pickles Studio peut vous aider à préciser une prochaine étape utile.');
  const payload = { situation, positives, points, actions, invitation };
  const signature = JSON.stringify([report.id, profile.revision, comparison?.id, payload]);
  const previewUrl = pdfPreview?.signature === signature ? pdfPreview.url : null;
  const confirmedComparisons = comparison?.competitors.filter(competitor => competitor.confirmed) || [];
  const wordCount = clientBriefBodyWordCount({...payload,companyName:report.companyName,website,comparison,points:points.map(point=>({...point,fact:available.find(f=>f.id===point.factId)}))});
  const selectionValid = points.length > 0 && points.every(point => point.text.trim() && available.some(fact => fact.id === point.factId));
  const contentValid = Boolean(situation.trim() && actions.length && actions.every(action => action.trim()) && invitation.trim());
  const tooLong = wordCount > 450;
  const generated = state.briefId === versionKey;
  const generatedStale = generated && Boolean(briefs.find(brief => brief.id === versionKey)?.stale);
  const pictures = points.flatMap(point => { const fact = available.find(item => item.id === point.factId); return fact?.visual && (fact.visual.assetId || fact.visual.screenshot) ? [fact] : []; }).slice(0, 1);
  useEffect(() => { setReviewed(false); }, [report.id, comparison?.id, profile.revision]);
  useEffect(() => () => { if (pdfPreview?.url) URL.revokeObjectURL(pdfPreview.url); }, [pdfPreview]);
  async function preparePreview() {
    setPreviewing(true); setPreviewError(''); setReviewed(false);
    const data = new FormData(); data.set('campaignId', campaignId); data.set('companyId', companyId); data.set('reportId', report.id); data.set('profileRevision', String(profile.revision)); data.set('payload', JSON.stringify(payload));
    try {
      const response = await fetch('/api/client-briefs/preview', { method: 'POST', body: data });
      if (!response.ok) { const result = await response.json().catch(() => null); throw new Error(result?.error || 'Aperçu indisponible.'); }
      if (!response.headers.get('content-type')?.includes('application/pdf')) throw new Error('L’aperçu PDF est indisponible. Actualisez la page et réessayez.');
      setPdfPreview({ url: URL.createObjectURL(await response.blob()), signature });
    } catch (error) { setPreviewError(error instanceof Error ? error.message : 'Aperçu indisponible.'); }
    finally { setPreviewing(false); }
  }
  function edit(change: () => void) {
    change(); setReviewed(false);
    if (generated) setVersionKey(crypto.randomUUID());
  }
  function changePoint(index: number, key: 'text' | 'effect' | 'help', value: string) {
    edit(() => setPoints(previous => previous.map((point, item) => item === index ? { ...point, [key]: value } : point)));
  }
  function startVersion() { setVersionKey(crypto.randomUUID()); setReviewed(false); setStep(0); setOpen(true); }
  return <section className="panel section-panel client-brief-workspace" aria-labelledby="client-brief-heading">
    <div className="client-brief-opening"><div><span className="eyebrow">Pickles Studio — par Brine</span><h2 id="client-brief-heading">Partager un bilan utile</h2><p>Un PDF court et soigné pour aider cette entreprise à voir ses priorités et ouvrir une conversation.</p></div><FileText size={32} aria-hidden="true"/></div>
    <p className="client-brief-scope">Deux pages A4 · jusqu’à trois constats confirmés · 450 mots maximum hors sources</p>
    {!open ? <div className="client-brief-start"><button type="button" className="button secondary" onClick={() => setOpen(true)}>Préparer le bilan<ArrowRight size={16} aria-hidden="true"/></button><p>La préparation et l’export utilisent le dossier conservé. Aucune nouvelle IA ni collecte n’est lancée.</p></div> : <>
      <nav className="client-brief-steps" aria-label="Étapes du bilan client">{briefSteps.map((label, index) => <button key={label} type="button" aria-current={step === index ? 'step' : undefined} disabled={pending || (index >= 2 && (!selectionValid || !contentValid)) || (index === 3 && !reviewed)} className={step === index ? 'selected' : ''} onClick={() => setStep(index)}><span>{index + 1}</span>{label}</button>)}</nav>
      <div className={'client-brief-word-count' + (tooLong ? ' too-long' : '')} role="status"><strong>{wordCount} / 450 mots</strong><span>{tooLong ? 'Réduisez explicitement les textes ou les points avant de générer.' : 'Sources exclues · comparaison documentée incluse'}</span></div>
      <form action={dispatch} className="stack client-brief-editor" data-testid="client-brief-form" aria-busy={pending}>
        <input type="hidden" name="campaignId" value={campaignId}/><input type="hidden" name="companyId" value={companyId}/><input type="hidden" name="reportId" value={report.id}/><input type="hidden" name="profileRevision" value={profile.revision}/><input type="hidden" name="submittedKey" value={versionKey}/><input type="hidden" name="payload" value={JSON.stringify(payload)}/>
        {step === 0 && <div className="stack"><div className="review-block-heading"><h3>Le contexte et ce qui fonctionne</h3><p>Quelques phrases suffisent. Gardez un ton factuel, utile et adapté à l’entreprise.</p></div>
          <label className="field">Situation actuelle<textarea value={situation} maxLength={1500} onChange={event => edit(() => setSituation(event.target.value))} rows={3}/></label>
          <label className="field">Point positif documenté<textarea value={positives} maxLength={1000} onChange={event => edit(() => setPositives(event.target.value))} rows={3} placeholder="Un atout réel observé dans le dossier…"/></label>
          {available.some(fact => fact.sentiment === 'positive') && <details className="workspace-detail"><summary>Reprendre un point positif confirmé</summary><div className="stack">{available.filter(fact => fact.sentiment === 'positive').slice(0, 3).map(fact => <button key={fact.id} type="button" className="button secondary client-brief-positive-choice" disabled={fact.text.length > 1000} onClick={() => edit(() => setPositives(fact.text))}>{fact.text}</button>)}</div></details>}
          <div className="client-brief-step-actions"><button type="button" className="button primary" disabled={!situation.trim()} onClick={() => setStep(1)}>Choisir les constats<ArrowRight size={16} aria-hidden="true"/></button></div>
        </div>}
        {step === 1 && <div className="stack"><div className="review-block-heading"><h3>Choisir ce qui sera utile au destinataire</h3><p>Retenez un à trois constats confirmés. Votre score et vos notes personnelles restent dans Brine.</p></div>
          <fieldset className="client-brief-point-selection"><legend>Constats confirmés · {points.length}/3 sélectionnés</legend>{available.length ? available.map(fact => <label className="client-brief-point-choice" key={fact.id}><input type="checkbox" checked={points.some(point => point.factId === fact.id)} disabled={points.length >= 3 && !points.some(point => point.factId === fact.id)} onChange={event => edit(() => setPoints(previous => event.target.checked ? [...previous, { factId: fact.id, text: fact.text, effect: '', help: '' }] : previous.filter(point => point.factId !== fact.id)))}/><span><FindingBadge fact={fact}/><strong>{fact.text}</strong><small>{reportDate(fact.observedOn)} · {fact.visual?.device === 'mobile' ? 'Mobile' : fact.visual?.device === 'desktop' ? 'Ordinateur' : fact.scope}</small></span></label>) : <p className="field-help">Confirmez d’abord un constat dans les cinq critères de qualification.</p>}</fieldset>
          {points.map((point, index) => <section className="client-brief-selected-point stack" key={point.factId}><div className="client-brief-point-heading"><h4>Constat {index + 1}</h4><button type="button" className="button text-button" onClick={() => edit(() => setPoints(previous => previous.filter(item => item.factId !== point.factId)))}><X size={15} aria-hidden="true"/>Retirer</button></div>
            {!available.some(fact => fact.id === point.factId) && <p className="form-error">Ce constat doit être reconfirmé dans la qualification ou retiré du bilan.</p>}
            <label className="field">Constat à présenter<textarea value={point.text} maxLength={1200} onChange={event => changePoint(index, 'text', event.target.value)} rows={3}/></label><label className="field">Effet possible à vérifier (facultatif)<textarea value={point.effect} maxLength={1000} onChange={event => changePoint(index, 'effect', event.target.value)} rows={2} placeholder="Ce que cela peut gêner, sans annoncer de perte de clients."/></label><label className="field">Piste d’amélioration ciblée (facultative)<textarea value={point.help} maxLength={1000} onChange={event => changePoint(index, 'help', event.target.value)} rows={2}/></label>
            {available.find(fact => fact.id === point.factId)?.visual && <FactVisualEvidence fact={available.find(fact => fact.id === point.factId)!}/>}
          </section>)}
          <div className="review-block-heading"><h3>Une ou deux actions utiles</h3><p>Proposez une suite simple qui rende service à l’entreprise.</p></div>{actions.map((value, index) => <div className="client-brief-action-field" key={index}><label className="field">Action utile {index + 1}<textarea value={value} maxLength={700} onChange={event => edit(() => setActions(previous => previous.map((action, item) => item === index ? event.target.value : action)))} rows={2}/></label>{actions.length > 1 && <button type="button" className="button text-button" aria-label={'Retirer l’action ' + (index + 1)} onClick={() => edit(() => setActions(previous => previous.filter((_, item) => item !== index)))}><X size={16} aria-hidden="true"/></button>}</div>)}
          {actions.length < 2 && <button type="button" className="button secondary" onClick={() => edit(() => setActions(previous => [...previous, '']))}><Plus size={16} aria-hidden="true"/>Ajouter une deuxième action</button>}
          <label className="field">Invitation discrète à répondre<textarea value={invitation} maxLength={700} onChange={event => edit(() => setInvitation(event.target.value))} rows={3}/></label>
          <div className="client-brief-step-actions"><button type="button" className="button secondary" onClick={() => setStep(0)}><ArrowLeft size={16} aria-hidden="true"/>Revenir au contexte</button><button type="button" className="button primary" disabled={!selectionValid || !contentValid} onClick={() => setStep(2)}>Relire le bilan<ArrowRight size={16} aria-hidden="true"/></button></div>
        </div>}
        {step === 2 && <div className="stack"><div className="review-block-heading"><h3>Relire ce que l’entreprise recevra</h3><p>Vérifiez les faits, les captures et le ton. Ouvrez le vrai PDF avant de confirmer la relecture. Un dépassement vous demandera de réduire le contenu.</p></div>
          <button type="button" className="button primary" disabled={previewing || tooLong || !selectionValid || !contentValid} onClick={preparePreview}>{previewing ? 'Préparation de l’aperçu…' : previewUrl ? 'Actualiser l’aperçu PDF' : 'Voir le véritable aperçu PDF'}<FileText size={16} aria-hidden="true"/></button>
          {previewError && <p className="form-error" role="alert">{previewError}</p>}
          {previewUrl && <div className="client-brief-pdf-preview"><a className="button primary" href={previewUrl} target="_blank" rel="noopener noreferrer">Ouvrir les deux pages en grand<ArrowRight size={16} aria-hidden="true"/></a><p className="field-help">Ouvrez ce PDF privé pour relire les deux pages, puis confirmez la relecture ci-dessous. Aucune collecte, IA ou version enregistrée à cette étape.</p><details className="client-brief-inline-preview"><summary>Afficher le PDF dans cette page</summary><iframe src={previewUrl} title="Aperçu du bilan client Pickles Studio"/></details></div>}
          <details className="client-brief-text-preview" open={!previewUrl}><summary>Relire le contenu du bilan</summary>
          <div className="client-brief-preview-pages">
            <article className="client-brief-preview-page"><div className="client-brief-brand"><img src="/pickles-logo.svg" alt="Pickles Studio" width="138" height="20"/><span>par Brine</span></div><div className="client-brief-page-body"><span className="eyebrow">Bilan de présence numérique</span><h3>{report.companyName}</h3><p>{situation}</p>{positives && <section className="client-brief-positive"><h4>Ce qui fonctionne</h4><p>{positives}</p></section>}<h4>Les constats à vérifier</h4>{points.map((point, index) => <section className="client-brief-preview-point" key={point.factId}><span>{String(index + 1).padStart(2, '0')}</span><div><strong>{point.text}</strong>{point.effect && <p>Effet possible : {point.effect}</p>}{point.help && <p>Piste utile : {point.help}</p>}</div></section>)}{pictures.map(fact => <FactVisualEvidence key={fact.id} fact={fact} expanded/>)}<p className="client-brief-page-number">Pickles Studio — par Brine · 1 / 2</p></div></article>
            <article className="client-brief-preview-page"><div className="client-brief-brand"><img src="/pickles-logo.svg" alt="Pickles Studio" width="138" height="20"/><span>par Brine</span></div><div className="client-brief-page-body"><span className="eyebrow">Repères et prochaines étapes</span><h3>Des améliorations utiles, à votre rythme</h3>
              {comparison?.queries.length ? <section><h4>Recherches Google observées</h4>{comparison.queries.map(query => <div className="client-brief-comparison-query" key={query.query}><strong>« {query.query} »</strong><p>{query.location} · ordinateur · {reportDate(query.recordedAt)} · dix premiers résultats organiques</p></div>)}{confirmedComparisons.map(competitor => <div className="client-brief-comparison-company" key={competitor.url}><a href={competitor.url} target="_blank" rel="noopener noreferrer">{competitor.name} ↗</a>{competitor.notes.map((note, index) => <p key={index}>{note}</p>)}</div>)}</section> : <p className="field-help">Aucune comparaison documentée pour ce bilan.</p>}
              <section><h4>{actions.length === 1 ? 'Une action utile' : 'Deux actions utiles'}</h4>{actions.map((action, index) => <p className="client-brief-preview-action" key={index}><strong>{String(index + 1).padStart(2, '0')}</strong>{action}</p>)}</section><p className="client-brief-invitation">{invitation}</p>
              <section className="client-brief-preview-sources"><h4>Sources et périmètre</h4>{report.sources.filter(source => points.some(point => available.find(fact => fact.id === point.factId)?.sourceIds.includes(source.id))).map(source => <p key={source.id}><a href={source.url} target="_blank" rel="noopener noreferrer">{source.title || source.url} ↗</a> · {reportDate(source.collectedAt)}</p>)}<p>Vérifications ponctuelles sur les pages et écrans cités. Les effets possibles restent à confirmer.</p></section><p className="client-brief-page-number">Pickles Studio — par Brine · 2 / 2</p>
            </div></article>
          </div>
          </details>
          <label className="check-label client-brief-review"><input type="checkbox" checked={reviewed} disabled={!previewUrl} onChange={event => setReviewed(event.target.checked)}/>J’ai relu le PDF et les constats sélectionnés.</label>
          <div className="client-brief-step-actions"><button type="button" className="button secondary" onClick={() => setStep(1)}><Pencil size={16} aria-hidden="true"/>Modifier les points</button><button type="button" className="button primary" disabled={!reviewed || tooLong} onClick={() => setStep(3)}>Passer à la génération<ArrowRight size={16} aria-hidden="true"/></button></div>
        </div>}
        {step === 3 && <div className="client-brief-export stack"><FileText size={32} aria-hidden="true"/><h3>{generatedStale ? 'Cette version est à actualiser' : generated ? 'Le bilan est prêt' : 'Générer la version relue'}</h3><p>{points.length} constat{points.length > 1 ? 's' : ''} · {pictures.length} capture{pictures.length > 1 ? 's' : ''} · {wordCount} mots hors sources</p><p>{generatedStale ? 'Le dossier a évolué. La version historique reste accessible ; préparez une nouvelle version avant de la partager.' : 'Le PDF conserve cette version. Générer et télécharger ne déclenchent aucune nouvelle recherche ni IA.'}</p><input type="hidden" name="reviewed" value={reviewed ? 'yes' : ''}/>
          {generated ? <><a className="button primary" href={`/api/client-briefs/${state.briefId}`}><Download size={16} aria-hidden="true"/>Télécharger le PDF</a><button className="button secondary" type="button" onClick={startVersion}>Préparer une nouvelle version</button></> : <><button className="button primary" type="submit" disabled={pending || !reviewed || !previewUrl || tooLong || !selectionValid || !contentValid}>{pending ? 'Génération…' : 'Générer le PDF'}<FileText size={16} aria-hidden="true"/></button><button className="button secondary" type="button" disabled={pending} onClick={() => setStep(2)}><ArrowLeft size={16} aria-hidden="true"/>Revenir à la relecture</button></>}
        </div>}
        <Feedback state={state}/>
      </form>
    </>}
    {briefs.length > 0 && <details className="workspace-detail client-brief-versions"><summary>Versions précédentes ({briefs.length})</summary><div className="stack">{briefs.map(brief => <div key={brief.id}><a href={`/api/client-briefs/${brief.id}`} className="open-link"><Download size={16} aria-hidden="true"/>Bilan du {reportDate(brief.createdAt)}</a><p>{brief.stale ? 'À actualiser : le dossier, le profil ou le comparatif a changé.' : 'Version relue conservée'}</p></div>)}</div></details>}
  </section>;
}
