'use client';
import Link from 'next/link';
import { suggestedContactSequence } from '@/lib/contact-sequence';
import { useActionState, useEffect, useState } from 'react';
import type { ActionState } from '@/lib/types';
import type { Campaign, CampaignCompany } from '@/lib/campaign-types';
import type { ApproachPlan, ContactDraft, ProspectReport as Report, ProviderProfile, ResearchFact } from '@/lib/research-types';
import { prepareContactAction, editContactDraftAction, recordContactAction, saveProviderProfileAction, prepareContinuationAction, correctReportFactAction, saveProfessionalContactAction } from '@/app/v2-actions';
import { ProspectReport } from './prospect-report';
type Mutation=(state:ActionState,data:FormData)=>Promise<ActionState>;
function Feedback({state}:{state:ActionState}){return <>{state.error&&<p role="alert" className="form-error">{state.error}</p>}{state.message&&<p role="status" className="form-success">{state.message}</p>}</>;}
function SaveForm({action,children,submit}:{action:Mutation;children:React.ReactNode;submit:string}){const [state,dispatch,pending]=useActionState(action,{});return <form className="stack" action={dispatch} onReset={e=>e.preventDefault()} aria-busy={pending}>{children}<button className="button primary" disabled={pending}>{pending?'Enregistrement…':submit}</button><Feedback state={state}/></form>;}
function ContextFields({company,campaign}:{company:CampaignCompany;campaign:Campaign}){return <><input type="hidden" name="campaignId" value={campaign.id}/><input type="hidden" name="companyId" value={company.id}/><input type="hidden" name="revision" value={company.participationRevision}/></>;}
function ProfessionalContactForm({company,campaign,report}:{company:CampaignCompany;campaign:Campaign;report:Report}) {
  const [email,setEmail]=useState(company.contact.email),[phone,setPhone]=useState(company.contact.phone),[source,setSource]=useState(report.contacts.find(c=>c.value===company.contact.email||c.value===company.contact.phone)?.sourceUrl||'');
  return <SaveForm action={saveProfessionalContactAction} submit="Enregistrer le contact avec sa provenance"><ContextFields company={company} campaign={campaign}/><input type="hidden" name="sharedUpdatedAt" value={company.updatedAt}/><p className="field-help">Les coordonnées sont communes aux campagnes. Choisissez une coordonnée publique du dossier ou saisissez votre vérification.</p>{report.contacts.filter(c=>['email','phone'].includes(c.kind)).map((c,i)=><button type="button" className="button secondary small-button" key={i} onClick={()=>{if(c.kind==='email')setEmail(c.value);else setPhone(c.value);setSource(c.sourceUrl);}}>Utiliser {c.value}</button>)}<div className="form-grid"><div className="field"><label htmlFor={'inline-email-'+company.id}>Email à confirmer</label><input id={'inline-email-'+company.id} name="email" type="email" value={email} onChange={e=>setEmail(e.target.value)} maxLength={320}/></div><div className="field"><label htmlFor={'inline-phone-'+company.id}>Téléphone à confirmer</label><input id={'inline-phone-'+company.id} name="phone" type="tel" value={phone} onChange={e=>setPhone(e.target.value)} maxLength={100}/></div></div><div className="field"><label htmlFor={'inline-source-'+company.id}>Source publique du contact</label><input id={'inline-source-'+company.id} type="url" name="sourceUrl" value={source} onChange={e=>setSource(e.target.value)} required maxLength={2000} placeholder="https://…"/></div></SaveForm>;
}
export function ProviderProfileForm({profile,compact=false}:{profile:ProviderProfile;compact?:boolean}) {
  const fields=[['name','Votre nom'],['activity','Votre activité'],['skills','Compétences'],['services','Prestations proposées'],['website','Votre site ou portfolio'],['references','Références réelles et liens'],['terms','Conditions et engagements que vous proposez'],['prices','Tarifs déclarés (facultatif)'],['signature','Signature des messages']] as const;
  const field=([key,label]:typeof fields[number])=><div className="field" key={key}><label htmlFor={'profile-'+key}>{label}</label>{['name','activity','website'].includes(key)?<input id={'profile-'+key} name={key} defaultValue={profile[key]} type={key==='website'?'url':'text'} maxLength={key==='name'?180:key==='activity'?300:2048}/>:<textarea id={'profile-'+key} name={key} defaultValue={profile[key]} maxLength={key==='references'?10000:key==='prices'?3000:key==='signature'?2000:5000}/>}</div>;
  return <SaveForm action={saveProviderProfileAction} submit="Enregistrer mon profil"><input type="hidden" name="revision" value={profile.revision}/>{compact?<><p className="field-help">Votre nom et votre activité permettent de vous présenter. L’aide proposée utilise aussi l’offre de cette campagne.</p>{fields.slice(0,2).map(field)}<details className="profile-optional"><summary>Compléter ma présentation (facultatif)</summary><div className="stack details-body">{fields.slice(2).map(field)}</div></details></>:fields.map(field)}<p className="field-help">Brine utilise ces informations pour présenter votre activité. Renseignez uniquement des références, tarifs et engagements que vous pouvez proposer.</p></SaveForm>;
}
function PlanEditor({company,campaign,report,profile,plan,aiAvailable,eligibleEvidence}:{company:CampaignCompany;campaign:Campaign;report:Report;profile:ProviderProfile;plan:ApproachPlan|null;aiAvailable:boolean;eligibleEvidence:ResearchFact[]}) {
  const [state,dispatch,pending]=useActionState(prepareContactAction,{}),[operationKey]=useState(()=>crypto.randomUUID());
  const [evidence,setEvidence]=useState(plan?.evidenceIds[0]||''),[channel,setChannel]=useState(company.readiness?.channelKind||'email');
  useEffect(()=>setEvidence(plan?.evidenceIds[0]||''),[plan?.id]);
  const unchanged=Boolean(plan&&plan.evidenceIds.includes(evidence));
  return <form action={dispatch} onReset={e=>e.preventDefault()} className="stack" aria-busy={pending}><ContextFields company={company} campaign={campaign}/><input type="hidden" name="operationKey" value={operationKey}/>
    <p className="eyebrow">1 · CHOISIR UN MOTIF DOCUMENTÉ</p><div className="field"><label htmlFor={'motive-evidence-'+company.id}>Preuve principale</label><select id={'motive-evidence-'+company.id} name="evidenceId" value={evidence} onChange={e=>setEvidence(e.target.value)}><option value="">Choisir un constat du dossier</option>{eligibleEvidence.map(f=><option key={f.id} value={f.id}>{f.text}</option>)}</select></div>
    {unchanged&&plan?<><p className="field-help">{plan.rationale}</p><div className="approach-chain" key={plan.id}>{([['motive','Motif'],['hypothesis','Hypothèse à confirmer'],['help','Aide proportionnée'],['question','Question principale'],['nextStep','Suite possible']] as const).map(([key,label])=><div className="field" key={key}><label htmlFor={key+'-'+company.id}>{label}</label><textarea id={key+'-'+company.id} name={key} defaultValue={plan[key]} maxLength={key==='motive'?12000:key==='question'?1500:key==='nextStep'?3000:5000}/></div>)}</div><p className="small muted">Offre utilisée : {plan.offer||'À renseigner'} · Objectif : ouvrir une conversation</p>{plan.revalidateReason&&<p className="form-error">{plan.revalidateReason}</p>}</>:<p className="field-help">Construisez le plan avec cette preuve avant de rédiger. La piste doit correspondre à votre offre.</p>}
    {plan?.alternatives?.length? <details><summary>Autres motifs possibles</summary>{plan.alternatives.map((a,i)=><div key={i} className="evidence-card"><p>{a.motive}</p><p className="small muted">{a.rationale}</p><button type="button" className="button secondary small-button" onClick={()=>setEvidence(a.evidenceIds[0]||'')}>Choisir cette preuve</button></div>)}</details>:null}
    <div className="button-row">{unchanged&&<button type="submit" name="operation" value="save_plan" className="button primary" disabled={pending}>Enregistrer mes formulations</button>}<button type="submit" name="operation" value="plan" className="button secondary" disabled={pending||!evidence}>Proposer un plan pour cette preuve</button></div><p className="field-help">Enregistrer conserve vos mots sans nouvelle recherche. Proposer refait les formulations à partir de la preuve sélectionnée.</p>{!eligibleEvidence.length&&<p className="field-help">Aucun motif compatible avec votre offre n’est documenté pour le moment. Complétez le dossier ou <Link href={'/campagnes/'+campaign.id+'?etape=cibler'}>précisez l’aide proposée dans cette campagne</Link>.</p>}
    <p className="eyebrow">2 · CONFIRMER LES TROIS POINTS</p>
    <label className="check-label"><input type="checkbox" name="target" value="yes" defaultChecked={company.readiness?.target}/>Cette entreprise correspond à ma cible et aux exclusions vérifiées.</label>
    <label className="check-label"><input type="checkbox" key={company.readiness?.confirmedAt||'new'} name="reason" value="yes" defaultChecked={company.readiness?.reason}/>Ce motif est documenté et lié à une aide que je propose.</label>
    <div className="field"><label htmlFor={'ready-channel-'+company.id}>Canal professionnel choisi</label><select id={'ready-channel-'+company.id} name="channelKind" value={channel} onChange={e=>setChannel(e.target.value as 'email'|'phone')}><option value="email">Email · {company.contact.email||'à renseigner'}</option><option value="phone">Appel · {company.contact.phone||'à renseigner'}</option></select></div>
    <label className="check-label"><input type="checkbox" name="channel" value="yes" defaultChecked={company.readiness?.channel}/>J’ai vérifié ce contact professionnel et sa provenance.</label>
    {!profile.activity&&<p className="field-help"><Link href="/sauvegarde#profil">Renseigner mon activité et mon offre</Link> pour préparer une présentation fidèle.</p>}
    <div className="button-row"><button className="button primary" name="operation" value="drafts" disabled={pending||!unchanged||!profile.activity}>{pending?'Préparation…':'Valider et préparer mes textes'}</button>{aiAvailable&&<button className="button secondary" name="operation" value="ai" disabled={pending||!unchanged||!profile.activity}>Rédiger avec l’IA · budget réservé</button>}</div><Feedback state={state}/>
  </form>;
}
function DraftEditor({company,campaign,draft,stale=false}:{company:CampaignCompany;campaign:Campaign;draft:ContactDraft;stale?:boolean}) {
  const [text,setText]=useState(draft.text),[subject,setSubject]=useState(draft.subject),[loaded,setLoaded]=useState(false),[copied,setCopied]=useState('');
  const key='brine-draft-'+draft.id,normalizeNewlines=(value:string)=>value.replace(/\r\n?/g,'\n'),hasUnsavedChanges=normalizeNewlines(text)!==normalizeNewlines(draft.text)||subject!==draft.subject;
  useEffect(()=>{try{const cached=JSON.parse(localStorage.getItem(key)||'null');if(cached){setText(cached.text);setSubject(cached.subject);}}catch{}setLoaded(true);},[key]);
  useEffect(()=>{if(loaded)localStorage.setItem(key,JSON.stringify({text,subject}));},[key,text,subject,loaded]);
  return <SaveForm action={editContactDraftAction} submit="Enregistrer cette version"><ContextFields company={company} campaign={campaign}/><input type="hidden" name="draftId" value={draft.id}/>{stale&&<p className="form-error">Ce brouillon doit être revalidé : vérifiez le motif, le dossier et votre offre avant de contacter.</p>}{draft.channel==='email'&&<div className="field"><label htmlFor={'draft-subject-'+draft.id}>Objet factuel</label><input name="subject" id={'draft-subject-'+draft.id} value={subject} onChange={e=>setSubject(e.target.value)} maxLength={300}/></div>}{draft.channel!=='email'&&<input type="hidden" name="subject" value={subject}/>}<div className="field"><label htmlFor={'draft-text-'+draft.id}>{draft.channel==='call'?'Trame d’appel':draft.channel==='followup'?'Relance sans réponse':draft.channel==='reply'?'Réponse préparée':'Email à relire'}</label><textarea className="draft-text" id={'draft-text-'+draft.id} name="text" value={text} onChange={e=>setText(e.target.value)} maxLength={12000} rows={10}/></div><button type="button" className="button secondary" disabled={stale||hasUnsavedChanges} onClick={async()=>{try{await navigator.clipboard.writeText((subject?subject+'\n\n':'')+text);setCopied('Texte copié.');}catch{setCopied('Sélectionnez le texte pour le copier.');}}}>Copier pour contacter manuellement</button><p role="status" className="small">{copied}</p>{!stale&&!hasUnsavedChanges&&draft.channel==='email'&&company.contact.email&&<a className="button secondary" href={'mailto:'+company.contact.email+'?subject='+encodeURIComponent(subject)+'&body='+encodeURIComponent(text)}>Ouvrir dans mon logiciel email</a>}{!stale&&!hasUnsavedChanges&&draft.channel==='call'&&company.contact.phone&&<a className="button secondary" href={'tel:'+company.contact.phone.replace(/[^+0-9]/g,'')}>Composer le numéro professionnel</a>}<p className="field-help">{hasUnsavedChanges&&<>Enregistrez cette version avant de la copier ou de l’utiliser. Le suivi conservera ainsi le texte effectivement utilisé.<br/></>}Version {draft.version} · {draft.origin==='openrouter'?'Rédaction assistée IA':draft.origin==='manual'?'Modification personnelle':'Trame déterministe'} · Une modification ici ne relance aucune recherche.</p></SaveForm>;
}
const callQuestions=[
  ['Ouverture','Bonjour, je suis [votre nom], [votre activité]. Est-ce que vous avez un court instant ?','Vérifier que le moment convient et identifier le bon interlocuteur.'],
  ['Motif et interlocuteur','Si nécessaire : êtes-vous la bonne personne pour parler de la présentation de vos prestations et des demandes reçues ?','Présenter le motif et son périmètre, puis identifier le bon interlocuteur.'],
  ['Fonctionnement','Comment recevez-vous les demandes aujourd’hui ?','Comprendre le fonctionnement avant de proposer une solution.'],
  ['Difficulté','Qu’est-ce qui vous complique le traitement de ces demandes, s’il y a quelque chose ?','Laisser la personne confirmer ou écarter la difficulté.'],
  ['Conséquence','Quand cela arrive, qu’est-ce que cela change concrètement pour vous ?','Documenter les conséquences vécues, sans les supposer.'],
  ['Résultat souhaité','Qu’aimeriez-vous simplifier en priorité ?','Faire préciser le résultat avant de définir une intervention.'],
];
export function CallGuide({plan,profile}:{plan:ApproachPlan;profile:ProviderProfile}){const [step,setStep]=useState(0),[branch,setBranch]=useState('');const [title,question,why]=callQuestions[step];return <div className="call-guide"><p className="eyebrow">APPEL · UNE QUESTION À LA FOIS</p><h4>{title}</h4>{step===1&&<div className="evidence-card"><p>{plan.motive}</p><p className="small muted">{plan.hypothesis}</p></div>}<p>{step===0?'Bonjour, je suis '+(profile.name||'[votre nom]')+', '+profile.activity+'. Est-ce que vous avez un court instant ?':step===2?plan.question:question}</p><p className="field-help">{why}</p><div className="button-row"><button className="button secondary" type="button" disabled={!step} onClick={()=>setStep(step-1)}>Précédente</button><button className="button secondary" type="button" disabled={step===callQuestions.length-1} onClick={()=>setStep(step+1)}>Question suivante</button></div><div className="field"><label htmlFor={'call-branch-'+plan.id}>Adapter à sa réponse</label><select id={'call-branch-'+plan.id} value={branch} onChange={e=>setBranch(e.target.value)}><option value="">Choisir la situation</option><option value="busy">Pas disponible</option><option value="taken">Déjà pris en charge</option><option value="later">Pas une priorité</option><option value="interest">Intéressé</option><option value="price">Demande un prix</option><option value="refusal">Refus</option></select></div>{branch&&<p role="status" className="data-notice">{({busy:'Demander un moment approprié ou terminer.',taken:'Demander s’il reste une difficulté. Sinon, clôturer.',later:'Noter cette information. Prévoir un suivi seulement si la personne le souhaite.',interest:'Reformuler ce qui a été dit, puis préciser le résultat recherché et les contraintes.',price:profile.prices?'Tarifs renseignés : '+profile.prices+'. Confirmer le périmètre avant un chiffrage.':'Préciser le périmètre avant de proposer un prix.',refusal:'Clôturer. En cas de demande de ne plus contacter, enregistrer une opposition commune.'} as Record<string,string>)[branch]}</p>}</div>;}
export function ContactOutcomeForm({company,campaign,today}:{company:CampaignCompany;campaign:Campaign;today:string;ready?:boolean}) {
  const [key,setKey]=useState(()=>crypto.randomUUID()),[followup,setFollowup]=useState(''),[mode,setMode]=useState('contact'),[state,dispatch,pending]=useActionState(recordContactAction,{});
  const [date,setDate]=useState(today),[channel,setChannel]=useState(company.readiness?.channelKind||'email'),[outcome,setOutcome]=useState('no_response'),[draftId,setDraftId]=useState(''),[note,setNote]=useState(''),[nextText,setNextText]=useState(''),[nextDate,setNextDate]=useState('');
  const sequence=suggestedContactSequence(company);
  const opposition=mode==='contact'&&outcome==='opposition';
  useEffect(()=>{if(state.ok){setKey(crypto.randomUUID());setFollowup('');setMode('contact');setDate(today);setChannel(company.readiness?.channelKind||'email');setOutcome('no_response');setDraftId('');setNote('');setNextText('');setNextDate('');}},[state,today,company.readiness?.channelKind]);
  return <form action={dispatch} onReset={e=>e.preventDefault()} className="stack" aria-busy={pending}><ContextFields company={company} campaign={campaign}/><input type="hidden" name="submittedKey" value={key}/><input type="hidden" name="completeActionId" value={company.nextAction?.id||''}/>
    <div className="data-notice"><strong>Votre séquence de contact</strong><p>{sequence.state==='not_started'?'J0, puis J+5 et J+12 si aucune réponse. Les dates seront proposées après le premier contact enregistré.':sequence.state==='stopped'?'Séquence arrêtée après une réponse, un refus ou une opposition.':sequence.state==='completed'?'Les deux relances suggérées sont terminées. Choisissez la suite explicitement.':sequence.steps.map(step=>step.label+' : '+step.date).join(' · ')}</p>{sequence.next&&<button type="button" className="button secondary" onClick={()=>{setFollowup('yes');setNextText(sequence.next!.label+' · contact manuel si toujours sans réponse');setNextDate(sequence.next!.date);}}>Utiliser la prochaine date suggérée</button>}</div>
    <p className="field-help">Ce formulaire enregistre une action ou un contact déjà réalisé. Il n’envoie aucun message et ne valide pas un futur contact.</p>
    {company.nextAction&&<><p className="data-notice">Action à terminer : {company.nextAction.text}</p><div className="field"><label htmlFor={'outcome-mode-'+company.id}>Ce que vous avez fait</label><select id={'outcome-mode-'+company.id} name="mode" value={mode} onChange={e=>setMode(e.target.value)}><option value="contact">Contact effectué</option><option value="action">Autre action réalisée</option></select></div></>}
    {!company.nextAction&&<input type="hidden" name="mode" value="contact"/>}
    <div className="form-grid"><div className="field"><label htmlFor={'contact-date-'+company.id}>Date de réalisation</label><input type="date" name="date" id={'contact-date-'+company.id} value={date} onChange={e=>setDate(e.target.value)} max={today} required/></div>{mode==='contact'&&<div className="field"><label htmlFor={'contact-channel-'+company.id}>Canal utilisé</label><select name="channel" id={'contact-channel-'+company.id} value={channel} onChange={e=>setChannel(e.target.value as 'email'|'phone')}><option value="email">Email</option><option value="phone">Appel</option></select></div>}</div>
    {mode==='contact'&&<><div className="field"><label htmlFor={'contact-result-'+company.id}>Résultat du contact</label><select name="outcome" id={'contact-result-'+company.id} value={outcome} onChange={e=>setOutcome(e.target.value)}><option value="no_response">Envoyé / pas de réponse</option><option value="conversation">Conversation réelle</option><option value="callback">Rappel convenu</option><option value="not_interested">Pas intéressé</option><option value="opposition">Ne plus contacter</option></select></div><div className="field"><label htmlFor={'used-draft-'+company.id}>Version utilisée</label><select name="draftId" id={'used-draft-'+company.id} value={draftId} onChange={e=>setDraftId(e.target.value)}><option value="">Contact sans brouillon Brine</option>{(company.drafts||[]).map(d=><option key={d.id} value={d.id}>{d.channel==='call'?'Appel':d.channel==='reply'?'Réponse':d.channel==='followup'?'Relance':'Email'} · version {d.version} · {d.createdAt}</option>)}</select></div></>}
    <div className="field"><label htmlFor={'contact-note-'+company.id}>Note et propos réellement exprimés</label><textarea name="note" id={'contact-note-'+company.id} value={note} onChange={e=>setNote(e.target.value)} maxLength={6000} placeholder="Reformulez ce qui a été dit. Indiquez si une hypothèse du dossier est contredite."/></div>
    {opposition?<><input type="hidden" name="followup" value="none"/><p className="data-notice">L’opposition sera appliquée à toutes les campagnes. Les actions prévues seront annulées ; aucun suivi de contact ne sera enregistré.</p></>:<><fieldset className="followup-choice"><legend>Quelle suite ?</legend><label className="check-label"><input name="followup" type="radio" value="yes" checked={followup==='yes'} onChange={()=>setFollowup('yes')} required/>Prévoir une prochaine action</label><label className="check-label"><input name="followup" type="radio" value="none" checked={followup==='none'} onChange={()=>setFollowup('none')}/>Aucun suivi prévu</label></fieldset>
    {followup==='yes'&&<div className="form-grid"><div className="field"><label htmlFor={'next-text-'+company.id}>Prochaine action</label><input id={'next-text-'+company.id} name="nextText" value={nextText} onChange={e=>setNextText(e.target.value)} maxLength={1000} required/></div><div className="field"><label htmlFor={'next-date-'+company.id}>Date choisie</label><input type="date" id={'next-date-'+company.id} name="nextDate" value={nextDate} onChange={e=>setNextDate(e.target.value)} required/></div></div>}</>}
    <button className="button primary" disabled={pending}>{pending?'Enregistrement…':'Enregistrer le résultat et la suite'}</button><Feedback state={state}/>
  </form>;
}
export function ContactWorkspace({company,campaign,report,profile,plan,aiAvailable,today,ready,missing,eligibleEvidence}:{company:CampaignCompany;campaign:Campaign;report:Report;profile:ProviderProfile;plan:ApproachPlan|null;aiAvailable:boolean;today:string;ready:boolean;missing:string[];eligibleEvidence:ResearchFact[]}) {
  const closed=company.oppositionActive||company.stage==='Perdu';
  const [tab,setTab]=useState(closed?'result':'plan');
  const [loaded,setLoaded]=useState(false),tabKey='brine-position-'+campaign.id+'-'+company.id;
  useEffect(()=>{const saved=localStorage.getItem(tabKey);if(closed)setTab('result');else if(saved&&['plan','email','call','result'].includes(saved))setTab(saved);setLoaded(true);},[tabKey,closed]);
  useEffect(()=>{if(loaded)localStorage.setItem(tabKey,tab);},[loaded,tab,tabKey]);
  const stale=(draft:ContactDraft)=>!ready||draft.reportId!==report.id||draft.planId!==company.plan?.id||draft.profileRevision!==profile.revision;
  const latest=(channel:ContactDraft['channel'])=>[...(company.drafts||[])].reverse().find(d=>d.channel===channel);
  return <div className="contact-workspace"><div className="section-title"><h2>{closed?'Conversation clôturée':'Préparer votre conversation'}</h2><span className="badge">{company.oppositionActive?'Ne plus contacter':closed?'Pas intéressé / suivi clôturé':ready?'Prêt à contacter':'À préparer'}</span></div><p>Un motif, une question, puis la suite selon la réponse. Vous effectuez le contact vous-même.</p><details open={!profile.activity} className="workspace-detail"><summary>{profile.activity?'Mon activité, mon offre et ma signature':'Renseigner mon activité avant de me présenter'}</summary><ProviderProfileForm profile={profile} compact/></details>{missing.length>0&&<p className="field-help">À confirmer : {missing.join(' · ')}</p>}
    <details className="workspace-detail" open={!company.contact.email&&!company.contact.phone}><summary>Vérifier ou compléter le contact professionnel</summary><ProfessionalContactForm company={company} campaign={campaign} report={report}/></details>
    <nav className="filter-tabs" aria-label="Préparation du contact">{[['plan','Motif et validation'],['email','Email'],['call','Appel'],['result','Résultat et suivi']].map(([key,label])=><button key={key} type="button" className={tab===key?'selected':''} onClick={()=>setTab(key)}>{label}</button>)}</nav>
    {tab==='plan'&&<PlanEditor key={company.id} eligibleEvidence={eligibleEvidence} company={company} campaign={campaign} report={report} profile={profile} plan={plan} aiAvailable={aiAvailable}/>}
    {['email','call'].includes(tab)&&<>{tab==='call'&&plan&&<CallGuide key={plan.id} plan={plan} profile={profile}/>} {latest(tab as 'email'|'call')?<DraftEditor key={latest(tab as 'email'|'call')!.id} company={company} campaign={campaign} draft={latest(tab as 'email'|'call')!} stale={stale(latest(tab as 'email'|'call')!)}/>:<p className="inline-empty">Construisez le plan et préparez les textes à l’étape précédente.</p>}</>}
    {tab==='result'&&<><ContactOutcomeForm key={company.id} company={company} campaign={campaign} today={today}/>{(company.contactEvents||[]).slice().reverse().map(event=><details key={event.id} className="workspace-detail"><summary>{event.date} · {event.outcome==='conversation'?'Conversation':event.outcome==='no_response'?'Sans réponse':event.outcome==='not_interested'?'Pas intéressé':event.outcome==='opposition'?'Ne plus contacter':event.outcome==='callback'?'Rappel convenu':'Contact enregistré'}</summary><p className="plain-text">{event.note||'Aucune note enregistrée.'}</p><p>{event.nextAction?'Suite : '+event.nextAction.text+' le '+event.nextAction.date:'Aucun suivi prévu.'}</p>{(['conversation','callback'].includes(event.outcome)||(event.outcome==='no_response'&&suggestedContactSequence(company).state==='active'))&&<SaveForm action={prepareContinuationAction} submit={event.outcome==='no_response'?'Préparer une relance manuelle facultative':'Préparer une réponse à partir de ces propos'}><ContextFields company={company} campaign={campaign}/><input type="hidden" name="eventId" value={event.id}/><input type="hidden" name="kind" value={event.outcome==='no_response'?'followup':'reply'}/></SaveForm>}</details>)}{latest('followup')&&<DraftEditor key={latest('followup')!.id} company={company} campaign={campaign} draft={latest('followup')!} stale={stale(latest('followup')!)}/>} {latest('reply')&&<DraftEditor key={latest('reply')!.id} company={company} campaign={campaign} draft={latest('reply')!} stale={stale(latest('reply')!)}/>}</>}
    <details className="workspace-detail"><summary>Corriger une information du dossier</summary><SaveForm action={correctReportFactAction} submit="Conserver la correction et signaler les brouillons"><ContextFields company={company} campaign={campaign}/><fieldset className="followup-choice"><legend>Ce qui est corrigé</legend><label className="check-label"><input type="radio" name="mode" value="fact" defaultChecked/>Le fait est inexact ou obsolète</label><label className="check-label"><input type="radio" name="mode" value="hypothesis"/>La conséquence supposée est réfutée, le fait reste vrai</label></fieldset><div className="field"><label htmlFor={'correction-fact-'+company.id}>Constat à corriger</label><select name="factId" id={'correction-fact-'+company.id} required defaultValue=""><option value="" disabled>Choisir une information</option>{report.facts.filter(f=>!f.corrected).map(f=><option key={f.id} value={f.id}>{f.text}</option>)}</select></div><div className="field"><label htmlFor={'correction-note-'+company.id}>Correction documentée et origine</label><textarea name="note" id={'correction-note-'+company.id} required maxLength={6000} placeholder="Indiquez la correction, ce qui a été confirmé ou réfuté et par qui."/></div></SaveForm></details>
    <details className="workspace-detail"><summary>Consulter le dossier et les preuves</summary><ProspectReport report={report} printHref={'/campagnes/rapports/'+company.id+'?campagne='+campaign.id}/></details>
    {(company.planHistory?.length||company.drafts?.length)?<details className="workspace-detail"><summary>Historique des plans et des messages</summary>{[...(company.planHistory||[]),...(company.plan?[company.plan]:[])].map((p,i)=><article className="evidence-card" key={p.id+'-'+i}><p className="eyebrow">{p.createdAt} · {p.method}</p><p>{p.motive}</p><p className="small muted">{p.hypothesis}<br/>{p.help}<br/>{p.question}<br/>{p.nextStep}</p><p className="small muted">Dossier {p.reportId} · Preuves {p.evidenceIds.join(', ')}</p></article>)}{(company.drafts||[]).map((d,i)=><details key={d.id+'-'+i}><summary>{d.channel} · version {d.version} · {d.usedAt?'utilisée le '+d.usedAt:'brouillon conservé'} · {d.createdAt}</summary><p className="plain-text">{d.subject}<br/>{d.text}</p></details>)}</details>:null}
  </div>;
}
