'use client';
import { useState } from 'react';
import type { ProspectReport as Report } from '@/lib/research-types';
const statusLabels={documented:'Documenté',partial:'Partiel',unverified:'Non vérifié',not_applicable:'Non applicable'};
const kindLabels={observed:'Observation directe',reported:'Information rapportée',hypothesis:'Hypothèse'};
export function PrintReportButton(){return <button className="button secondary print-hidden" type="button" onClick={()=>window.print()}>Imprimer / enregistrer en PDF</button>;}
export function ProspectReport({report,selectionName,selectedIds=[],printHref,expanded=false}:{report:Report;selectionName?:string;selectedIds?:string[];printHref?:string;expanded?:boolean}) {
  const [open,setOpen]=useState(expanded),[selected,setSelected]=useState(selectedIds);
  const toggle=(id:string)=>setSelected(old=>old.includes(id)?old.filter(x=>x!==id):[...old,id]);
  return <div className="prospect-report" data-testid="prospect-report"><div className="report-opening"><p className="eyebrow">DOSSIER · {report.facts.length} CONSTATS · {report.sources.length} SOURCES</p><p className="plain-text">{report.summary}</p><p className="small muted">Budget, besoin reconnu, priorité et décisionnaire restent inconnus sans information documentée.</p><div className="button-row print-hidden"><button type="button" className="button secondary" aria-expanded={open} onClick={()=>setOpen(!open)}>{open?'Replier le rapport':'Voir le rapport complet'}</button>{printHref&&<a className="button text-button" href={printHref} target="_blank" rel="noopener noreferrer">Export complet ↗</a>}</div></div>
    {selectionName&&report.facts.filter(f=>selected.includes(f.id)).map(f=><input key={f.id} type="hidden" name={selectionName} value={f.id}/>)}
    <div className={open?'report-full':'report-full report-folded'}>
      <nav aria-label="Parties du dossier" className="report-nav print-hidden">{report.sections.map(s=><a key={s.key} href={'#report-'+report.id+'-'+s.key}>{s.title}</a>)}</nav>
      {report.sections.map(section=><section key={section.key} id={'report-'+report.id+'-'+section.key} className="report-section"><div className="section-title"><h3>{section.title}</h3><span className="badge">{statusLabels[section.status]}</span></div>{section.notes.map((note,index)=><p className="small muted" key={index}>{note}</p>)}
        {report.facts.filter(f=>section.factIds.includes(f.id)).map(f=><article className={'evidence-card fact-'+f.sentiment} key={f.id} data-fact-id={f.id}><div className="fact-heading"><span className="eyebrow">{kindLabels[f.kind]}</span><span className="small muted">{f.observedOn}</span></div><p className="plain-text">{f.text}</p><p className="small muted">{f.scope}</p>{f.corrected&&<p className="form-error">Constat corrigé : ne plus utiliser la formulation précédente.</p>}
          {f.sourceIds.map(id=>{const source=report.sources.find(s=>s.id===id);return source?<a className="open-link small" key={id} href={source.url} target="_blank" rel="noopener noreferrer">{source.title} · {source.collectedAt} ↗</a>:<p key={id} className="small muted">Source inconnue : {id}</p>;})}
          {selectionName&&f.kind!=='hypothesis'&&!f.corrected&&<button type="button" className={'button small-button print-hidden '+(selected.includes(f.id)?'primary':'secondary')} onClick={()=>toggle(f.id)} aria-pressed={selected.includes(f.id)}>{selected.includes(f.id)?'Preuve sélectionnée':'Utiliser pour mon approche'}</button>}
        </article>)}
        {section.key==='presence'&&report.profiles.map(url=><p key={url}><a href={url} target="_blank" rel="noopener noreferrer">{url} ↗</a></p>)}
        {section.key==='contact'&&report.contacts.map((contact,i)=><p key={i}>{contact.kind==='formUrl'?'Formulaire repéré, non testé':contact.kind==='profileUrl'?'Profil public':contact.kind==='email'?'Email public':'Téléphone public'} : {contact.value} · <a href={contact.sourceUrl} target="_blank" rel="noopener noreferrer">Provenance ↗</a></p>)}
        {section.key==='visibility'&&report.panel&&<div className="panel-responses"><h4>Panel API — réponses conservées</h4><p className="field-help">Ces réponses API ne représentent pas les interfaces ChatGPT ou Claude. Une absence ne porte que sur cette question et cette réponse.</p>{report.panel.responses.map((r,i)=><details key={i}><summary>{r.question} · {r.valid?'Réponse valide':'Erreur'}</summary><p className="small muted">{r.model} · {r.engine} · {r.recordedAt}</p><p className="plain-text">{r.answer||r.error}</p>{r.sources.map(s=><p key={s.id}><a href={s.url} target="_blank" rel="noopener noreferrer">{s.title}</a></p>)}</details>)}</div>}
        {section.key==='method'&&<><h4>Couverture de la collecte</h4><ul>{report.coverage.map((item,i)=><li key={i}>{item}</li>)}</ul>{report.warnings.map((warning,i)=><p className="field-help" key={i}>{warning}</p>)}{report.narrative&&<><h4>Lecture assistée du dossier</h4><p className="plain-text">{report.narrative}</p></>}<h4>Toutes les sources et leurs extraits</h4><ol className="report-sources">{report.sources.map(s=><li key={s.id}><a href={s.url} target="_blank" rel="noopener noreferrer">{s.title}</a><p className="small muted">{s.provider} · {s.collectedAt}{s.query?' · Requête : '+s.query:''}</p><p className="plain-text small">{s.excerpt||'Aucun extrait conservé.'}</p></li>)}</ol></>}
      </section>)}
    </div>
  </div>;
}
