'use client';
import {useEffect,useState,type ReactNode} from 'react';
import Link from 'next/link';
import {useRouter} from 'next/navigation';
import Image from 'next/image';
import {FindingReview} from './qualification-enrichment';
import {useSessionChoice} from './use-session-choice';
import {isPublicVisualUrl} from '@/lib/visual-evidence';
import {reportDate} from './prospect-report';
import type {ProspectReport} from '@/lib/research-types';
import {UI_LABELS} from '@/lib/labels';
export function SiteQualificationWorkspace({report,website,candidateId,revision,studyHref,observations,qualification,afterExchange,contactEditor}:{report:ProspectReport;website:string;candidateId:string;revision:number;studyHref:string;observations:ReactNode;qualification:ReactNode;afterExchange?:ReactNode;contactEditor?:ReactNode}){
 const router=useRouter();
 const [tab,setTab]=useSessionChoice(studyHref+':space',['observations','qualification',...(afterExchange?['exchange' as const]:[]),...(contactEditor?['contact' as const]:[])] as const,'observations');
 const [mode,setMode]=useSessionChoice(studyHref+':viewer',['capture','site'] as const,'capture');
 const [surface,setSurface]=useState<'work'|'site'>('work'),[embed,setEmbed]=useState(false),[selected,setSelected]=useState(report.facts.find(f=>f.visual)?.id||''),[proofOpen,setProofOpen]=useState(false);
 const safeWebsite=isPublicVisualUrl(website)?website:'';
 const fact=report.facts.find(f=>f.id===selected),visual=fact?.visual,image=visual?.assetId?'/api/research-assets/'+visual.assetId:visual?.screenshot;
 useEffect(()=>{const reveal=(event?:Event)=>{const value=event instanceof CustomEvent?String(event.detail):location.hash;if(value.includes('criterion-')||value.includes('answers.'))setTab('qualification');else if(value.includes('observation')||value.includes('items.'))setTab('observations');else if(value.includes('exchange'))setTab('exchange');else if(value.includes('contact-heading'))setTab('contact');setProofOpen(false);setSurface('work');if(value.startsWith('#'))requestAnimationFrame(()=>document.getElementById(value.slice(1))?.scrollIntoView({block:'start'}));};const proof=(e:Event)=>{setSelected(String((e as CustomEvent).detail));setProofOpen(true);setMode('capture');setSurface('site');};reveal();window.addEventListener('hashchange',reveal);window.addEventListener('brine:qualification-focus',reveal);window.addEventListener('brine:view-proof',proof);return()=>{window.removeEventListener('hashchange',reveal);window.removeEventListener('brine:qualification-focus',reveal);window.removeEventListener('brine:view-proof',proof);};},[]);
 const returnToControl=()=>{setProofOpen(false);setSurface('work');requestAnimationFrame(()=>{const area=document.querySelector<HTMLElement>(`.qualification-active-work ${tab==='observations'?'.observations-block':tab==='qualification'?'.qualification-block':tab==='contact'?'.company-form':'.after-exchange-block'}`);const target=area?.querySelector<HTMLElement>('.compact-control-select')||area;target?.scrollIntoView({block:'start'});target?.querySelector<HTMLElement>('select,input,textarea')?.focus({preventScroll:true});});};
 return <div className="site-qualification-shell"><div className="site-work-toggle" aria-label="Vue de travail"><button className="button secondary" aria-pressed={surface==='work'} onClick={()=>setSurface('work')}>{UI_LABELS.steps.qualify}</button><button className="button secondary" aria-pressed={surface==='site'} onClick={()=>setSurface('site')}>Site et {UI_LABELS.evidence.proofs.toLocaleLowerCase('fr')}</button></div><div className="site-qualification-grid" data-surface={surface}>
 <aside className="qualification-viewer" aria-label={`Site et ${UI_LABELS.evidence.proofs.toLocaleLowerCase('fr')}`}><div className="button-row"><button className="button secondary" aria-pressed={mode==='capture'} onClick={()=>setMode('capture')}>Capture conservée</button><button className="button secondary" aria-pressed={mode==='site'} onClick={()=>setMode('site')}>Site navigable</button></div>
 {mode==='capture'?<><label className="field">{UI_LABELS.evidence.proof} à consulter<select value={selected} onChange={e=>{setSelected(e.target.value);setProofOpen(true);}}><option value="">Choisir une {UI_LABELS.evidence.proof.toLocaleLowerCase('fr')}</option>{report.facts.map(f=><option key={f.id} value={f.id}>{f.corrected?'Ancien relevé corrigé · ':f.review?.state==='rejected'?'Rejeté · ':''}{f.visual?'Capture · ':''}{f.text.slice(0,100)}</option>)}</select></label>{fact&&<p className="field-help">{visual?.element||`${UI_LABELS.evidence.finding} enregistré`} · {reportDate(fact.observedOn)}{visual?.viewport&&` · ${visual.device} ${visual.viewport.width} × ${visual.viewport.height} px`}</p>}{image?<Image className="qualification-viewer-image" src={image} alt={visual?.element||'Capture conservée'} width={visual?.viewport?.width||1280} height={visual?.viewport?.height||900} unoptimized/>:<p className="viewer-empty">{fact?`Ce ${UI_LABELS.evidence.finding.toLocaleLowerCase('fr')} comporte une source écrite, sans capture conservée.`:`Aucune capture sélectionnée. Choisissez une ${UI_LABELS.evidence.proof.toLocaleLowerCase('fr')} ou ouvrez le site.`}</p>}{visual?.pageUrl&&<a className="open-link" href={visual.pageUrl} target="_blank" rel="noopener noreferrer">Ouvrir la page source ↗</a>}<p className="field-help">Une capture figée décrit un écran et une date précis ; elle n’est pas le site actuel.</p></>:<>{safeWebsite?<><a className="open-link" href={website} target="_blank" rel="noopener noreferrer">Ouvrir le site ↗</a><p className="field-help">Adresse ouverte : {website}</p>{embed?<iframe src={safeWebsite} title={`Site public du ${UI_LABELS.entities.prospect.toLocaleLowerCase('fr')}`} sandbox="allow-scripts allow-same-origin allow-forms allow-popups" referrerPolicy="no-referrer" loading="lazy"/>:<button className="button secondary" onClick={()=>setEmbed(true)}>Afficher le site dans ce panneau</button>}<p className="field-help">Le site peut refuser cet affichage. Ouvrez-le dans un onglet ou revenez aux captures. Brine ne lit pas sa navigation interne ; la largeur du panneau ne simule pas un téléphone. Aucun formulaire n’est testé automatiquement.</p></>:<p className="viewer-empty">Site non identifié. Les informations et {UI_LABELS.evidence.proofs.toLocaleLowerCase('fr')} du dossier restent disponibles.</p>}</>}
 {fact&&<button className="button secondary" onClick={()=>{setProofOpen(true);setSurface('work');}}>Voir le {UI_LABELS.evidence.finding.toLocaleLowerCase('fr')} et le confirmer</button>}<button className="button text-button viewer-return" onClick={returnToControl}>Revenir au {UI_LABELS.evidence.finding.toLocaleLowerCase('fr')}</button>
 </aside>
 <section className="qualification-active-work" aria-label="Travail de qualification"><div className="workspace-space-select-group"><label className="field workspace-space-select">Espace de travail<select value={tab} onChange={e=>{if(e.target.value==='ia'){router.push(studyHref);return;}setTab(e.target.value as typeof tab);setProofOpen(false);}}><option value="observations">Site et présence · 9 {UI_LABELS.evidence.findings.toLocaleLowerCase('fr')}</option><option value="qualification">Qualification · 5 critères</option><option value="ia">{UI_LABELS.aiVisibility}</option>{contactEditor&&<option value="contact">Coordonnées</option>}{afterExchange&&<option value="exchange">Après l’échange</option>}</select></label><Link className="button secondary" href={studyHref}>{UI_LABELS.aiVisibility}</Link></div><nav className="qualification-spaces" aria-label="Espaces de qualification"><button type="button" aria-pressed={tab==='observations'} onClick={()=>{setTab('observations');setProofOpen(false);}}>Site et présence<small>9 {UI_LABELS.evidence.findings.toLocaleLowerCase('fr')}</small></button><button type="button" aria-pressed={tab==='qualification'} onClick={()=>{setTab('qualification');setProofOpen(false);}}>Qualification<small>5 critères</small></button><Link href={studyHref}>{UI_LABELS.aiVisibility}</Link>{contactEditor&&<button type="button" aria-pressed={tab==='contact'} onClick={()=>{setTab('contact');setProofOpen(false);}}>Coordonnées</button>}{afterExchange&&<button type="button" aria-pressed={tab==='exchange'} onClick={()=>{setTab('exchange');setProofOpen(false);}}>Après l’échange</button>}</nav>
 <div hidden={proofOpen}><div hidden={tab!=='observations'}>{observations}</div><div hidden={tab!=='qualification'}>{qualification}</div><div hidden={tab!=='exchange'}>{afterExchange}</div><div hidden={tab!=='contact'}>{contactEditor}</div></div>
 {proofOpen&&fact&&<section className="qualification-proof-detail"><button className="button secondary" onClick={returnToControl}>Revenir au {UI_LABELS.evidence.finding.toLocaleLowerCase('fr')}</button><FindingReview fact={fact} report={report} candidateId={candidateId} revision={revision} hideVisual readOnly={!candidateId}/></section>}
 </section></div></div>;
}
