import Link from 'next/link';
import { notFound } from 'next/navigation';
import { requireAuthenticated } from '@/lib/auth';
import { getCampaignRepository } from '@/lib/campaign-runtime';
import { CampaignQualificationList, type QualificationListItem, type QualificationFilter } from '@/components/campaign-qualification-list';
import { WorkflowSteps } from '@/components/workflow-steps';
import { CandidateQualification } from '@/components/candidate-qualification';
import { ProspectReview } from '@/components/prospect-review';
import { VisualObservationForm } from '@/components/visual-observation-form';
import { CampaignOfferForm } from '@/components/campaign-offer-form';
import { CampaignMutation, RunRefresh } from '@/components/campaign-forms';
import { confirmWebsiteAction } from '@/app/campaign-actions';
import { evaluateQualification } from '@/lib/qualification';
import { parisToday } from '@/lib/domain';
import { buildProspectInsights } from '@/lib/prospect-insights';
import { getEligibleApproachEvidence } from '@/lib/contact-preparation';
import { listCandidateContacts } from '@/lib/research-report';
import { qualificationListFindings } from '@/lib/qualification-enrichment';
export default async function QualificationPage({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{candidat?:string;filtre?:QualificationFilter;decision?:string}>}){
  await requireAuthenticated();const {id}=await params,query=await searchParams,repo=await getCampaignRepository();
  const [campaign,profile,candidates,companies,runs]=await Promise.all([repo.getCampaign(id),repo.getProviderProfile(),repo.listCampaignCandidates(id),repo.listCompanies(id),repo.listRuns(id)]),today=parisToday();
  const active=runs.some(run=>['queued','running'].includes(run.status));
  const contexts=await Promise.all(candidates.map(candidate=>repo.getQualificationContext(candidate.id)));
  const items:QualificationListItem[]=contexts.map(context=>({id:context.candidate.id,href:`/campagnes/${id}/qualification?candidat=${context.candidate.id}`,name:context.company.name,city:context.company.city,business:context.company.business,website:context.company.website,status:context.company.archived?'verify':['accepted','verify','rejected'].includes(context.candidate.status)?context.candidate.status as QualificationFilter:'review',evaluation:evaluateQualification(context.company,campaign,today),findings:qualificationListFindings(context.report),contact:context.company.contact.email||context.company.contact.phone||'À trouver'}));
  const seen=new Set(contexts.map(context=>context.candidate.companyId).filter(Boolean));
  for(const company of companies.filter(company=>!seen.has(company.id))){const report=await repo.getCompanyReport(id,company.id);items.push({id:company.id,href:`/prospects/${company.id}?campagne=${id}`,name:company.name,city:company.city,business:company.business,website:company.website,status:company.archived?'verify':'accepted',evaluation:evaluateQualification(company,campaign,today),findings:report?qualificationListFindings(report):[],contact:company.contact.email||company.contact.phone||'À trouver'});}
  const context=query.candidat?contexts.find(context=>context.candidate.id===query.candidat):null;if(query.candidat&&!context)notFound();
  return <><Link href="/campagnes" className="back-link">← Campagnes</Link><div className="page-heading"><div><p className="eyebrow">{campaign.name}</p><h1>{context?context.company.name:'Qualifier mes entreprises'}</h1><p className="page-subtitle">{context?`${context.company.business} · ${context.company.city}`:'Vos critères, les constats à vérifier et la prochaine décision.'}</p></div><Link className="button secondary" href={`/campagnes/${id}?etape=rechercher`}>Lancer une recherche</Link></div><WorkflowSteps campaignId={id} active="examiner"/>{active&&<RunRefresh active/>}
    {query.decision&&<p className="form-success" role="status">{query.decision==='accept'?'Prospect validé. La qualification et les preuves sont conservées.':query.decision==='verify'?'Entreprise conservée pour plus tard.':'Entreprise écartée ; son dossier reste accessible.'}</p>}
    {!context?<CampaignQualificationList items={items} campaignId={id} initialFilter={query.filtre}/>:<><Link className="back-link" href={`/campagnes/${id}/qualification`}>← Toutes les entreprises de cette campagne</Link>{['queued','processing'].includes(context.candidate.status)&&<p className="data-notice">Analyse en cours. Vos saisies restent conservées.</p>}{context.candidate.status==='needs_site'&&<details className="panel section-panel" open><summary>Confirmer le site avant analyse</summary><CampaignMutation action={confirmWebsiteAction} submit="Confirmer le site et analyser" secondary><input type="hidden" name="candidateId" value={context.candidate.id}/><input type="hidden" name="revision" value={context.candidate.revision}/><label className="field">Site officiel<input type="url" name="website" required defaultValue={context.candidate.website||context.candidate.websites[0]?.url||''}/></label><p className="field-help">Un site non identifié ne prouve pas qu’il n’en existe pas.</p></CampaignMutation></details>}<section className="panel section-panel"><ProspectReview decisionReturnTo={`/campagnes/${id}/qualification`} candidateId={context.candidate.id} revision={context.candidate.revision} campaignId={id} report={context.report} insights={buildProspectInsights(context.report,campaign,profile,{name:context.company.name,website:context.company.website,business:context.company.business,city:context.company.city})} contacts={listCandidateContacts(context.candidate)} selectedIds={context.company.findingIds.filter(f=>f.startsWith(context.candidate.id+':')).map(f=>f.slice(context.candidate.id.length+1))} selectedContactIndexes={listCandidateContacts(context.candidate).flatMap((contact,index)=>context.company.contact[contact.kind]===contact.value?[index]:[])} eligibleIds={getEligibleApproachEvidence(context.report,campaign,profile).map(f=>f.id)} initialApproach={context.company.approach} prepareHref={context.candidate.companyId?`/campagnes/${id}?etape=preparer&prospect=${context.candidate.companyId}`:undefined} companyHref={context.candidate.companyId?`/prospects/${context.candidate.companyId}?campagne=${id}`:undefined} savedContactValues={context.company.candidateId?undefined:context.company.contact} retained={context.candidate.status==='accepted'} archived={context.company.archived} canReview={!['queued','processing'].includes(context.candidate.status)} qualification={<CandidateQualification context={context}/>} offerEditor={<CampaignOfferForm campaign={campaign}/>} visualObservation={<VisualObservationForm candidateId={context.candidate.id} revision={context.candidate.revision} pageUrl={context.candidate.website}/>}/></section></>}
  </>;
}
