import Link from 'next/link';
import { notFound } from 'next/navigation';
import { requireAuthenticated } from '@/lib/auth';
import { getCampaignRepository } from '@/lib/campaign-runtime';
import { CampaignQualificationList, type QualificationListItem, type QualificationFilter } from '@/components/campaign-qualification-list';
import { WorkflowSteps } from '@/components/workflow-steps';
import { LearningGuide } from '@/components/learning-guide';
import { learningModuleIdSchema } from '@/lib/learning-schema';
import { CandidateQualification } from '@/components/candidate-qualification';
import { ProspectReview } from '@/components/prospect-review';
import { VisualObservationForm } from '@/components/visual-observation-form';
import { CampaignOfferForm } from '@/components/campaign-offer-form';
import { CampaignMutation, RunRefresh } from '@/components/campaign-forms';
import { confirmWebsiteAction } from '@/app/campaign-actions';
import { evaluateQualification } from '@/lib/qualification';
import { parisToday } from '@/lib/domain';
import { buildProspectInsights } from '@/lib/prospect-insights';
import { getEligibleApproachEvidence } from '@/lib/contact-preparation';
import { listCandidateContacts } from '@/lib/research-report';
import { qualificationListFindings } from '@/lib/qualification-enrichment';
import { UI_LABELS } from '@/lib/labels';
export default async function QualificationPage({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{candidat?:string;filtre?:QualificationFilter;decision?:string;guide?:string}>}){
  await requireAuthenticated();const {id}=await params,query=await searchParams,repo=await getCampaignRepository();
  const [campaign,profile,candidates,companies,runs,learning]=await Promise.all([repo.getCampaign(id),repo.getProviderProfile(),repo.listCampaignCandidates(id),query.candidat?Promise.resolve([]):repo.listCompanies(id),repo.listRuns(id),repo.getLearningProgress()]),today=parisToday();
  const active=runs.some(run=>['queued','running'].includes(run.status));
  if(query.candidat&&!candidates.some(candidate=>candidate.id===query.candidat))notFound();
  const contexts=query.candidat?[await repo.getQualificationContext(query.candidat)]:await repo.getQualificationContexts(candidates.map(candidate=>candidate.id));
  const items:QualificationListItem[]=contexts.map(context=>({id:context.candidate.id,href:`/campagnes/${id}/qualification?candidat=${context.candidate.id}`,name:context.company.name,city:context.company.city,business:context.company.business,website:context.company.website,status:context.company.archived?'verify':['accepted','verify','rejected'].includes(context.candidate.status)?context.candidate.status as QualificationFilter:'review',evaluation:evaluateQualification(context.company,campaign,today),findings:qualificationListFindings(context.report),contact:context.company.contact.email||context.company.contact.phone||'À trouver'}));
  const seen=new Set(contexts.map(context=>context.candidate.companyId).filter(Boolean));
  const additionalCompanies=companies.filter(company=>!seen.has(company.id)),companyReports=await repo.getCompanyReports(id,additionalCompanies.map(company=>company.id));
  for(const company of additionalCompanies){const report=companyReports.get(company.id);items.push({id:company.id,href:`/prospects/${company.id}?campagne=${id}`,name:company.name,city:company.city,business:company.business,website:company.website,status:company.archived?'verify':'accepted',evaluation:evaluateQualification(company,campaign,today),findings:report?qualificationListFindings(report):[],contact:company.contact.email||company.contact.phone||'À trouver'});}
  const context=query.candidat?contexts.find(context=>context.candidate.id===query.candidat):null;if(query.candidat&&!context)notFound();
  return <div className={context?"qualification-page":undefined}><Link href={context?`/campagnes/${id}/qualification`:"/campagnes"} className="back-link">← {context?`${campaign.name} · ${context.candidate.status==='accepted'?UI_LABELS.entities.prospects.toLocaleLowerCase('fr'):UI_LABELS.entities.companies.toLocaleLowerCase('fr')}`:"Campagnes"}</Link><div className="page-heading"><div><p className="eyebrow">{campaign.name}</p><h1>{context?context.company.name:`${UI_LABELS.steps.qualify} les ${UI_LABELS.entities.companies.toLocaleLowerCase('fr')}`}</h1><p className="page-subtitle">{context?`${context.company.business} · ${context.company.city}`:`Vos critères, les ${UI_LABELS.evidence.findings.toLocaleLowerCase('fr')} à vérifier et la qualification.`}</p></div>{context?<a className="button secondary" href={context.candidate.status==='accepted'&&context.candidate.companyId?context.company.oppositionActive||context.company.stage==='Perdu'?`/prospects/${context.candidate.companyId}?campagne=${id}#contact`:`/campagnes/${id}?etape=preparer&prospect=${context.candidate.companyId}`:`#review-decision-${context.candidate.id}`}>{context.candidate.status==='accepted'?context.company.oppositionActive||context.company.stage==='Perdu'?'Consulter le suivi':UI_LABELS.steps.contact:UI_LABELS.steps.qualify}</a>:<Link className="button secondary" href={`/campagnes/${id}?etape=rechercher`}>{UI_LABELS.steps.search}</Link>}</div><WorkflowSteps campaignId={id} active="examiner"/>{active&&<RunRefresh active/>}
    <div className={context?"learning-workspace qualification-focused":"learning-workspace"}><div className="learning-workspace-main">
    {query.decision&&<p className="form-success" role="status">{query.decision==='accept'?`${UI_LABELS.entities.prospect} validé. La qualification et les ${UI_LABELS.evidence.proofs.toLocaleLowerCase('fr')} sont conservées.`:query.decision==='verify'?`${UI_LABELS.entities.company} conservée pour plus tard.`:`${UI_LABELS.entities.company} écartée ; son dossier reste accessible.`}</p>}
    {!context?<CampaignQualificationList items={items} campaignId={id} initialFilter={query.filtre}/>:<>{['queued','processing'].includes(context.candidate.status)&&<p className="data-notice">Analyse en cours. Vos saisies restent conservées.</p>}{context.candidate.status==='needs_site'&&<details className="panel section-panel" open><summary>Confirmer le site avant analyse</summary><CampaignMutation action={confirmWebsiteAction} submit="Confirmer le site et analyser" secondary><input type="hidden" name="candidateId" value={context.candidate.id}/><input type="hidden" name="revision" value={context.candidate.revision}/><label className="field">Site officiel<input type="url" name="website" required defaultValue={context.candidate.website||context.candidate.websites[0]?.url||''}/></label><p className="field-help">Un site non identifié ne prouve pas qu’il n’en existe pas.</p></CampaignMutation></details>}<section className="panel section-panel"><ProspectReview decisionReturnTo={`/campagnes/${id}/qualification`} candidateId={context.candidate.id} revision={context.candidate.revision} campaignId={id} report={context.report} insights={buildProspectInsights(context.report,campaign,profile,{name:context.company.name,website:context.company.website,business:context.company.business,city:context.company.city})} contacts={listCandidateContacts(context.candidate)} selectedIds={context.company.findingIds.filter(f=>f.startsWith(context.candidate.id+':')).map(f=>f.slice(context.candidate.id.length+1))} selectedContactIndexes={listCandidateContacts(context.candidate).flatMap((contact,index)=>context.company.contact[contact.kind]===contact.value?[index]:[])} eligibleIds={getEligibleApproachEvidence(context.report,campaign,profile).map(f=>f.id)} initialApproach={context.company.approach} prepareHref={context.candidate.companyId?`/campagnes/${id}?etape=preparer&prospect=${context.candidate.companyId}`:undefined} companyHref={context.candidate.companyId?`/prospects/${context.candidate.companyId}?campagne=${id}`:undefined} savedContactValues={context.company.candidateId?undefined:context.company.contact} retained={context.candidate.status==='accepted'} archived={context.company.archived} canReview={!['queued','processing'].includes(context.candidate.status)} qualification={<CandidateQualification context={context}/>} offerEditor={<CampaignOfferForm campaign={campaign}/>} visualObservation={<VisualObservationForm candidateId={context.candidate.id} revision={context.candidate.revision} pageUrl={context.candidate.website}/>}/></section></>}
    </div><LearningGuide progress={learning} moduleId={learningModuleIdSchema.safeParse(query.guide).data||'qualification'} campaignId={id}/></div>
  </div>;
}
