import {test,expect,type APIRequestContext} from '@playwright/test';
import type {Backup} from '../lib/types';
const read=async(request:APIRequestContext):Promise<Backup>=>(await request.get('/api/backup')).json();
for(const width of [1280,390])test(`étude IA indépendante, comparaison, preuve choisie et relevé manuel à ${width}px`,async({page,request})=>{
 test.setTimeout(120000);await page.setViewportSize({width,height:900});await page.goto('/prospects');await page.getByRole('button',{name:'Ajouter un prospect',exact:true}).first().click();const dialog=page.getByRole('dialog');await dialog.getByLabel('Nom du prospect',{exact:false}).fill(`Atelier IA fictif ${width}`);await dialog.getByLabel('Site web',{exact:true}).fill(`https://atelier-ia-${width}.example`);await dialog.getByRole('button',{name:'Créer le prospect',exact:true}).click();await expect(page).toHaveURL(/created=1/);const companyId=new URL(page.url()).pathname.split('/').at(-1)!;
 const before=await read(request),href=`/campagnes/initial/visibilite-ia?prospect=${companyId}`;await page.goto(href);const preparation=page.getByTestId('study-preparation');await expect(preparation).toContainText('2 questions × 3 répétitions = 6 essais');await preparation.getByRole('textbox',{name:'Question exacte',exact:true}).fill('Quels ateliers de rénovation recommander à Montpellier ?');await preparation.getByLabel('Mot-clé ou métier',{exact:true}).fill('rénovation');await page.reload();await expect(preparation.getByRole('textbox',{name:'Question exacte',exact:true})).toHaveValue('Quels ateliers de rénovation recommander à Montpellier ?');await preparation.getByRole('checkbox',{name:/J’ai vérifié les questions/}).check();await preparation.getByRole('button',{name:'Enregistrer ce plan d’étude',exact:true}).click();await expect(page).toHaveURL(/etude=/);const id=new URL(page.url()).searchParams.get('etude')!;
 await page.getByRole('button',{name:'Lancer les essais',exact:true}).click();await page.goto('/campagnes');await expect.poll(async()=>(await read(request)).campaignData!.aiStudies!.find(s=>s.id===id)!.status,{timeout:45000}).toBe('completed');await page.goto(href+'&etude='+id);const table=page.locator('.study-comparison');await expect(table.locator('tbody tr')).toHaveCount(2);await expect(table.locator('tbody tr').first()).toContainText('2/3');await expect(table.locator('tbody tr').last()).toContainText('1/2');await expect(table.locator('tbody tr').last()).toContainText('1 erreur(s)');await expect(page.getByRole('button',{name:'Lancer les essais',exact:true})).toHaveCount(0);
 await page.locator('.study-trials > li').first().locator('summary').first().click();await expect(page.locator('.study-trials')).toContainText('Conversation indépendante');await page.getByRole('button',{name:'Utiliser ce constat pour mon approche',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'Constat retenu dans le dossier'})).toBeVisible();const saved=await read(request),study=saved.campaignData!.aiStudies!.find(s=>s.id===id)!;expect(study.trials).toHaveLength(6);expect(new Set(study.trials.map(t=>t.id)).size).toBe(6);expect(study.trials.filter(t=>t.status==='error')).toHaveLength(1);expect(study.evidence).toHaveLength(1);expect(saved.campaignData!.participations).toEqual(before.campaignData!.participations);expect(saved.activities).toEqual(before.activities);
 await page.getByRole('link',{name:'Préparer une nouvelle étude',exact:true}).click();await preparation.getByLabel('Canal',{exact:true}).selectOption('claude-app');await preparation.getByLabel('Répétitions par question',{exact:true}).selectOption('1');await preparation.getByRole('checkbox',{name:/J’ai vérifié les questions/}).check();await preparation.getByRole('button',{name:'Enregistrer ce plan d’étude',exact:true}).click();await expect(page).toHaveURL(/etude=/);const manualId=new URL(page.url()).searchParams.get('etude')!;expect(manualId).not.toBe(id);await expect(page.locator('body')).toContainText('Un seul essai par question');await page.locator('.study-trials > li').first().locator('summary').first().click();await page.getByText('Saisir cette réponse et sa preuve',{exact:true}).first().click();await page.getByRole('textbox',{name:'Réponse brute',exact:true}).fill('Autre Atelier est recommandé dans cette conversation réelle du jeu de test.');await page.getByLabel('Lien de preuve de cet essai',{exact:true}).fill('https://claude.ai/share/jeu-fictif');await page.getByLabel('Mention de l’entreprise',{exact:true}).selectOption('false');await page.getByLabel('Recommandation pour la demande',{exact:true}).selectOption('false');await page.getByRole('checkbox',{name:/J’ai vérifié l’identité et la classification/}).check();await page.getByRole('button',{name:'Enregistrer cet essai',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'Essai enregistré.'})).toBeVisible();const manual=(await read(request)).campaignData!.aiStudies!.find(s=>s.id===manualId)!;expect(manual.channel).toBe('claude-app');expect(manual.trials[0].answer).toContain('jeu de test');expect(manual.trials[0].citation).toBeNull();expect(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)).toBe(false);await page.screenshot({path:`test-results/v25-study-${width}.png`,fullPage:true});
});
