import { test,expect } from '@playwright/test';
import type { Backup } from '../lib/types';

test('campagne, lot persistant, revue, entreprise commune et suivi indépendant sur mobile',async({page,request})=>{
  test.setTimeout(120000);
  const baseline:Backup=await(await request.get('/api/backup')).json();
  try{
    await page.goto('/campagnes');await page.getByRole('link',{name:'Créer une campagne',exact:true}).click();
    await page.getByLabel('Nom de la campagne',{exact:true}).fill('Campagne navigateur — devis');await page.getByLabel('Commune',{exact:true}).fill('Lyon');await page.getByLabel('Activité recherchée',{exact:true}).fill('Électricité');await page.getByLabel('Codes d’activité NAF',{exact:true}).fill('43.21A');await page.getByLabel('Offre proposée',{exact:true}).fill('Améliorer les demandes de devis');await page.getByRole('button',{name:'Créer la campagne',exact:true}).click();
    await expect(page.getByRole('heading',{name:'Campagne navigateur — devis',exact:true})).toBeVisible();const campaignId=new URL(page.url()).pathname.split('/').at(-1)!;
    await page.getByRole('button',{name:'Lancer la recherche et l’analyse',exact:true}).click();await expect(page).toHaveURL(/\/campagnes\/lots\//);const runUrl=page.url(),runId=new URL(runUrl).pathname.split('/').at(-1)!;
    // Navigate away: the real compiled Workflow SDK continues without page polling.
    await page.goto('/campagnes');await expect.poll(async()=>{const data=await(await request.get(`/api/campaign-runs/${runId}`)).json();return data.run.status;},{timeout:45000}).toBe('completed');
    await page.goto(runUrl);await expect(page.getByRole('heading',{name:'Votre lot de recherche',exact:true})).toBeVisible();await expect(page.getByText('PageSpeed indisponible : configuration de test.',{exact:false})).toBeVisible();
    await page.screenshot({path:'test-results/campaign-review-desktop.png',fullPage:true});
    await page.getByRole('checkbox',{name:'Le lien Demander un devis renvoie HTTP 404.',exact:true}).check();await page.getByRole('checkbox',{name:/contact@atelier-demo.test/}).check();await page.getByRole('button',{name:'Retenir dans la campagne',exact:true}).click();await page.getByRole('link',{name:/Ouvrir la fiche prospect/}).click();
    await expect(page.getByText(`Suivi : Campagne navigateur — devis`,{exact:true})).toBeVisible();await expect(page.getByLabel('Email professionnel',{exact:true})).toHaveValue('contact@atelier-demo.test');await expect(page.getByTestId('qualification-summary')).toContainText('Non évalué');
    const companyId=new URL(page.url()).pathname.split('/').at(-1)!;await page.getByRole('button',{name:'Reprendre le constat retenu comme preuve',exact:true}).click();await expect(page.getByTestId('qualification-form').locator('input[name="payload"]')).toHaveValue(/HTTP 404/);
    await page.goto(`/campagnes/${campaignId}`);await page.getByRole('button',{name:'Dupliquer la configuration',exact:true}).click();await expect(page.getByRole('heading',{name:'Campagne navigateur — devis — copie',exact:true})).toBeVisible();const copyId=new URL(page.url()).pathname.split('/').at(-1)!;
    await page.getByText('Rattacher une entreprise déjà connue',{exact:true}).click();await page.getByLabel('Entreprise',{exact:true}).selectOption(companyId);await page.getByRole('button',{name:'Rattacher à cette campagne',exact:true}).click();
    await page.goto(`/prospects/${companyId}?campagne=${copyId}`);await expect(page.getByLabel('Email professionnel',{exact:true})).toHaveValue('contact@atelier-demo.test');await expect(page.getByLabel('Angle d’approche',{exact:true})).toHaveValue('');
    await page.getByRole('button',{name:'Prévoir la suite',exact:true}).first().click();const dialog=page.getByRole('dialog');await dialog.getByLabel(/^Action(?:\s|$)/).fill('Appeler pour la deuxième offre');await dialog.getByRole('button',{name:'Enregistrer l’action',exact:true}).click();await expect(dialog.getByRole('status')).toContainText('Prochaine action enregistrée.');await dialog.getByRole('button',{name:'Fermer',exact:true}).click();
    const backup:Backup=await(await request.get('/api/backup')).json();expect(backup.companies.filter(c=>c.id===companyId)).toHaveLength(1);expect(backup.campaignData!.participations.find(p=>p.companyId===companyId&&p.campaignId===campaignId)!.nextAction).toBeNull();expect(backup.campaignData!.participations.find(p=>p.companyId===companyId&&p.campaignId===copyId)!.nextAction!.text).toBe('Appeler pour la deuxième offre');
    await page.setViewportSize({width:390,height:844});await page.goto('/campagnes');expect(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)).toBe(false);await page.screenshot({path:'test-results/campaigns-mobile.png',fullPage:true});await page.goto(runUrl+'?filtre=complete');await page.getByRole('link',{name:/Artisan — site à confirmer/}).click();await expect(page.getByLabel('Site officiel',{exact:true})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)).toBe(false);await page.screenshot({path:'test-results/campaign-review-mobile.png',fullPage:true});
  }finally{
    await page.goto('/sauvegarde');await page.getByLabel('Fichier de sauvegarde JSON',{exact:true}).setInputFiles({name:'baseline.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(baseline))});await page.getByRole('button',{name:'Vérifier le fichier',exact:true}).click();await page.getByRole('checkbox',{name:'Je confirme le remplacement des données par cette sauvegarde.',exact:true}).check();await page.getByRole('button',{name:'Confirmer la restauration',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'Restauration terminée.'})).toBeVisible();
  }
});
