import { test,expect } from '@playwright/test';
import type { Backup } from '../lib/types';
import { openFactSection, openContactChoices } from './report-helpers';
test('campagnes indépendantes, fiche commune, contacts préservés et revue mobile',async({page,request})=>{
  test.setTimeout(120000);const baseline:Backup=await(await request.get('/api/backup')).json();
  try{
    await page.goto('/campagnes/nouvelle');
    await page.getByLabel('Nom de la campagne',{exact:true}).fill('Campagne navigateur — devis');await page.getByLabel('Commune',{exact:true}).fill('Lyon');await page.getByLabel('Activité recherchée',{exact:true}).fill('Électricité');await page.getByLabel(/Codes d’activité NAF/).fill('43.21A');await page.getByLabel('Offre proposée',{exact:true}).fill('Améliorer les demandes de devis');await page.getByRole('button',{name:'Créer la campagne',exact:true}).click();
    await expect(page.getByRole('heading',{name:'Campagne navigateur — devis',exact:true})).toBeVisible();const campaignId=new URL(page.url()).pathname.split('/').at(-1)!;
    await page.getByRole('button',{name:'Lancer la recherche et l’analyse',exact:true}).click();await expect(page).toHaveURL(/campagnes\/lots/);const runUrl=page.url(),runId=new URL(runUrl).pathname.split('/').at(-1)!;
    await page.goto('/campagnes');await expect.poll(async()=>{const data=await(await request.get('/api/campaign-runs/'+runId)).json();return data.run.status;},{timeout:45000}).toBe('completed');
    let data:Backup=await(await request.get('/api/backup')).json();const candidate=data.campaignData!.candidates.find(c=>c.runId===runId&&c.company.name==='Atelier Démo — lot')!;
    await page.goto(runUrl+'?candidat='+candidate.id);await page.getByRole('button',{name:'Voir le rapport complet',exact:true}).click();
    await openFactSection(page,'quote404');await page.getByTestId('prospect-report').locator('[data-fact-id="quote404"]').getByRole('button',{name:'Utiliser pour mon approche',exact:true}).click();await openContactChoices(page);await page.getByRole('checkbox',{name:/contact@atelier-demo.test/}).check();await page.getByRole('button',{name:'Garder pour préparer un contact',exact:true}).click();
    data=await(await request.get('/api/backup')).json();const companyId=data.companies.find(c=>c.name==='Atelier Démo — lot')!.id;
    await page.goto('/campagnes/'+campaignId);await page.getByText('Gestion et entreprises déjà connues',{exact:true}).click();await page.getByRole('button',{name:'Dupliquer la configuration',exact:true}).click();await expect(page.getByRole('heading',{name:'Campagne navigateur — devis — copie',exact:true})).toBeVisible();const copyId=new URL(page.url()).pathname.split('/').at(-1)!;
    await page.getByText('Gestion et entreprises déjà connues',{exact:true}).click();await page.getByLabel('Entreprise déjà connue',{exact:true}).selectOption(companyId);await page.getByRole('button',{name:'Rattacher à cette campagne',exact:true}).click();
    await page.goto('/prospects/'+companyId+'?campagne='+copyId);await expect(page.getByLabel('Email professionnel',{exact:true})).toHaveValue('contact@atelier-demo.test');
    await page.getByRole('button',{name:'Prévoir la suite',exact:true}).first().click();const dialog=page.getByRole('dialog');await dialog.getByLabel(/^Action(?:\s|$)/).fill('Appeler pour la deuxième offre');await dialog.getByRole('button',{name:'Enregistrer l’action',exact:true}).click();await expect(dialog.getByRole('status')).toContainText('Prochaine action enregistrée.');await dialog.getByRole('button',{name:'Fermer',exact:true}).click();
    data=await(await request.get('/api/backup')).json();expect(data.companies.filter(c=>c.id===companyId)).toHaveLength(1);expect(data.campaignData!.participations.find(p=>p.companyId===companyId&&p.campaignId===campaignId)!.nextAction).toBeNull();expect(data.campaignData!.participations.find(p=>p.companyId===companyId&&p.campaignId===copyId)!.nextAction!.text).toBe('Appeler pour la deuxième offre');
    const unknown=data.campaignData!.candidates.find(c=>c.runId===runId&&c.company.name==='Artisan — site à confirmer')!;await page.setViewportSize({width:390,height:844});await page.goto(runUrl+'?candidat='+unknown.id);await expect(page.getByText('Site non confirmé',{exact:true})).toBeVisible();await page.getByText('Origine de l’entreprise et site identifié',{exact:true}).click();await expect(page.getByLabel('Corriger ou renseigner le site officiel',{exact:true})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)).toBe(false);await page.screenshot({path:'test-results/campaign-review-mobile.png',fullPage:true});
  }finally{
    await page.goto('/sauvegarde');await page.getByLabel('Fichier de sauvegarde JSON',{exact:true}).setInputFiles({name:'baseline.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(baseline))});await page.getByRole('button',{name:'Vérifier le fichier',exact:true}).click();await page.getByRole('checkbox',{name:'Je confirme le remplacement des données par cette sauvegarde.',exact:true}).check();await page.getByRole('button',{name:'Confirmer la restauration',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'Restauration terminée.'})).toBeVisible();
  }
});
