import { test,expect,type APIRequestContext } from '@playwright/test';
import { PDFDocument } from 'pdf-lib';
import type { Backup } from '../lib/types';
const read=async(request:APIRequestContext):Promise<Backup>=>(await request.get('/api/backup')).json();
for(const width of [1280,390])test(`qualification guidée, confirmation séparée et PDF relu à ${width}px`,async({page,request})=>{
 test.setTimeout(120000);await page.setViewportSize({width,height:900});const baseline=await read(request);
 try{
  await page.goto('/campagnes/nouvelle');await page.getByLabel('Nom de la campagne',{exact:true}).fill(`Qualification et PDF ${width}`);await page.getByLabel('Commune',{exact:true}).fill('Lyon');await page.getByLabel('Activité recherchée',{exact:true}).fill('Électricité');await page.getByLabel('Mots clés de recherche',{exact:true}).fill('électricien');await page.getByRole('button',{name:'Créer la campagne',exact:true}).click();await expect(page.getByRole('heading',{name:`Qualification et PDF ${width}`,exact:true})).toBeVisible();const campaignId=new URL(page.url()).pathname.split('/').at(-1)!;
  await page.getByRole('button',{name:'Lancer la recherche et l’analyse',exact:true}).click();await expect(page).toHaveURL(/\/campagnes\/lots\//);const runId=new URL(page.url()).pathname.split('/').at(-1)!;await page.goto('/campagnes');await expect.poll(async()=>(await(await request.get(`/api/campaign-runs/${runId}`)).json()).run.status,{timeout:45000}).toBe('completed');const candidate=(await read(request)).campaignData!.candidates.find(c=>c.runId===runId&&c.company.name==='Atelier Démo — lot')!;
  await page.goto(`/campagnes/${campaignId}/qualification?candidat=${candidate.id}`);const summary=page.getByTestId('qualification-summary');await expect(summary).toContainText('0/100');await expect(summary).toContainText('0/5');await expect(page.getByTestId('qualification-form').locator('fieldset')).toHaveCount(5);await expect(page.getByRole('button',{name:'Voir le rapport complet',exact:true})).toHaveAttribute('aria-expanded','false');
  const panel=page.locator('.qualification-suggestion[aria-label="Analyse pour Problème concret"]');const accept=panel.getByRole('button',{name:'Accepter la proposition',exact:true});await expect(accept).toBeDisabled();
  while(await panel.getByRole('button',{name:'Confirmer le constat',exact:true}).count()){await panel.getByRole('button',{name:'Confirmer le constat',exact:true}).first().click();await expect(summary).toContainText('0/100');await expect.poll(async()=>(await read(request)).campaignData!.candidates.find(c=>c.id===candidate.id)!.revision).toBeGreaterThan(candidate.revision);}
  await expect(accept).toBeEnabled();await accept.click();await expect(summary).toContainText('1/5');const draft=(await read(request)).campaignData!.candidates.find(c=>c.id===candidate.id)!.qualificationDraft!;expect(draft.answers.problem.answer).not.toBe('unknown');expect(draft.answers.fit.answer).toBe('unknown');await page.reload();await expect(summary).toContainText('1/5');
  await page.getByRole('button',{name:'Valider le prospect',exact:true}).click();await expect.poll(async()=>(await read(request)).campaignData!.candidates.find(c=>c.id===candidate.id)!.status).toBe('accepted');const kept=await read(request),companyId=kept.campaignData!.candidates.find(c=>c.id===candidate.id)!.companyId!,membership=kept.campaignData!.participations.find(p=>p.campaignId===campaignId&&p.companyId===companyId)!;expect(membership.qualification).toEqual(draft);
  await page.goto(`/campagnes/${campaignId}?etape=preparer&prospect=${companyId}`);await expect(page.getByTestId('qualification-summary')).toContainText('1/5');await page.getByRole('button',{name:'Préparer le bilan',exact:true}).click();await page.getByRole('button',{name:'Choisir les constats',exact:true}).click();await page.getByRole('checkbox',{name:/Le lien Demander un devis renvoie HTTP 404/}).check();await page.getByRole('button',{name:'Relire le bilan',exact:true}).click();const preview=page.waitForResponse(r=>r.url().endsWith('/api/client-briefs/preview'));await page.getByRole('button',{name:'Voir le véritable aperçu PDF',exact:true}).click();expect((await preview).headers()['content-type']).toContain('application/pdf');await page.getByRole('checkbox',{name:'J’ai relu le PDF et les constats sélectionnés.',exact:true}).check();await page.getByRole('button',{name:'Passer à la génération',exact:true}).click();await page.getByRole('button',{name:'Générer le PDF',exact:true}).click();const link=page.getByRole('link',{name:'Télécharger le PDF',exact:true});await expect(link).toBeVisible();const response=await request.get((await link.getAttribute('href'))!);expect(response.headers()['content-type']).toContain('application/pdf');expect((await PDFDocument.load(await response.body())).getPageCount()).toBe(2);const saved=await read(request);expect(saved.campaignData!.clientBriefs!.filter(b=>b.companyId===companyId)).toHaveLength(1);expect(saved.campaignData!.candidates.find(c=>c.id===candidate.id)!.research!.facts.some(f=>f.id==='quote404')).toBe(true);expect(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)).toBe(false);
 }finally{await page.goto('/sauvegarde');await page.getByLabel('Sauvegarde Brine ZIP ou ancien fichier JSON',{exact:true}).setInputFiles({name:'baseline.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(baseline))});await page.getByRole('button',{name:'Vérifier le fichier',exact:true}).click();await page.getByRole('checkbox',{name:'Je confirme le remplacement des données par cette sauvegarde.',exact:true}).check();await page.getByRole('button',{name:'Confirmer la restauration',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'Restauration terminée.'})).toBeVisible();}
});
