import {randomUUID} from 'node:crypto';
import type {CampaignRepository} from './campaign-repository';
import {aiStudyInputSchema,aiStudySchema,type AiStudy,type StudyTrial} from './ai-study-schema';
import {RESEARCH_MODEL,maximumOpenRouterCost,getResearchConfiguration,checkResearchProvider} from './research-providers';
import {getBudgetOverview,getProviderState} from './research-budget';
import type {Transaction} from '@libsql/client';
const now=()=>new Date().toISOString();
async function read(tx:Pick<Transaction,'execute'>,id:string){const row=(await tx.execute({sql:'SELECT payload FROM research_ai_studies WHERE id=?',args:[id]})).rows[0];if(!row)throw new Error('Étude introuvable.');return aiStudySchema.parse(JSON.parse(String(row.payload)));}
async function put(tx:Transaction,study:AiStudy){study.updatedAt=now();await tx.execute({sql:'UPDATE research_ai_studies SET payload=? WHERE id=?',args:[JSON.stringify(aiStudySchema.parse(study)),study.id]});}
export async function getAiStudy(repo:CampaignRepository,id:string){return read(repo.client,id);}
export async function listAiStudies(repo:CampaignRepository,campaignId:string,subjectId?:string){const rows=await repo.client.execute({sql:'SELECT payload FROM research_ai_studies WHERE campaignId=?',args:[campaignId]});return rows.rows.map(r=>aiStudySchema.parse(JSON.parse(String(r.payload)))).filter(s=>!subjectId||s.candidateId===subjectId||s.companyId===subjectId).sort((a,b)=>b.createdAt.localeCompare(a.createdAt));}
export async function createAiStudy(repo:CampaignRepository,input:unknown){
 const value=aiStudyInputSchema.parse(input),campaign=await repo.getCampaign(value.campaignId);if(campaign.status!=='active')throw new Error('Réactivez la campagne avant de préparer une étude.');
 let subject:AiStudy['subject'];if(value.candidateId){const context=await repo.getQualificationContext(value.candidateId);if(context.campaign.id!==campaign.id)throw new Error('Prospect d’une autre campagne.');subject={name:context.company.name,business:context.company.business,city:context.company.city,website:context.company.website};}else{const c=await repo.getCompany(campaign.id,value.companyId!);if(c.oppositionActive)throw new Error('Cette entreprise s’oppose aux contacts.');subject={name:c.name,business:c.business,city:c.city,website:c.website};}
 if(value.channel==='api'&&value.model!==RESEARCH_MODEL)throw new Error('Ce modèle automatique n’est pas configuré.');
 const {reviewed:_reviewed,...configuration}=value;const stamp=now(),study:AiStudy={...configuration,version:1,subject,mode:'web',status:'draft',revision:1,generation:1,owner:'',leaseUntil:'',createdAt:stamp,updatedAt:stamp,error:'',trials:value.questions.flatMap(q=>Array.from({length:value.repeats},(_,i)=>({id:randomUUID(),questionId:q.id,ordinal:i+1,status:'queued' as const,answer:'',sources:[],recordedAt:'',model:value.model,proofUrl:'',mention:null,recommendation:null,citation:null,error:'',reviewedAt:''})))};
 return repo.transaction(async tx=>{const prior=(await tx.execute({sql:'SELECT payload FROM research_ai_studies WHERE id=?',args:[value.id]})).rows[0];if(prior){const old=aiStudySchema.parse(JSON.parse(String(prior.payload)));if(old.campaignId!==value.campaignId||JSON.stringify(old.questions)!==JSON.stringify(value.questions)||old.repeats!==value.repeats||old.channel!==value.channel||old.model!==value.model||old.interface!==value.interface||old.candidateId!==value.candidateId||old.companyId!==value.companyId)throw new Error('Cette soumission désigne déjà une autre étude.');return old;}await tx.execute({sql:'INSERT INTO research_ai_studies(id,campaignId,payload) VALUES(?,?,?)',args:[study.id,study.campaignId,JSON.stringify(aiStudySchema.parse(study))]});return study;});
}
export async function controlAiStudy(repo:CampaignRepository,id:string,revision:number,operation:'launch'|'pause'){
 const current=await getAiStudy(repo,id);
 if(operation==='launch'&&(await repo.getCampaign(current.campaignId)).status!=='active')throw new Error('Réactivez la campagne avant de lancer cette étude.');
 if(operation==='launch'&&!current.trials.some(t=>['queued','running'].includes(t.status)))throw new Error('Cette étude ne comporte plus d’essai à exécuter. Préparez une nouvelle étude.');
 if(operation==='launch'&&current.channel==='api'){
  if(!(process.env.BRINE_TEST_FIXTURES==='1'&&process.env.VERCEL!=='1')){
   if(!getResearchConfiguration().openRouter)throw new Error('Ajoutez OPENROUTER_API_KEY côté serveur avant de lancer.');
   await checkResearchProvider(repo,'openrouter');
   const [budget,state]=await Promise.all([getBudgetOverview(repo),getProviderState(repo,'openrouter')]);const maximum=current.trials.filter(t=>t.status==='queued').length*maximumOpenRouterCost(true,2000);
   if(!state?.valid||Date.now()-Date.parse(state.checkedAt)>86400000)throw new Error('Vérifiez les sources et crédits dans Données et préférences.');
   if(maximum>budget.remainingEuroEstimate/1.35||maximum>(state.remaining||0))throw new Error('Le plafond théorique dépasse le budget disponible. Créez un pilote avec moins de questions ou de répétitions.');
  }
 }
 return repo.transaction(async tx=>{const study=await read(tx,id);if(study.revision!==revision)throw new Error('Étude modifiée ailleurs. Rechargez-la.');if(operation==='pause'){study.status='paused';study.owner='';study.leaseUntil='';study.generation++;}else{const campaign=JSON.parse(String((await tx.execute({sql:'SELECT payload FROM campaigns WHERE id=?',args:[study.campaignId]})).rows[0]?.payload));if(campaign.status!=='active')throw new Error('Réactivez la campagne avant de lancer cette étude.');if(study.channel!=='api')throw new Error('Cette étude se remplit manuellement, essai par essai.');if(study.status==='running'&&study.leaseUntil>now())throw new Error('Cette étude est déjà en cours.');study.status='queued';study.generation++;study.owner='';study.leaseUntil='';study.error='';}study.revision++;await put(tx,study);return study;});
}
export async function claimAiStudy(repo:CampaignRepository,id:string,owner:string,epoch:string){return repo.transaction(async tx=>{if(String((await tx.execute("SELECT value FROM campaign_meta WHERE id='epoch'")).rows[0]?.value)!==epoch)return null;const s=await read(tx,id);if(!['queued','running'].includes(s.status)||s.status==='running'&&s.leaseUntil>now())return null;s.status='running';s.owner=owner;s.leaseUntil=new Date(Date.now()+240000).toISOString();s.revision++;await put(tx,s);return s;});}
export async function updateStudyTrial(repo:CampaignRepository,run:AiStudy,epoch:string,trial:StudyTrial){return repo.transaction(async tx=>{if(String((await tx.execute("SELECT value FROM campaign_meta WHERE id='epoch'")).rows[0]?.value)!==epoch)return false;const current=await read(tx,run.id);if(current.owner!==run.owner||current.generation!==run.generation||current.status!=='running')return false;const index=current.trials.findIndex(t=>t.id===trial.id);if(index<0)return false;if(trial.status==='running'&&current.trials[index].status==='running'&&current.trials[index].executionOwner===run.owner)return false;current.trials[index]=trial;current.leaseUntil=new Date(Date.now()+240000).toISOString();current.revision++;await put(tx,current);return true;});}
export async function finishAiStudy(repo:CampaignRepository,run:AiStudy,epoch:string,error=''){return repo.transaction(async tx=>{if(String((await tx.execute("SELECT value FROM campaign_meta WHERE id='epoch'")).rows[0]?.value)!==epoch)return;const current=await read(tx,run.id);if(current.owner!==run.owner||current.generation!==run.generation)return;current.status=error?'paused':current.trials.some(t=>t.status==='queued'||t.status==='running')?'paused':'completed';current.error=error.slice(0,2000);current.owner='';current.leaseUntil='';current.revision++;await put(tx,current);});}
export async function saveManualStudyTrial(repo:CampaignRepository,id:string,revision:number,trialId:string,input:unknown){
 const fields=studyTrialSchemaForReview.parse(input);
 return repo.transaction(async tx=>{const study=await read(tx,id);if(study.revision!==revision)throw new Error('Étude modifiée ailleurs. Rechargez-la.');if(study.status==='running'||study.status==='queued')throw new Error('Attendez ou mettez l’étude en pause avant de corriger.');const trial=study.trials.find(t=>t.id===trialId);if(!trial)throw new Error('Essai introuvable.');if(study.channel==='api'&&(!trial.answer||!trial.recordedAt))throw new Error('Aucune réponse API à classer.');if(study.channel!=='api'&&!fields.proofUrl)throw new Error('Ajoutez un lien de preuve à ce relevé d’application.');
 if(study.channel==='api'&&(fields.answer!==trial.answer||fields.recordedAt!==trial.recordedAt))throw new Error('La réponse brute et la date API restent immuables.');
 for(const evidence of study.evidence||[])if(evidence.questionId===trial.questionId){evidence.fact.corrected=true;evidence.fact.scope+=' Ce relevé a été remplacé par une correction de classification : choisissez une nouvelle observation avant de le réutiliser.';}
 trial.reviews=[...(trial.reviews||[]),{at:now(),mention:trial.mention,recommendation:trial.recommendation,citation:trial.citation,answer:trial.answer,proofUrl:trial.proofUrl}].slice(-100);
 if(study.channel!=='api'){trial.answer=fields.answer;trial.proofUrl=fields.proofUrl;trial.recordedAt=fields.recordedAt;}
 Object.assign(trial,{mention:fields.mention,recommendation:fields.recommendation,citation:fields.citation,status:fields.classified?'valid':'unclassified',reviewedAt:now()});if(study.channel!=='api')trial.model=study.model;study.status=study.trials.every(t=>!['queued','running'].includes(t.status))?'completed':'draft';study.revision++;await put(tx,study);return study;});
}
import {z} from 'zod';
const studyTrialSchemaForReview=z.object({answer:z.string().trim().min(1).max(40000),proofUrl:z.string().max(2000).refine(v=>!v||/^https?:\/\//.test(v)&&z.string().url().safeParse(v).success),recordedAt:z.iso.datetime().refine(v=>Date.parse(v)<=Date.now(),'Une date future n’est pas un relevé.'),mention:z.boolean().nullable(),recommendation:z.boolean().nullable(),citation:z.boolean().nullable(),classified:z.boolean()}).strict().refine(v=>!v.classified||(v.mention!==null&&v.recommendation!==null),'Classez la mention et la recommandation ou gardez cet essai à vérifier.');

export async function selectStudyEvidence(repo:CampaignRepository,id:string,revision:number,questionId:string){const {studyEvidence}=await import('./ai-study-evidence');return repo.transaction(async tx=>{const study=await read(tx,id);if(study.revision!==revision)throw new Error('Étude modifiée. Rechargez les résultats.');if(['running','queued'].includes(study.status))throw new Error('Terminez ou mettez l’étude en pause avant de choisir une observation.');const evidence=studyEvidence(study,questionId);study.evidence||=[];if(study.evidence.some(e=>e.fact.id===evidence.fact.id))return study;study.evidence.push(evidence);study.revision++;await put(tx,study);return study;});}

export async function getAiStudyCost(repo:CampaignRepository,id:string){const rows=(await repo.client.execute({sql:'SELECT actualUsdMicros,reservedUsdMicros FROM research_operations WHERE operationKey LIKE ?',args:[`study:${id}:trial:%`]})).rows;return {actual:rows.filter(r=>r.actualUsdMicros!==null).reduce((n,r)=>n+Number(r.actualUsdMicros),0)/1000000,reserved:rows.filter(r=>r.actualUsdMicros===null).reduce((n,r)=>n+Number(r.reservedUsdMicros),0)/1000000,recordedCalls:rows.length};}
