import Link from 'next/link';
import { Plus, ArrowUpRight, Target } from 'lucide-react';
import { requireAuthenticated } from '@/lib/auth';
import { getCampaignRepository } from '@/lib/campaign-runtime';
export const metadata={title:'Campagnes'};
export default async function Campaigns(){await requireAuthenticated();const repo=await getCampaignRepository(),campaigns=await repo.listCampaigns();const data=await Promise.all(campaigns.map(async c=>({campaign:c,companies:await repo.listCompanies(c.id),runs:await repo.listRuns(c.id),reviewCount:(await Promise.all((await repo.listRuns(c.id)).map(r=>repo.listCandidates(r.id)))).flat().filter(r=>r.status==='review'||r.status==='needs_site'||r.status==='verify').length})));return <>
  <div className="page-heading"><div><p className="eyebrow">DES CIBLES, DES CONVERSATIONS</p><h1>Campagnes</h1><p className="page-subtitle">Une cible et un suivi distincts pour chaque offre.</p></div><Link href="/campagnes/nouvelle" className="button primary"><Plus size={16}/>Créer une campagne</Link></div>
  <div className="campaign-grid">{data.map(({campaign:c,companies,runs,reviewCount})=><article className="panel section-panel campaign-card" key={c.id}><div className="section-title"><Target size={20}/><span className="badge">{c.status==='active'?'Active':c.status==='paused'?'En pause':'Archivée'}</span></div><h2><Link href={`/campagnes/${c.id}`}>{c.name}</Link></h2><p>{c.targetBusiness} · {c.targetCity}</p><p className="small muted">{c.targetOffer||'Offre à préciser'}</p><div className="campaign-metrics"><span><strong>{reviewCount}</strong> à examiner</span><span><strong>{companies.filter(c=>!c.archived).length}</strong> prospects</span><span><strong>{runs.filter(r=>r.status==='running'||r.status==='queued').length}</strong> lots en cours</span><span><strong>{companies.filter(c=>c.nextAction&&!c.oppositionActive).length}</strong> actions</span></div><Link href={`/campagnes/${c.id}`} className="open-link">Ouvrir la campagne<ArrowUpRight size={14}/></Link></article>)}</div>
</>;}
