import Link from 'next/link';
import {notFound} from 'next/navigation';
import {requireAuthenticated} from '@/lib/auth';
import {getCampaignRepository} from '@/lib/campaign-runtime';
import {getAiStudy,listAiStudies,getAiStudyCost} from '@/lib/ai-study-storage';
import {StudyPreparation,StudyControl,StudyResults} from '@/components/ai-study';
import {getBudgetOverview} from '@/lib/research-budget';
import {maximumOpenRouterCost} from '@/lib/research-providers';
import {UI_LABELS} from '@/lib/labels';
export default async function AiStudyPage({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{candidat?:string;prospect?:string;etude?:string;nouvelle?:string}>}){
 await requireAuthenticated();const {id}=await params,query=await searchParams,repo=await getCampaignRepository(),campaign=await repo.getCampaign(id),budget=await getBudgetOverview(repo);
 let study=query.etude?await getAiStudy(repo,query.etude):null;if(study&&study.campaignId!==id)notFound();
 const candidateId=study?.candidateId||query.candidat||null,companyId=study?.companyId||query.prospect||null;
 const context=candidateId?await repo.getQualificationContext(candidateId):null;if(context&&context.campaign.id!==id)notFound();const company=companyId?await repo.getCompany(id,companyId):context?.company;
 const studyCost=study?await getAiStudyCost(repo,study.id):null;
 const studies=await listAiStudies(repo,id,candidateId||companyId||undefined),newHref=`/campagnes/${id}/visibilite-ia?${candidateId?'candidat='+candidateId:companyId?'prospect='+companyId:''}&nouvelle=1`;
 const companies=!company&&!study?await repo.listCompanies(id):[],candidates=!company&&!study?await repo.listCampaignCandidates(id):[];
 return <div className="ai-study-page"><Link className="back-link" href={`/campagnes/${id}`}>← {campaign.name}</Link><div className="page-heading"><div><p className="eyebrow">{campaign.name} · Recherches documentées</p><h1>{UI_LABELS.aiVisibility}</h1><p className="page-subtitle">Des questions précises, plusieurs essais, des résultats à vérifier.</p></div>{company&&<Link className="button secondary" href={newHref}>Préparer une nouvelle étude</Link>}</div>
 {process.env.BRINE_TEST_FIXTURES==='1'&&process.env.VERCEL!=='1'&&<p className="data-notice">Recette isolée : données fictives, fournisseur simulé, aucune recherche payante.</p>}
 {!company&&!study?<section className="panel section-panel"><h2>Choisir une entreprise</h2><p>Ouvrez une étude depuis sa qualification ou choisissez-la ici.</p>{companies.map(c=><p key={c.id}><Link href={`/campagnes/${id}/visibilite-ia?prospect=${c.id}`}>{c.name} →</Link></p>)}{candidates.filter(c=>!c.companyId).map(c=><p key={c.id}><Link href={`/campagnes/${id}/visibilite-ia?candidat=${c.id}`}>{c.company.name} →</Link></p>)}</section>:study?<section className="panel section-panel study-workspace"><h2>{study.subject.name}</h2><p>{study.interface} · {study.model||'Modèle inconnu'} · Recherche web · {study.trials.filter(t=>!['queued','running'].includes(t.status)).length}/{study.trials.length} essais réalisés · {study.status==='paused'?'En pause':study.status==='completed'?'Terminé':study.status==='draft'?'Plan enregistré':study.status==='queued'?'En attente':'En cours'}</p><p className="field-help">La ville est un contexte demandé ; localisation effective du moteur non vérifiée. {study.repeats===1?'Un seul essai par question, aucune répétition mesurée.':''}</p>{study.channel==='api'&&<details><summary>Budget et méthode</summary><p>Plafond de ce plan : {(study.trials.length*maximumOpenRouterCost(true,2000)).toFixed(2)} $. Chaque appel est réservé avant exécution ; coût réel connu pour cette étude : {studyCost!.actual.toFixed(4)} $ ; réservations de cette étude restant à rapprocher : {studyCost!.reserved.toFixed(4)} $. Budget partagé restant : {(budget.remainingEuroEstimate/1.35).toFixed(2)} $.</p><p>Chaque essai a une requête neuve sans historique partagé. Une reprise conserve les réponses et n’exécute que les essais restants. Un résultat/coût incertain n’est pas refacturé automatiquement.</p></details>}{study.error&&<p className="form-error" role="alert">{study.error}</p>}<StudyControl study={study}/><StudyResults study={study}/></section>:company&&<section className="panel section-panel study-workspace"><StudyPreparation campaignId={id} candidateId={candidateId} companyId={companyId} name={company.name} business={campaign.keywords?.split(/[,;\n]/)[0]?.trim()||company.business||campaign.targetBusiness} city={company.city||campaign.targetCity} maximumPerTrial={maximumOpenRouterCost(true,2000)} budgetRemaining={budget.remainingEuroEstimate/1.35}/></section>}
 {studies.length>0&&<details className="study-history" open={!study&&query.nouvelle!=='1'}><summary>Voir les relevés précédents ({studies.length})</summary>{studies.map(s=><p key={s.id}><Link href={`/campagnes/${id}/visibilite-ia?etude=${s.id}`}>{s.subject.name} · {new Date(s.createdAt).toLocaleString('fr-FR',{timeZone:'Europe/Paris'})} · {s.interface} · {s.trials.length} essais</Link></p>)}</details>}
 </div>;
}
